### ISSUE TITLE
Tiles Web-Part – Some Office UI Fabric Icons not working

### ISSUE THREAD

**Issue by patrickabel** [SharePoint/sp-starter-kit#101]
I have noticed with the **Tiles web-part** in the SP Starter Kit is **not supporting all of the Office UI Fabric icons**. Here are a few icons for example that aren't working for me:
- PublishCourse
- Commitments
- ConnectContacts

Is this a versioning issue with node modules or npm dependencies? If so, could I get some help with the necessary updates in order for this web-part to support all icons within the Office UI Fabric suite. 

#### Category
- [ ] Question
- [ X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I expect to be able to set the **IconName** value to "ConnectContacts" on the supporting list of the Tiles web-part and this icon be visible in the UI.

#### Observed Behavior

Several of the Office UI Fabric Icons noted above (among others) are not rendered within the Tiles web-part.

**Comment by eoverfield** [comment]
@patrickabel Yes, a known issue, please refer to the following post:
https://github.com/SharePoint/sp-starter-kit/issues/76

**Comment by bcameron1231** [comment]
Closing - Duplicate and Related to #76
