### ISSUE TITLE
Attached sites not using portal colour theme

### ISSUE THREAD

**Issue by Chris-Leeworthy** [SharePoint/sp-starter-kit#103]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

I have ticked two boxes as I'm not sure if the problem lies with the starter kit or SharePoint's implementation of colour theming between hub and attached sites. 

I have up to date PNP Powershell, my developer tenant has first release active for all users and the script ran with no errors that I noticed.

#### Expected or Desired Behavior

Sites linked to the portal hub site should share the same colour theme as the hub site. 

#### Observed Behavior

Although the 'Human Resources' and 'Marketing' sites are linked to the hub site they do not share the same colour theme.

**HUB**
![pic1](https://user-images.githubusercontent.com/13499355/43129497-78da3090-8f2c-11e8-8f5f-ded82fc50d0c.png)

**Human Resources**
![pic2](https://user-images.githubusercontent.com/13499355/43129570-a8cafc4e-8f2c-11e8-958c-268a3d483b4d.png)

**Marketing**
![pic3](https://user-images.githubusercontent.com/13499355/43129665-ddea323c-8f2c-11e8-9c48-14d3c5566176.png)

I had read that it might take time for the other sites to inherit the hub site theme but the images above were generated 24 hours after I ran the Deploy.ps1 so this doesn't seem like a propagation delay.

The two sites indicate that they are linked to the hub but the colour themes do not match.

#### Steps to Reproduce

Run the script.

**Comment by vegardStromsoy** [comment]
Could this be related to the Notes in this article: https://support.office.com/en-us/article/set-up-your-sharepoint-hub-site-e2daed64-658c-4462-aeaf-7d1a92eba098 ?
"If the theme for the site that was converted to a hub site was never changed from the original theme assigned by SharePoint at the time it was created, any sites associated with it will not inherit the hub site theme."

**Comment by vegardStromsoy** [comment]
Having a similar problem (not using PnP Starter Kit) where site is created, converted to hub site, sites attached, theme changed: not propagating theme changes. If I create site, convert to hub site, change from default theme to another, attach sites: propagating theme changes. 
As I understand the note in the article you have to change theme once _before_ attaching sites to the hub.

**Comment by iainl** [comment]
Also having the same issue.

**Comment by bcameron1231** [comment]
Hi, we are working on cleaning up the issues list. I understand this is an old issue. If this is still affecting you, could you please re-open a ticket in the issues list. Thanks!
