### ISSUE TITLE
Creating sites

### ISSUE THREAD

**Issue by spurr82** [SharePoint/sp-starter-kit#104]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Solutions provisions without error

#### Observed Behavior

Creating ontogen-marketing
npm : npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
At E:\DEV\sp-starter-kit-master\provisioning\deploy.ps1:76 char:5
+     npm install
+     ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN option...kidar/fsevents::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm
 
WARN
 
notsup
 Not compatible with your operating system or architecture: fsevents@1.2.4
npm
 
WARN
 
optional
 Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm
 
WARN
 
notsup
 Not compatible with your operating system or architecture: fsevents@1.2.4

**Comment by eoverfield** [comment]
Those are pretty common warning messages when npm install is ran by the deployment script to load up your node_modules found within the solution folder. Once all of the modules are loaded you should be able to run the deploy script again and you should not receive these warnings.

**Comment by spurr82** [comment]
ok, i do repeatedly get this error though

**Comment by bcameron1231** [comment]
@spurr82 as Eric mentioned, these aren't really errors.  They are just warnings.  In the meantime, can you provide what version of NPM you are using?

**Comment by eoverfield** [comment]
If these errors are starting with the line 76, in particular a message on npm install, you are either running the deploy script each time with the --Build parameter, which normally is not needed, or for some reason the SPFx solution package sppgk file is still not being created properly.

The script looks in .\solution\sharepoint\solution\ for sharepoint-starter-kit.sppkg. If that package is not found, then the script looks to build it.

I suggest you check to see if this file exists on your workstation. If it does not after running the deployment script, check your version of node as @bcameron1231 mentioned, as well as attempt to run "npm install", then gulp build, gulp bundle, gulp package-solution within the solution folder manually to see how the SPFx build process works for you.

**Comment by spurr82** [comment]
I created a W10 vm in azure, to start a fresh with the install of each part of the required. I have managed to get the solution deploed, some warnings but all good. (apart from im not able to add foot links, thworing a JS error )

Uncaught TypeError: Cannot read property 'concat' of undefined
    at t._saveEdit (portal-footer-application-customizer_3f174defe3730bc17f2d7c1335df1fc6.js:44)
    at Object.r (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at a (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at Object.s [as executeDispatchesInOrder] (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at f (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at m (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at Array.forEach (<anonymous>)
    at r (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at Object.processEventQueue (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at r (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:660)

**Comment by eoverfield** [comment]
@spurr82 great to hear. It appears as though you started a new issue for the JS error (excellent) here: https://github.com/SharePoint/sp-starter-kit/issues/128. I suggest this issue be closed.
