### ISSUE TITLE
Provisioning

### ISSUE THREAD

**Issue by spurr82** [SharePoint/sp-starter-kit#105]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

Provisioning solution
Apply-PnPProvisioningTemplate : Object reference not set to an instance of an object.
At E:\DEV\sp-starter-kit-master\provisioning\deploy.ps1:98 char:5
+     Apply-PnPProvisioningTemplate -Path "$PSScriptRoot\solution.xml"  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by bcameron1231** [comment]
Hi @spurr82 , can you confirm for us that you have followed through the "Getting Started" section of the documentation and completed the pre-requirements? Did you manually upload the .sppkg file to the app catalog?

**Comment by eoverfield** [comment]
@spurr82 please also review https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/common-provision-results.md. The null error is one I ran across a long time ago, but I don't remember why, and couldn't duplicate it since. 

Please also try turning on debugging logging.
Set-PnPTraceLog -On -Level Debug

**Comment by spurr82** [comment]
Hi yes, followed the getting started, and tried both manually uploading

**Comment by spurr82** [comment]
thanks @eoverfield ill check that out also

**Comment by bcameron1231** [comment]
Hi, I am working on cleaning up / working on the issues list. I understand this is an old ticket and may not be relevant to you anymore, can you confirm whether this is still a problem for you?
