### ISSUE TITLE
Whether Validations working in Tiles Webpart to check invalid URL 

### ISSUE THREAD

**Issue by splearner** [SharePoint/sp-starter-kit#106]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Bug
- [ ] Enhancement

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue on generic SharePoint topic or dev documentation, please use the (sp-dev-docs Issue list)[http://aka.ms/spdev-issues]
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
@Preethirasu could you please clarify if you are reporting a bug, or making a request? Is there an expected behavior that is missing?

**Comment by Preethirasu** [comment]
PropertyFieldCollection Data is not validating the Title value or URL(to check whether URL is valid or not ). But i can see that method is there in sp-dev-fx-property-controls-master -->collectionData.
Is anyone else facing the same issue ?

**Comment by estruyf** [comment]
@splearner it is by design the URL of the tiles and links web parts are not validated. It was requested that relative URLs could be entered. 

Right now the URL field in the `PropertyFieldCollectionData` control is configured as a `string`. If you want to change the behaviour, you can update the following line: https://github.com/SharePoint/sp-starter-kit/blob/master/solution/src/webparts/tiles/TilesWebPart.ts#L73 from `type: CustomCollectionFieldType.string` to `type: CustomCollectionFieldType.url`.

**Comment by splearner** [comment]
@estruyf i have changed the Type as CustomCollectionFieldType.url only but i am not getting the error message stating  "Provided Url is invalid". Please help me out to fix the issue

**Comment by estruyf** [comment]
Can you show me a screenshot of where you get this?

**Comment by splearner** [comment]
when i tried to debug the solution,once it enter into the regex function in Collection Data it returns string.invalid error but alert or validation is not working.
it accepts any value in URL field.

**Comment by estruyf** [comment]
@splearner can you give me more details on the `@pnp/spfx-property-controls` version you are using + in which browser (version) you are testing this?

**Comment by splearner** [comment]
@estruyf ia m using "@pnp/spfx-property-controls": "1.8.0" and testing in Chrome browser

**Comment by estruyf** [comment]
@splearner how does the field render? It should look like this when an invalid URL is entered. We choose not to show a message in the control because it causes some control jumping behaviour.

![screenshot 2018-08-09 14 09 56](https://user-images.githubusercontent.com/2900833/43897951-0c1dbbd4-9bde-11e8-90c7-f9933a6f3a71.png)
![screenshot 2018-08-09 14 09 19](https://user-images.githubusercontent.com/2900833/43897952-0c3870c8-9bde-11e8-8072-12410b6174ec.png)
