### ISSUE TITLE
AADSTS50058  error on Personal Mail and all Graph Webpart

### ISSUE THREAD

**Issue by tioger** [SharePoint/sp-starter-kit#109]
_Category_

- [ ]     Question
- [x]     Bug
- [ ]     Enhancement

_Expected or Desired Behavior_

Expecting the web parts to show personal mail or events without prompting for additional credentials.
Observed Behavior

When adding the Personal Mail or all other graph web parts a message pops up that says "Additional credentials are required to show this page correctly." When I click "OK" the page reload and this pop up message appear a second time and a loop start  =>> click OK => reload => pop up  =>Ok ...
Before the first reload my webpart give this message 

" AADSTS50058 : A silent sign-in request was sent but no user is signed in . Trace ID: 1ff65364-24e6-4bde-90b5-91a16e912100 Correlation ID: f3231d16-52ee-46aa-917a-9d8dd1c30455"

_Steps to Reproduce_
This error doesn't appear all the time, i think this error appear when i don't check "Keep me logged in" 
Add the Personal Email or all other graph web parts to a Modern Page.

**Comment by MGoelles24** [comment]
Did you have applied the pnp template?

Maybe the API permissions for Microsoft Graph are missing.

**Comment by bcameron1231** [comment]
Hi, I realize this is an older ticket. We are finally going back through some of these issues to make sure we can get them resolved. 

Has this been resolved for you, is it still an issue or can this issue be closed?
