### ISSUE TITLE
Apply-PnPProvisioningTemplate : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jcollinsks** [SharePoint/sp-starter-kit#11]
#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I'm trying to deploy to my environment, I've tried on multiple computers and even started from scratch with a development environment.

#### Observed Behavior

![image](https://user-images.githubusercontent.com/2774588/40581219-b5a78c14-6107-11e8-853a-36f1810e2ded.png)

#### Steps to Reproduce

.\deploy.ps1 -TenantUrl https://tenant.sharepoint.com -SitePrefix Demo
-Company Company Name -WeatherCity "Las Vegas" -StockSymbol "MSFT"

**Comment by tommytetley** [comment]
Hi J,

Did you find a solution to this error? I'm encountering the same when trying to deploy the Sharepoint starter kit.

Thanks,
Tommy

**Comment by eoverfield** [comment]
@tommytetley have you referenced the installation documentation? https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/common-provision-results.md. The null error is not specifically referenced, although if you follow through the steps, that may help.

I suggest you provide a screenshot of your specific error and open a new issue as this issue is over 3 months old and there have been a few updates.

**Comment by anandasanyal** [comment]
Can you please share the solution, as I'm getting the same error. I'm using following commands. Made all the pre-requisites and running the command from the [provisioning] folder.

Apply-PnPTenantTemplate -Path .\starterkit.pnp -Parameters @{"Company"="Software Logics";"SiteUrlPrefix"="SL";"WeatherCity"="Seattle"}

Thank you.

**Comment by jcollinsks** [comment]
@anandasanyal are you connecting to the tenant admin url https://tenant-admin.sharepoint.com to deploy?

**Comment by anandasanyal** [comment]
I'm connecting to the tenant not the tenant admin.

**Comment by jcollinsks** [comment]
Because you're creating site collections, I am pretty certain you have to be connected to the tenant admin site.

**Comment by anandasanyal** [comment]
No just tried that well, did not work.

**Comment by anandasanyal** [comment]
Finally I've used [https://provisioning.sharepointpnp.com/] for provisioning.
It would be good if it can be done from PnP Powershell.
Thank you
