### ISSUE TITLE
Error on the webpart's deployment

### ISSUE THREAD

**Issue by GuigzUp13** [SharePoint/sp-starter-kit#110]
Hi, thank you in advance for analysing my issue. I work on a trial Dev Tenant with Sharepoint Online SPFx. I'm trying to develop webparts like those in the starter-kit.

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I need to deploy some webparts from Sp-starter-kit (like recentlyUsedDocument).

#### Observed Behavior

"Error in the application" during the deployment of my webpart recentlyUsedDocument

When I check on the administration panel -> webApiPermissionManagement : 
[HTTP]:500 -  [CorrelationId]:85d87f9e-30d1-0000-22fb-8b3a8b33e17d [Version]:16.0.0.7918 - The requested operation is part of an experimental feature that is not supported in the current environment
[HTTP]:500 -  [CorrelationId]:85d87f9e-80d6-0000-22fb-8dc795b183ea [Version]:16.0.0.7918 - The requested operation is part of an experimental feature that is not supported in the current environment

Yeoman version : 2.0.4
Npm version : 5.6.0

#### Steps to Reproduce

Get webpart's files of "recentlyUsedDocument" from sp-starter-kit in this own project file.
Build package solution *.sppkg 
Deploy in AppCatalog

**Comment by elpinto007** [comment]
Did you check if your tenant is on track for Targeted release for everyone?

**Comment by GuigzUp13** [comment]
thank you for your answer. I just set and for the moment it doesn't work but I'll wait a little bit that maybe the tenant make it update.

**Comment by GuigzUp13** [comment]
It works !! 
Tutorial to set tenant in targeted release or standard version 
https://support.office.com/en-us/article/set-up-the-standard-or-targeted-release-options-in-office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47?ui=en-US&rs=en-US&ad=US
