### ISSUE TITLE
Question: Will I need to redeploy this solution whenever there is an update to this repo?

### ISSUE THREAD

**Issue by JosephG60** [SharePoint/sp-starter-kit#111]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Question
Hey guys. I'm currently in the process of learning SharePoint admin so that I can have a place where I can put my freelance projects as well as invite a virtual assistant help me complete them.

I have a question in regards to the maintainability of my SharePoint sites with this starter kit implemented. When updates are added to this solution, will I need to download those changes (via GitHub Desktop) and re-deploy the solution (via PowerShell) to have the updates reflected on my site?

What I'm imagining is having my sites separate from the sites that the starter kit creates, but still have my sites use some of the components from the starter kit sites. An update for the starter kit comes out, so I redeploy the updated starter kit to my tenant and have my starter kit sites updated. Is this correct?

Really enjoy the awesome work, keep it up!

Thanks,
Joe

**Comment by bcameron1231** [comment]
Hi, i noticed this is an old ticket and may not be relevant to you.

However, to answer your question, yes, you could need to re-deply an updated .sppkg package for any new updates to the Starter kit.
