### ISSUE TITLE
Typo in Extensions > AlertNotification

### ISSUE THREAD

**Issue by elpinto007** [SharePoint/sp-starter-kit#114]
#### Category
- [ ] Question
- [ x ] Bug
- [ ] Enhancement
#### Expected or Desired Behavior
Spelling of the Alert Notification is incorrect. Came across this while trying to recreate as a new standalone solution.

#### Observed Behavior
Spelled as "AlertNotiticationApplicationCustomizer" - very easy to overlook the 't' for an 'f'

**Comment by bcameron1231** [comment]
This issue is resolved with #348 , will show up in the next version of the starter kit.
