### ISSUE TITLE
CollabFooter not working if default language on termstore is not set to english

### ISSUE THREAD

**Issue by jakobnotseth** [SharePoint/sp-starter-kit#115]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

TermStore default language should not have affect on functionality. It should query termsets using the default locale on termstore in order to get termset in return. If not, the requirements should specify to set english locale as the default termstore language.

#### Observed Behavior

In my environment, termstore was set to default norwegian default, loading termsets subsequently failed since SPTaxonomyService query specifies only english locale when getting termset.

#### Steps to Reproduce

Change default language to anything other than english on termstore.

**Comment by jakobnotseth** [comment]
I know the solution only currently works in english, but requirements forget to specify english default on termstore. Otherwise, it should be made generic using the default termstore locale instead of a fixed locale.

**Comment by jakobnotseth** [comment]
Could perhaps be related to issue #50

**Comment by eoverfield** [comment]
I do not believe the issues are related although they are both language related. I will see what I can offer in the way of updated guidance, or update the provisioning template.

**Comment by eoverfield** [comment]
I submitted a PR, https://github.com/SharePoint/sp-starter-kit/pull/116, to address this. I am recommending a documentation approach as we want to target English by default as overall the solution does require English culture code elsewhere. A manual change should work for those that need it, it did work for me.

**Comment by bcameron1231** [comment]
Closing - Fixed via PR
