### ISSUE TITLE
Problems with running deploy.ps1

### ISSUE THREAD

**Issue by EdwKro** [SharePoint/sp-starter-kit#117]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

When running deploy.ps1 I get the following:

![image](https://user-images.githubusercontent.com/42034600/43775624-a81cc38c-9a4d-11e8-982b-57e061402fb3.png)

after this it's an endless rain of errors.

I have the latest version of powershell
I have run through the prereqs
I have the app uploaded to my appstore and the API's approved.

please help! =)

**Comment by westerdaled** [comment]
My advice would be to open deploy.ps1  or fuctions.ps1 in IDE ( or VS Code) and place breakpoint in the New-SiteHierarchy function around on or before one of the statements below.

```
$hubParams.Connection = $connection
 New-PnPSite @hubParams
```
Then inspect all parameters.  if these look ok, you are free to try creating a test site to check you have the correct permissions - you should be logging in as a global admin ( without 2-factor) plus adding the same login account to the term store admin.    I have done a number of deployments of the sp-starter-kit, sometimes stepping through each line to check it. The error you have looks to me more environmental.

**Comment by EdwKro** [comment]
Thanks for the reply. I am global admin and am already trying to do this on a test-site. I do not have 2-factor login.

I'll have a look and see if I can place a breakpoint and see what's going on

**Comment by eoverfield** [comment]
It looks to me as though there is a problem with PnP PowerShell. It is having problems loading local assemblies.

Check out: https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/common-provision-results.md#error-inproper-version-of-pnp-powershell-installed. Can you run the PS commandlet provided in the doc above and share the version of PnP PS you are using?

**Comment by privero** [comment]
I had the same error today, running PnPPowerShellOnline 3.0.1808.0. Reverting to 2.28.1807.0 allowed the Starter Kit to install normally.

**Comment by eoverfield** [comment]
@privero ah, interesting. I have not tried 3.0.1808.0 myself. @erwinvanhunen could you provide any insight into the latest version of PnPPS (https://github.com/SharePoint/PnP-PowerShell/releases) and starter kit? Thanks.

**Comment by EdwKro** [comment]
@privero that solution works just fine, thank you so much!

**Comment by bcameron1231** [comment]
Closing - Answered and solution works per Author.
