### ISSUE TITLE
Provisioning fails when managed path for groups is set to teams

### ISSUE THREAD

**Issue by appieschot** [SharePoint/sp-starter-kit#12]
#### Category
- [ ] Question
- [x] Bug
- [x] Enhancement

#### Expected or Desired Behavior
The script fails when the tenant is having the default managed path set to teams for group creation. Groups get created but applying of the template fails as /sites/ is captured hardcoded in the script. Suggestion would be to include guidance to configure the tenant to use /sites/, and for future releases to update the script to determine what managed path should be used.  

#### Observed Behavior
Script fails on line 139 if group is created under the managed path /teams/ 

#### Steps to Reproduce
Go to the SPO admin center, select 'settings' and navigate to the Create Groups under setting to change the managed path to /teams/

**Comment by eoverfield** [comment]
a related issue #30 addressed. Closing.
