### ISSUE TITLE
Additional Credentionals are required to show this page correctly (in IE not Chrome/FireFox) for AadHttpClient

### ISSUE THREAD

**Issue by SBolla0** [SharePoint/sp-starter-kit#120]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue on generic SharePoint topic or dev documentation, please use the (sp-dev-docs Issue list)[http://aka.ms/spdev-issues]
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by SBolla0** [comment]
In IE  alert `message` "Additional credentials are required to show this page correctly"
![aadhttpclient](https://user-images.githubusercontent.com/42420613/44171410-af04d400-a0c9-11e8-8845-b6850700d054.GIF)

**Comment by SBolla0** [comment]
SPFx works fine in FireFox and Chrome, Issue is when IE is used.

**Comment by TM4CH** [comment]
Same issue here, working with GRAPH API. 
 
I tried to add:     
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.ReadWrite.All"
      }
    ]

in the package-solution.json file.

**Comment by vaibhavg98** [comment]
Same here.
I am also getting this error. It goes on in infinite loop.
However, it does work in incognito mode.

**Comment by TM4CH** [comment]
I was testing the webpart on a demo tenant. Placed it on my own tenant and it worked!
So the problem is mostly by the logged in user(permissions).

**Comment by vaibhavg98** [comment]
That's great!
BTW, by demo tenant do you mean the "free" one?
And own tenant?

**Comment by TM4CH** [comment]
Yes, demo = free one. And with own I mean the companies.

![](https://i.stack.imgur.com/AzQ4d.jpg)

With the demo I couldn't manage everything (ownership, site collections).

**Comment by bcameron1231** [comment]
Hi, I am working through some of the issues in the issues list. I understand this is an old ticket and may not be relevant to you.

Is this still an answer or can it be closed?
