### ISSUE TITLE
MyLinks in Portal Footer

### ISSUE THREAD

**Issue by elpinto007** [SharePoint/sp-starter-kit#122]
#### Category
- [X] Question
- [] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Deploy the footer solution to a SharePoint site and have it available on the site with links from the Portal Footer links list
#### Observed Behavior
The footer fails to bundle and render on the page. The solution errors with a "Module not found" message for the "MyLinksStrings" module when trying to run the bundle command.

#### Steps to Reproduce
Create a new solution for Application Customizer, copy across the required code for the portal footer, and run the build/bundle/package command. An error occurs when trying to bundle the solution.
I have published my code on [Git here](https://github.com/elpinto007/sp-starter-portal-footer). You can clone and bundle it to view the error.

EDIT:
Changed the category to Question only as requested

**Comment by elpinto007** [comment]
Something I did notice in my solution. The JS files do not have:
`"use strict";`

I have also noticed that the following line appears in most of the JS files in the starter kit but does not for me:
`Object.defineProperty(exports, "__esModule", { value: true });`

I wonder if this has something to do with the library version I have in my solution vs the starter kit.

**Comment by bcameron1231** [comment]
Thanks for logging this. If possible, could you modify your post to be just a question and not a bug because the issue has arisen from the modification of the out of the box starter kit.

What looks like is happening is that you have modified the config.json file and removed the localizedResource value for the MyLinksStrings. 

I would start by adding  modifying your config.json from 
```
"localizedResources": {
    "PortalFooterApplicationCustomizerStrings": "lib/extensions/portalFooter/loc/{locale}.js"
  }
```
to
```
"localizedResources": {
    "PortalFooterApplicationCustomizerStrings": "lib/extensions/portalFooter/loc/{locale}.js",
    "MyLinksStrings": "lib/common/myLinks/loc/{locale}.js"
  }
```

and see where that gets you :)

**Comment by elpinto007** [comment]
Hi Beau
Awesome! Thanks for the tip. That did get rid of the error for me. I still got the following message when I did the bundle:

`The build failed because a task wrote output to stderr. Exiting with exit code: 1`

There are no other messages give in the console.

**Comment by elpinto007** [comment]
I deployed it to my dev tenant hoping to see some more information. 
`NotificationsTest:1 Uncaught (in promise) Error: ***Failed to load component "a83c65db-900d-478b-84c7-65e5bc3567ba" (PortalFooterApplicationCustomizer).
Original error: ***Failed to load entry point from component "a83c65db-900d-478b-84c7-65e5bc3567ba" (PortalFooterApplicationCustomizer).
Original error: Error loading https://component-id.invalid/a83c65db-900d-478b-84c7-65e5bc3567ba_0.0.1
	Cannot read property 'selectedLink' of undefined
    at t [as constructor] (sp-pages-assembly_en-us_8f1820dcfb5d7e4e5ee46852e5afabf1.js:710)
    at new t (sp-pages-assembly_en-us_8f1820dcfb5d7e4e5ee46852e5afabf1.js:1583)
    at Function.e.buildErrorWithVerboseLog (sp-pages-assembly_en-us_8f1820dcfb5d7e4e5ee46852e5afabf1.js:1583)
    at Function.e.buildLoadComponentError (sp-pages-assembly_en-us_8f1820dcfb5d7e4e5ee46852e5afabf1.js:1583)
    at sp-pages-assembly_en-us_8f1820dcfb5d7e4e5ee46852e5afabf1.js:1583`

**Comment by bcameron1231** [comment]
It also looks like your solution may be a bit older than the current solution in the repo.

If you run your gulp build does it compile with no errors?

**Comment by elpinto007** [comment]
Yup. I managed to do a clean, build, bundle and package. Tried it again, didnt work. I am increasing the version number in the package-solution.json file - that shouldnt affect anything I believe?
I get the exact same error as above, where it cannot read property selectedLink. I thought it might be the custom user property. But my tenant has that, I just double checked as well. 

Do I need to have a Public CDN created to host any files? I cant find this exact error online for my situation, but I came across it for someone else and their solution was hosting some files on the CDN [here](https://sharepoint.stackexchange.com/questions/209886/spfx-failed-to-load-path-dependency-from-component)

**Comment by bcameron1231** [comment]
Nope, there has to be another issue in your solution. When I get a moment, I will download your solution and see what I can find out.

**Comment by eoverfield** [comment]
@elpinto007 it looks to me as though spfx 1.5.1 removed an inherited dependency on office-ui-fabric-react, thus you added this to your dependencies. The version you used changed the way that commandBar and possibly other react components, thus in MyLinksDialog.tsx, you made a few changes?

My suggestion, and how I was able to get your code to work, was to first change package.json to reference an older version of ui fabric react:
"office-ui-fabric-react": "5.21.0"

Run npm install, or to be safe, remove node_modules and then run npm install

Then I suggest you take MyLinksDialog.tsx from sp starter kit and replace what you have. Get that code working correctly in the browser, and then if you want to make additional changes to MyLInksDialog.tsx, do so.

If you do not want to go through this effort I suggest you look at MyLInksDialog.tsx as I believe your root problem is there.

**Comment by elpinto007** [comment]
Thanks @eoverfield ! Yes, the newer version of office-ui-fabric reworks the commandbar quite a bit. So I made the changes in the MyLinksDialog.tsx for the new constructors. I was hoping to be able to get the newer version working so it may help others in the future who want to base their solutions using the new ui fabric react.

I'll revert to the older library and get the solution working.
Thanks for your help guys! Really do appreciate your help with the starter kit.
