### ISSUE TITLE
Documenation and broken links

### ISSUE THREAD

**Issue by Shamrh** [SharePoint/sp-starter-kit#123]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

### Link is broken 
![image](https://user-images.githubusercontent.com/32353229/44567013-39b29680-a78e-11e8-82fb-6c433de1b56b.png)

### documentation of list seems to be incorrect
![image](https://user-images.githubusercontent.com/32353229/44567081-71214300-a78e-11e8-962f-5c979b675906.png)

**Comment by bcameron1231** [comment]
Thank you @Shamrh . I have created a PR to fix this issue. #124

**Comment by VesaJuvonen** [comment]
#124 merged, so closing.

**Comment by VesaJuvonen** [comment]
thx @bcameron1231  for the fix and @Shamrh for reporting the issue.
