### ISSUE TITLE
Cannot select custom theme

### ISSUE THREAD

**Issue by nicholas-morris** [SharePoint/sp-starter-kit#125]
Hi,
Seeing an issue on a tenant. When using the custom theme generator and applying via powershell I am unable to change the look and see the newly created theme however if I run the get-spotheme they are being listed??

Any Idea why they cannot be selected from 

PS C:\WINDOWS\system32> get-spotheme

Name           Palette
----           -------
Contoso Portal {[neutralPrimaryAlt, #4b4b4b], [themeLighterAlt, #fff9f5], [black, #1d1d1d], [themeTertiary, #fda667]...
oneagency      {[themeLight, #fcd5b7], [themeTertiary, #f9ac71], [black, #1d1d1d], [neutralSecondary, #858585]...}
Custom Cyan    {[themeLight, #affefe], [themeTertiary, #76ffff], [black, #000000], [neutralSecondary, #666666]...}
Oneagency2     {[themeLight, #fcd5b7], [themeTertiary, #f9ac71], [black, #1d1d1d], [neutralSecondary, #858585]...}
CompanyNew     {[themeLight, #b0b8bb], [themeTertiary, #98a2a4], [black, #0b0b0b], [neutralSecondary, #373737]...}
Customtheme2   {[neutralPrimaryAlt, #656565], [themeLighterAlt, #d6e3f5], [black, #3e3e3e], [themeTertiary, #6495da]...
Customtheme    {[neutralPrimaryAlt, #656565], [themeLighterAlt, #d6e3f5], [black, #3e3e3e], [themeTertiary, #6495da]...
![image](https://user-images.githubusercontent.com/6046855/44688334-03d02380-aaa8-11e8-998b-ab68b5aacc6e.png)
![image](https://user-images.githubusercontent.com/6046855/44688341-10ed1280-aaa8-11e8-8206-762b099e3d39.png)

**Comment by bcameron1231** [comment]
Hi @nicholas-morris ,  it looks like this is unrelated to the PnP Starter Kit. There is a JS error that occurs in every tenant (with or without the Starter Kit). This is likely the culprit for why you are unable to change the look.

**Comment by nicholas-morris** [comment]
Thanks Beau,

Any way I can fix this or link to material explaining the error and resolution?

Regards,
Nick

**Comment by bcameron1231** [comment]
Nope, it appears out of our control. I'd submit a ticket with MSFT and see if they are aware of it. It's happening in multiple tenants for me.
