### ISSUE TITLE
Small customisations in the footer

### ISSUE THREAD

**Issue by ruben1980** [SharePoint/sp-starter-kit#126]
Hi,

First of all, let me tell you that I am verry happy with the SP Starter kit!
I managed to install everything properly and everything is working fine now.

Can someone tell me how I can:

1. I want to put in more links in the footer, how do I set the height of the footer? Can this be done with CSS?

2. I want to change the support link to a hyperlink (right next to the copyright)

thanks in advance!

Ruben

**Comment by bcameron1231** [comment]
1. You can set the height of the footer via CSS. You will have to open up the extension in VS Code and modify the code for the extension. Inside /src/extensions/portalFooter/components/Links/Links.module.scss on line 15, there is CSS code that specifies the height of the footer when it's visible. Currently set to 190px. You'll want to modify this piece.

You'll then rebuild the solution using Gulp, and upload the .sppkg file to your app catalog.

2. You can definitely change the support link. I have a post about customizing the footer, and then updating the site with the new footer. Can be found [here](https://beaucameron.net/2018/07/19/customizing-the-pnp-starter-kit-for-office-365-part-1-portal-footer/)

**Comment by ytterstrom** [comment]
There is also a pull request in https://github.com/SharePoint/sp-starter-kit/pull/118 that autoadjust the footer based on number of links.
