### ISSUE TITLE
MyLinks Unable to Add

### ISSUE THREAD

**Issue by spurr82** [SharePoint/sp-starter-kit#128]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

Able to add links

#### Observed Behavior

No Links added, the add dialog stays open
Get an error in console

_Uncaught TypeError: Cannot read property 'concat' of undefined
    at t._saveEdit (portal-footer-application-customizer_3f174defe3730bc17f2d7c1335df1fc6.js:44)
    at Object.r (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at a (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at Object.s [as executeDispatchesInOrder] (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at f (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at m (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at Array.forEach (<anonymous>)
    at r (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at Object.processEventQueue (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646)
    at r (sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:660)
t._saveEdit @ portal-footer-application-customizer_3f174defe3730bc17f2d7c1335df1fc6.js:44
r @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
a @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
s @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
f @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
m @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
r @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
processEventQueue @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
r @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:660
handleTopLevel @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:660
i @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:660
perform @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
batchedUpdates @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:660
i @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:646
dispatchEvent @ sp-pages-assembly_en-us_d4876ad6641337ff9e7f2daa78ac3b66.js:660_

#### Steps to Reproduce

Click arrows to open footer
Click edit
Click Add
Fill in details
Click Add

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi @spurr82 Can you confirm you have both the PnP-PortalFooter-Links list on the portal as well as the custom property on the user profile?

**Comment by bcameron1231** [comment]
The customizer you are loading right now is the Portal Footer and not the Collab Footer. They are two different extensions.  On the hub site you want PnP-PortalFooter-Links.

Portal Footer lives on the Hub site portal site. On the HR and Marketing site, it uses the Collab Footer.

**Comment by spurr82** [comment]
ahh nice, I'll go add the other, did I skip some doco somewhere?

**Comment by bcameron1231** [comment]
This is documentation you'd be looking at https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/components/ext-portal-footer.md 

Sounds like you aren't deploying using the PowerShell script?

**Comment by spurr82** [comment]
yeah im using PS i went through the 

> Preparing your tenant for the PnP SharePoint Starter Kit

But when it mentions creating the UPS Properties it only mentions one protery , had the second property been mentioned it would have been all G

**Comment by bcameron1231** [comment]
There is only one property on the user profile you need. The list should be deployed with the hub site.

**Comment by spurr82** [comment]
Sorry you confused me, you siad there are 2 Collab, and Portal

in the UPS do i need PnP-CollabFooter-MyLinks or PnP-PortalFooter-Links ???

The lists I have are there, no issues, the adding of the links in HR and marketing site work, no problem

**Comment by bcameron1231** [comment]
Sorry, my apologies for any confusion. There are two footers - "Collab Footer" and "Portal Footer". Each have their own list on the sites they live on. That is, The Portal Footer should have a PnP-PortalFooter-Links list on the site, and the Collab Footer will have a PnP-CollabFooter-Links list on the HR/Marketing sites.

Both extensions use the same User Profile Property "PnP-CollabFooter-MyLinks" to load your personal links. :)

So to confirm, you have that property on your User Profile and you have the respective lists on the sites right?

**Comment by spurr82** [comment]
Ok so this is a little crazy

My Setup: 

UPS
---------
PnP-CollabFooter-MyLinks 

-------

Marketing site - no list called PnP-CollabFooter-MyLinks (not that i can see in sitge contents)
HR site - no list called PnP-CollabFooter-MyLinks (not that i can see in sitge contents)
Poratl Site - Has a list called PnP-PortalFooter-Links 

-------
What i have just done is add another UPS property "PnP-PortalFooter-Links" so i now have 2.... and it now works...

To me it looks the the personal "my links" uses the UPS property to store values, the list on the portal site is to store additional corperate links thats must be there all the time managed by lets say the comms team in an org.

**Comment by bcameron1231** [comment]
Ah I misspoke, my apologies. There isn't a list on the HR/Marketing site...  Just on the portal site.  But that is interesting that you added PnP-PortalFooter-Links to the UPS. The PnP-CollabFooter-MyLinks is the only UPS property required when using the default deployment.

If you look at the deployment template https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/hubsite.xml on line 500, you'll see where it specifies the personalItemsStorageProperty.

**Comment by eoverfield** [comment]
@spurr82 I understand you were able to get this working, outstanding, but the fix does not make sense. A user property "PnP-PortalFooter-Links" should not be needed as that is not found in the code unless you changed something in the provisioning process.

My suggestion is that you now remove the user property, PnP-PortalFooter-Links, and see what happens. Maybe there was a delay in the system accepting PnP-CollabFooter-MyLinks?

The specific error you originally encountered was triggered in \solution\src\common\myLinks\myLinksDialog.tsx, line 249. There was a state, "links" that was not being sent to this particular React component, "this.state.links.concat([]);".

The links are originally retrieved when the extension is being initialized in "PortalFooterApplicationCustomizer.ts" found in \solution\src\extensions\portalFooter.

You will find a method, private async loadLinks(): Promise<ILinkGroup[]> {} that loads the links. What is strange is that in your case either this did not fire, did not return its promise properly, or somehow the results became null.

Assuming that the common list and the particular user property are available, you should be good.

**Comment by spurr82** [comment]
Based on reviewing the code, to remove the property was my next step, the original property I added was done yesterday but there could have been a delay somewhere. I'll try first thing tomorrow and come back to this thread.

**Comment by spurr82** [comment]
I have removed the additional property, all seems to be ok at the moment. Thanks for your time @eoverfield

**Comment by VesaJuvonen** [comment]
Closing this one as seems like solved. Issue most likely was simply on the naming of the user profile property as you cannot have two User Profile properties with the same name - the fact that SharePoint allowed you to create the second one, means that there was a typo on the original one, which is already deleted, so we can't confirm your setup. Thanks anyway @spurr82 for following up on the status and good that you got it to work.
