### ISSUE TITLE
Personal page webparts do not load

### ISSUE THREAD

**Issue by tchagan** [SharePoint/sp-starter-kit#13]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When viewing the Personal.aspx page I expect the web parts for meetings, tasks, personal contacts, personal email, recent sites and recent documents to load successfully and display their associated data.

#### Observed Behavior

The first web part loads, this is usually the meetings web part. The others don't load at all or else timeout with an error.

#### Steps to Reproduce

1. Run the provisioning/deploy.ps1 script
2. Go to the newly (successfully) provisioned site.
3. Click on the Personal link

the web parts should be there with their associated loading messages, the meetings web part will load and none of the rest will.

**Comment by expiscornovus** [comment]
@tchagan I got the same issue. It looks like it only completes the first graph request for a calendar. It looks like the rest has a timeout.

![graphtimeout](https://user-images.githubusercontent.com/22542376/40788312-0732578a-64f0-11e8-9543-1d96a7a622eb.png)

**Comment by tchagan** [comment]
@expiscornovus I've found that if I put on of the personal webparts on another page by itself, it works fine. If I then go to the Personal page the web parts seem to work fine too. I'm presuming that this is an authentication issue when more than one webpart on a page is using MS Graph. I read about this in another thread, there was a workaround but I also read that PnP folks were working on this issue.

**Comment by Worrelpa** [comment]
I believe it is a bug... 
details from Beau Camerons blog points to the following article.

https://github.com/SharePoint/sp-dev-docs/issues/1810

There is a work around but required rebuilding the package. 
However the bug is being worked on.

**Comment by VesaJuvonen** [comment]
This is indeed related to a bug in the underlying AAD auth model, which should be addressed partly in the SPFx v1.5 and fully in upcoming 1.6.
