### ISSUE TITLE
Error Provisioningtemplate

### ISSUE THREAD

**Issue by edgarjpgoncalves** [SharePoint/sp-starter-kit#130]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

>![image](https://user-images.githubusercontent.com/42936759/44988519-d7724680-af82-11e8-928a-dd59bb718b8e.png)

**Comment by eoverfield** [comment]
Have you referenced https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/common-provision-results.md?

Also, is appears as though English, language code 1033, is not your default language. Is that correct? There is a current requirement that English be your default language.

**Comment by edgarjpgoncalves** [comment]
hello

I have already made all the corrections.
Yes, the basic definition of sharepoint was Portuguese, I tried to change
everything to English, but it must be missing something!


Edgar Gonçalves

Telemóvel +351 - 966497274


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
03/09/18,
19:58:10

Eric Overfield <notifications@github.com> escreveu no dia segunda,
3/09/2018 à(s) 19:51:

**Comment by maximreynaud** [comment]
Hello @edgarjpgoncalves did you fix your problem ?

Cheers;
Maxime REYNAUD

**Comment by edgarjpgoncalves** [comment]
hello

I did not make it

Com os melhores cumprimentos,

Edgar Gonçalves

Telemóvel +351 - 966497274


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
26/09/18,
11:54:10

Maxime Reynaud <notifications@github.com> escreveu no dia quarta,
26/09/2018 à(s) 10:43:

**Comment by bcameron1231** [comment]
Hi, I realize this is an older ticket and may not apply to you anymore. We are working on cleaning up the issues list, if this is still a problem, could you re-open an issue in the list.
