### ISSUE TITLE
Tiles webpart does not display properly on iOS

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/sp-starter-kit#132]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
The Tiles webpart should show 3 tiles in each row with max 3 rows in total (3x3) in all mobile devices.

#### Observed Behavior
In iOS devices, the Tiles webpart shows 4 rows with 2 tiles in the first row and 1 tile in the last row (2x3x3x1). 

#### Steps to Reproduce
Add the Tiles webpart to the page and configure to display 9 tiles. Then open the website on an iPhone. We tried it with different versions of iOS and on different tenant environments, and got similar results. The webpart looks good on all Android mobile devices. 

An example of how the tiles webpart looks:
![image](https://user-images.githubusercontent.com/10626435/45008822-4ad59000-b037-11e8-9d07-0c68cfa1dccd.png)

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Thanks! Duplicate issue from #16 and there is a PR fix for this #112

**Comment by VesaJuvonen** [comment]
Actually - closing this as it's duplicate. Let's track this with #16.
