### ISSUE TITLE
The requested operation is part of an experimental function that is not supported in the current environment.

### ISSUE THREAD

**Issue by ruben1980** [SharePoint/sp-starter-kit#135]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Observed Behavior

Since yesterday I noticed in the personal page all webparts show me the error:

'The requested operation is part of an experimental function that is not supported in the current environment.'

as far I can see the affects on the webparts:
- upcoming meetings
- Personal contact
- My Tasks
- Personal e-mail
- Recent documents
- Recent Sites

**Comment by eoverfield** [comment]
SPFx 1.6.0 was released yesterday. you can review the notes here: https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.6-release-notes.
It appears as though they had to roll out a new AAD end point thus permissions will have to be re-granted. Yet at the current time there appears to be a delay in the global roll out. I am seeing similar errors across many tenants.

I expect this to be fixed for everyone soon. @VesaJuvonen is there additional insight you can share at the moment?

**Comment by iainl** [comment]
Any update on this, it is currently impacting many tenants that we support?

**Comment by eoverfield** [comment]
@iainl the issue has been logged over in Microsoft's preferred spot, here as well:
https://github.com/SharePoint/sp-dev-docs/issues/2480

**Comment by bcameron1231** [comment]
Closing - This is no longer an issue since go live of the SPFx 1.6
