### ISSUE TITLE
Top nav not saving changes

### ISSUE THREAD

**Issue by iainl** [SharePoint/sp-starter-kit#139]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

The nav menu at the top of the page should save changes

#### Observed Behavior

When editing the nav menu it does not save any changes

#### Steps to Reproduce

Click edit, make a change, save, refresh the page

![image](https://user-images.githubusercontent.com/38407636/45500728-33a14b80-b777-11e8-977a-cf3b0d3f0597.png)

Is there any specific documentation for this nav menu?

**Comment by eoverfield** [comment]
@iainl the top navigation you are referring to is standard OOTB hub navigation. The edit feature is a part of SharePoint Hub sites and not specific to the starter kit. I have found the edit feature for hub navigation can take a few minutes to stick sometimes, but that is unusual. 

https://support.office.com/en-us/article/customize-the-navigation-on-your-sharepoint-site-3cd61ae7-a9ed-4e1e-bf6d-4655f0bf25ca#hubnav

**Comment by iainl** [comment]
Ahh ok, Thanks. Do you happen to know how to enable this on other modern pages?

**Comment by VesaJuvonen** [comment]
That is a hub site navigation. If you make some site collection as a hub site, it will have this hub navigation for you to edit and modify.

**Comment by eoverfield** [comment]
@iainl the hub navigation (top nav) you are referring to should appear on all content pages within a site that is joined to a hub. You can manually join other sites to a hub and those new sites should inherit the hub navigation.
