### ISSUE TITLE
Tiles webpart not working

### ISSUE THREAD

**Issue by krmoanh** [SharePoint/sp-starter-kit#14]
Hi 
I have  problem with Tiles Webpart its just show ( There is no list connection configured for this web part. ) and when I click edit trying to make the Tiles web part configuration its just blank I cant do anything but the second option Specify the height of the tiles it work no problem with it? is there any idea how it works this Tiles webpart

**Comment by BraunJonathan** [comment]
Same here ;-)
Would be very nice to have specific documentation (at least a  how to use one) for each webart/extension.
This project is a very very good id though with a lot of things to learn from !

**Comment by expiscornovus** [comment]
@krmoanh I just deployed the starter kit. When I take a look at the tiles web part I see it should have deployed a list called PnPTiles at the portal Hub site and made a connection with that list. Can you find that list via site contents menu on your Hub site?

You should be able to add a new tile via that list. Btw, it uses Office UI Fabric icons.

![addnewtilelink](https://user-images.githubusercontent.com/22542376/40775600-c667b58c-64c8-11e8-874e-9850fc36253d.png)

**Comment by BraunJonathan** [comment]
I can find the liste in the portal hub site content.
I added rows to that list but when i add the webpart, it still says to me that no list connection has been configured :(

**Comment by krmoanh** [comment]
uhm ok now I got it. but how about if I would like to use Tiles webpart as separate  project. i mean creating new project name Tiles webpart and test it.

**Comment by VesaJuvonen** [comment]
We did change the implementation of the Tiles web part with the latest release. Now it's no longer dependent on the list in the site as that did cause it not to be that reusable. With the latest version, you can configure the actual tiles directly from the web part properties using the collection editor form PnP reusable SPFx controls. This should make it much easier to reuse the web part.

**Comment by Preethirasu** [comment]
Hi VesaJuvonen,

Please share the updated code

**Comment by eoverfield** [comment]
@Preethirasu  the updates tiles webpart was released a few weeks back as a part of the starter kit. The tiles webpart uses a new PropertyFieldCollectionData control https://github.com/SharePoint/sp-dev-fx-property-controls/blob/master/docs/documentation/docs/controls/PropertyFieldCollectionData.md.

**Comment by Preethirasu** [comment]
Thanks eoverfield for your response.
I just need the tile web part code where UI Fabric Name is a dropdown . Could you please share the code

**Comment by Preethirasu** [comment]
When i tried to separate the code its throwing error as "List not configured". What tenant property has to be added?

When i deployed the whole package ,PnpTile List is not available in the site.

**Comment by eoverfield** [comment]
@Preethirasu The tiles webpart does not use a list nor a tenant property. The tiles webpart stores the link items within its own properties. https://github.com/SharePoint/sp-starter-kit/issues/37#issuecomment-402722552. An older version of the starter kit did use a list I believe, I suggest you download the latest repo.
