### ISSUE TITLE
Portal Footer disappears navigating between links to other hub site collections

### ISSUE THREAD

**Issue by martinpyman** [SharePoint/sp-starter-kit#141]
Hi all,

Noticed a bug in 
https://github.com/SharePoint/sp-starter-kit/blob/master/solution/src/extensions/portalFooter/PortalFooterApplicationCustomizer.ts

When you navigate across sites with the footer deployed, SharePoint downloads the page differently. The _bottomPlaceholder is returned as "isDisposed" - rather than when you refresh on a new page. When you then try and render the ReactDom it fails as _bottomPlaceholder is in a disposed state.
This now checks for isDisposed in the bottomPlaceholder

Line 204. 
`if (!PortalFooterApplicationCustomizer._bottomPlaceholder) {`
is now:
`if (!PortalFooterApplicationCustomizer._bottomPlaceholder || PortalFooterApplicationCustomizer._bottomPlaceholder.isDisposed) {`

I made a change suggestion on the code, but not sure that was the right thing to do!

Martin

**Comment by martinpyman** [comment]
Any update on this? Seems like such a simple fix to include?

**Comment by bcameron1231** [comment]
Closing, Fixed by PR #282
