### ISSUE TITLE
PortalFooter not displaying in the hub site

### ISSUE THREAD

**Issue by gayathrak** [SharePoint/sp-starter-kit#144]
#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

I'm trying to deploy only the PortalFooter extension to my dev tenant without using the starter kit (not retrieving from the starter kit). 
I have created a new extension called PortalFooter and copy the PortalFooter code from the starter kit and added the required folders only for the PortalFooter. After i did npm install and gulp serve to check from my workbench, could not see the footer appearing in the hub site. No errors. Already have the list called "PnP-PortalFooter-Links"
What should i need to change or add (files) in order to get this extension deployed as a separate extension (without using starter kit) to my dev tenant?

Thanks

**Comment by bcameron1231** [comment]
Can you clarify your testing process? If you are just gulp/serving... are you testing the footer using `?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"<extensionId>":{"location":"<extensionType>","properties":<propertiesJSON>}} `

**Comment by bcameron1231** [comment]
Can you clarify how you are trying to test this extension? Extension do not load in the workbench, did you configure the serve.json file support your testing?

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages

**Comment by gayathrak** [comment]
Thanks..  
I have configured the serve.json to have below now

{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "serveConfigurations": {
    "default": {
      "pageUrl": "https://gdmdev.sharepoint.com/sites/TemplateSite2/SitePages/Test2.aspx",
      "customActions": {
        "80f37756-0fbc-434d-9835-55401b47e5bb": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {}
        }
      }
    },
    "portalFooter": {
      "pageUrl": "https://gdmdev.sharepoint.com/sites/TemplateSite2/SitePages/Test2.aspx",
      "customActions": {
        "80f37756-0fbc-434d-9835-55401b47e5bb": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {}
        }
      }
    }
  }
}

i did gulp serve --config=portalFooter

Page loads up but cannot footer did not load. 

What will be the best process to get only one extension from starter kit and deploy that particular extension to my dev tenant?

Thanks

**Comment by bcameron1231** [comment]
Generally, I create a new solution and mover the files that I want for the PortalFooter. If I can find some time, I may be able to do that for you.

When the page loaded, did the "allow debug scripts" show up?

**Comment by gayathrak** [comment]
Yes, it showed up and after selecting "Load debug scripts" i get the page alright but cannot see the portal footer. I have already got PnPPortalFooterLinks list with 1 item in it.

Thanks Beau..

**Comment by bcameron1231** [comment]
If you open up Dev Tools in your browser (F12) are you noticing an errors? Maybe unable to load manifest, or another javascript error?

**Comment by gayathrak** [comment]
Thanks @bcameron1231.. Very helpful

I have attached the error messages. Below is my debug url with properties 

debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js&loadSPFX=true&customActions=%7B"a935ac7b-8b7d-4e17-bef0-357126b93843"%3A%7B"location"%3A"ClientSideExtension.ApplicationCustomizer"%2C"properties"%3A%7B"linksListTitle"%3A"PnP-PortalFooter-Links"%2C"copyright"%3A"%40GDM"%2C"support"%3A"support"%2C"personalItemsStorageProperty"%3A"PnP-CollabFooter-MyLinks"%7D%7D%7D

In the starter kit there is a hubsite.xml under provisioning. Do the properties in the above url is sufficient to load the PortalFooter? 

![error2](https://user-images.githubusercontent.com/41831812/45917905-0fa1e080-bec2-11e8-8d66-584509c5bc8f.jpg)
![error1](https://user-images.githubusercontent.com/41831812/45917906-0fa1e080-bec2-11e8-9440-396f9ac93fea.jpg)

**Comment by bcameron1231** [comment]
Hi @gayathrak  Glad to hear you got it working!! The portal footer is *per* hub site.  I've been working on a solution which is a mix of the Collab Footer + the Portal Footer... so that we can have the display of the Portal Footer, but use the Term Store for managing the content of the footer, across all sites in the tenant.

**Comment by gayathrak** [comment]
Thanks @bcameron1231  that will be helpful for lot of users..
