### ISSUE TITLE
Tiles and Footer not deployed

### ISSUE THREAD

**Issue by NagJoshi** [SharePoint/sp-starter-kit#156]
Category
[ X]   Question
       Bug
      Enhancement

Hi, 
I have deployed the starter after thoroughly reading the instructions. Tried to deploy the solutions in different tenants but still no luck. The solution is getting deployed and both hub site and the team sites are getting created successfully but can't see some of the components. Can't see the Tiles and the Footer Links.  I have added the user profile property as described in the document. I can see the pnp portal footer links list the hub site but can't see the Tiles webpart on the hum home page. Also no footer.

I have uploaded the sppkg file to the app catalog  but it didn't ask me to trust the solution etc. Tenant Deployed metadata columns is showing as No. Also when I visited the API management page I can't see any items there to approve the requested api permissions. 

Kindly suggest whether I am doing anything wrong. Images attached which shows App uploaded but not deployed, no Tiles webpart,no footer webpart.

![image](https://user-images.githubusercontent.com/41113456/45951630-1af92700-bffc-11e8-93c2-ee84f4328211.png)
![image](https://user-images.githubusercontent.com/41113456/45951639-2b110680-bffc-11e8-98ae-f27aec81256a.png)

![image](https://user-images.githubusercontent.com/41113456/45951711-7fb48180-bffc-11e8-9536-df63adb192b3.png)

**Comment by simonagren** [comment]
@NagJoshi This is related to #157 and #158 aswell. 
Gonna add an answer in #158!

**Comment by NagJoshi** [comment]
Footer and Tiles Web part works fine with the Dev branch source. Thanks Simon.
