### ISSUE TITLE
API management page empty

### ISSUE THREAD

**Issue by NagJoshi** [SharePoint/sp-starter-kit#157]
#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
"After deploying the .sppkg package to the tenant app catalog, approve the requested API permissions. " ...from the installation guide for SharePoint starter kit

API Management page should show some entries about Microsoft Graph after deploying the SharePoint Starter Kit solution. I have added the sppkg file to the app catalog. When I opened the API Management page from the SharePoint admin centre it is not showing nay entries, just blank.

#### Observed Behavior
There should be some entries in the API management page where I can approve the APIs.

#### Steps to Reproduce
Following the SharePoint starter kit guidelines

Screenshots:
![image](https://user-images.githubusercontent.com/41113456/45961533-9ff13a00-c016-11e8-98ea-b00a172dd4f2.png)

**Comment by thomasberman** [comment]
I'm experiencing the same thing as well. I've tried on two completely isolated tenants using a tenant admin account on each. 

Occasionally (when refreshing a few times), I'm getting this message:

![image](https://user-images.githubusercontent.com/3643224/45962135-104c8b00-c018-11e8-9b38-02c4872d6a19.png)

**Comment by simonagren** [comment]
@NagJoshi @thomasberman  This is related to #157 and #158 aswell.
Gonna add an answer in #158!

**Comment by eoverfield** [comment]
Your issue here may be related to the update to SPFx 1.6 on the backend. You might want to review the following thread and see if the suggestion below helps.

https://github.com/SharePoint/sp-dev-docs/issues/2472

https://github.com/SharePoint/sp-dev-docs/issues/2472#issuecomment-419213781

**Comment by simonagren** [comment]
@eoverfield Thanks for providing that!
it could be because of that, but as in his other issues I assume that he hasn't been able to deploy the solution.  If you look in #156 he hasn't deployed it.
And all of these errors occur then.

**Comment by NagJoshi** [comment]
I can see the entries in the API page after deploying the package file with Dev source, not master branch source. Thanks Simon and Eric.
