### ISSUE TITLE
SharePoint Starter Kit deployment "Resource Not Found Error"

### ISSUE THREAD

**Issue by NagJoshi** [SharePoint/sp-starter-kit#158]
#### Category
- [ X] Question
- [X ] Bug
- [ ] Enhancement

I am trying to deploy the SharePoint starter kit. All the prerequisites are met. But getting errors "ResoourceNotFoundException" during "Provisioning solution" stage in the deployment script".

#### Expected or Desired Behavior
After the deployment all the client side webparts should be available on the page. There should not be any errors while running the deploy.ps1 script.

#### Observed Behavior
Hub site and team sites are provisioned correctly, can access the sites, branding applied but webparts, extensions etc are not deployed. Can't see Tiles, Footer etc in the Hub site. Provisioning solution step throws as an error "ResoourceNotFoundException". Please find the screenshot below:

![image](https://user-images.githubusercontent.com/41113456/45961817-56edb580-c017-11e8-90d7-a5fe60317994.png)

Please help!

**Comment by simonagren** [comment]
Hi @NagJoshi !

First off, have you created an App Catalog? 

If I remember this correctly this has to do with either that, or that your tenant isn't in "first realese".
When your tenant isn't in first realease the "sharepoint-starter-kit.sppkg" get activated with errors. 

Have a look at this documentation:
https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/api-management.md

https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/manual-deploy-sppkg-solution.md

Good luck, let me know how it pans out :)

**Comment by simonagren** [comment]
So there seem to be something not 100% right with the `sharepoint-starter-kit.sppkg` currently available in the master branch of the repository.
I have a fork of this repository, and I did this in a few steps:

1.  Made sure my repository was up to date. You could either pull from upstream, or just clone this respository.

2. run `npm install`

2.  In visual studio code I ran these commands one by one:

```
-gulp -f "gulpfile.js" clean
- gulp -f "gulpfile.js" build
- gulp -f "gulpfile.js" bundle --ship
- gulp -f "gulpfile.js" package-solution --ship
```
![image](https://user-images.githubusercontent.com/16558321/46013649-38e28c80-c0cd-11e8-9711-5628d754d5fc.png)

3. Now I uploaded the new `sharepoint-starter-kit.sppkg` from "/solution/sharepoint/solution/sharepoint-starter-kit.sppkg"

4. 
![image](https://user-images.githubusercontent.com/16558321/46013816-a098d780-c0cd-11e8-9a0b-e1ba15a31440.png)

5. 
![image](https://user-images.githubusercontent.com/16558321/46013933-ed7cae00-c0cd-11e8-8abf-3aa0ed046dee.png)

**Comment by simonagren** [comment]
> We had a package built from an earlier starter kit download (downloaded in July) and it had the following snippet in the package-solution.json:
> 
> ```
>   "$schema": "https://dev.office.com/json-schemas/spfx-build/package-solution.schema.json",
> ```
> We have been successfully deploying this package to various test tenants, but this morning we were deploying this package to a test tenant and came across the same error, we updated the schema to:
> 
> ```
>  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
> ```
> And it worked from then on.
> 
> Not sure if this is in release notes somewhere (not had a chance to check yet).
> 
> If you check your tenant app catalog site you'll "probably" see the package has been uploaded but it's in a broken state (some of the columns are not populated).

@colinrippeyfinarne you could be onto something.
At least in the dev branch this is already changed, as you can see in the image below.

![image](https://user-images.githubusercontent.com/16558321/46014410-6defde80-c0cf-11e8-9d86-765110eb9089.png)

**Comment by thomasberman** [comment]
@simonagren @colinrippeyfinarne 

It looks like there's more to it than just the schema in package-solution.json. I updated that in Master then packaged it and I got exactly the same behavior as the original issue. When I packaged Dev like Simon recommended, it worked just fine.

Maybe @VesaJuvonen can have a look at this and update Master.

**Comment by eoverfield** [comment]
Hi All, I can provide some context circa late Sept 2018. @erwinvanhunen and @waldekmastykarz in particular have been making updates to the dev branch to update the SPFx solution to v1.6 as well as add a new hierarchy provisioning component which was announced on a PnP Community call and I believe you can review here: https://youtu.be/Jjm52Pgxhjs?t=22m12s.

The dev branch has quite a few new changes, I would not suggest for your more production tenants, or rather use with caution as more is expected to change. I have not heard a timeline when the dev branch will be merged with the master branch.

Unfortunately I have not seen the issue you are reporting here. You could try taking the master branch and updating only the package-solution.json and rebuilding the SPFx solution.

**Comment by NagJoshi** [comment]
Hi Simon,

Thanks a lot for your reply, much appreciated. As suggested, I have tested with the Dev branch code package. Package file deployed fine, API page empty issue is resolved, approved Microsoft Graph. Web Parts, Extensions etc deployed fine and Resource Not Found error disappeared from the deploy script but this time it created some other error messages in the Apply Template step which worked fine with the Master branch code. Because of this error the template didn't get applied. It seems there are some issues with both the current Dev and Master branch code though the errors are different. Thanks once again!

**Comment by NagJoshi** [comment]
Hi Eric, Thank you very much for the update.

**Comment by eoverfield** [comment]
I posted a related update: https://github.com/SharePoint/sp-starter-kit/issues/168#issuecomment-427535039
