### ISSUE TITLE
How To Deploy With Two Factor Authentication? 

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/sp-starter-kit#161]
Any guidance on how to deploy with multi factor authentication enabled? Will it be enough if the device login is set once in the beginning before calling deploy.ps1?

**Comment by VesaJuvonen** [comment]
You can use Connect-PnPOnline with UseWebLogin switch, which will then prompt you for MFA authentication. See more details from the official cmdlet documentation - https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps,

**Comment by quo10** [comment]
Using the new approach I get following error using MFA: Apply-PnPProvisioningHierarchy : The remote server returned an error: (403) Forbidden.

**Comment by eoverfield** [comment]
@quo10 I believe the issue you are witnessing is being addressed in the following issue: https://github.com/SharePoint/sp-starter-kit/issues/179

**Comment by VesaJuvonen** [comment]
@quo10 - can you execute following right after your exception and the submit a new issue. This would then confirm if the issue is same as with #179... Get-PnPException. This cmdlet will report the exception details where the 403 happened, which should be included in the issue details. Thx.
