### ISSUE TITLE
New meeting button in upcoming meetings web part

### ISSUE THREAD

**Issue by Laskewitz** [SharePoint/sp-starter-kit#163]
I would love to see a new meeting button on top of the upcoming meeting web part which will open a new window with a new meeting dialog.

#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

**Comment by VesaJuvonen** [comment]
Merged to dev and will be out in master together with the upcoming Starter Kit release (after PnP Oct PowerShell is out).
