### ISSUE TITLE
Tenant API management approval error

### ISSUE THREAD

**Issue by gdavisMDA** [SharePoint/sp-starter-kit#167]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Attempting to approve the Graph API's setting up the sp-starter-kit

#### Observed Behavior

When I click approve, I get this error for each item.

[HTTP]:500 -  [CorrelationId]:1cea929e-f09c-6000-17ab-233305890ef7 [Version]:16.0.0.8112 - Insufficient privileges to complete the operation.

I am the global admin. Is there a permission I am not aware of?

#### Steps to Reproduce

uploaded the starter-kit.sppkg file. Then navigated to approve the apps. Error on clicking approve

>

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
It is possible this is related to recent updates to SPFx 1.6. I suggest you review the following suggestion and see if that helps.

https://github.com/SharePoint/sp-dev-docs/issues/2472#issuecomment-419213781

**Comment by gdavisMDA** [comment]
Thanks!
