### ISSUE TITLE
Issue with Default Language other than English (the only one so far)

### ISSUE THREAD

**Issue by MelAtWork** [SharePoint/sp-starter-kit#17]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior

The desired behaviour would be a one-click-no-sorrow-solution for everyone :-)

As Modern Sites are inheriting the default language from the root site collection when they are created, the default document library in a german tenant for example has a path called "Freigegebene Dokumente" instead. 
In the file portal.xml several Urls are hardcoded to "Shared Documents" (e.g. Upload of .pptx File).

#### Observed Behavior

When the pptx should be uploaded, the "Shared Documents" Library can't be found. This leads to this exception message:
"Access denied. You do not have permission to perform this action or access this resource."

Also because of this, the webpart that shows the pptx in the portals home page will be broken.

#### Steps to Reproduce

Try with a tenant with another Default language, e.g. German.

#### My personal Quick-Fix Solution
Search and replace "Shared Documents" with e.g. "Feigegebene Dokumente" (or the name of the default doclib in your language).

#### My personal "Aha-Moments"
Although this might not be the right scope, I want to quickly share some hints, that took me a little time to figure out. Might save some time to someone, I hope this is ok for the community:
1. Make sure you have this "First Release to Everybody" Setting in your tenant (see issue #6 )
2. On my machine all files were automatically blocked (Win 10). With the PowerShell Command 
`Get-ChildItem [your path to folder]\sp-starter-kit-master -recurse | Unblock-File`
you can unblock all files at once
3. When you deploy the app-package manually, there is no need for building it with the code. To skip this step, you can either change the deploy.ps1 or simply create a folder "solution" in the existing folder "/solution/sharepoint" and paste the "sharepoint-portal-Showcase.sppkg" from the folder "package" into it

After this, everything worked perfectly fine for me with the latest version. Thanks, guys!

**Comment by AlexTihme** [comment]
Great insights! Thank you!

**Comment by andreasblueher** [comment]
@erwinvanhunen I just found [this blog post](https://www.erwinmcm.com/multilingual-provisioning-templates-with-the-office-365-developer-patterns-and-practices-provisioning-engine/) and I was wondering if this feature could be used here to support multiple languages for the sp-starter-kit? Or is there an easier way to have different urls for the library for different languages?

**Comment by andreasblueher** [comment]
Why did you close this? In my opinion nothing is fixed as long the PR is not merged or do you disagree?

**Comment by MelAtWork** [comment]
@andreasblueher I considered this as "addressed" and wanted to clean up for other "open issues" that need more help than this, as the solution will just be a matter of time (hopefully)

**Comment by andreasblueher** [comment]
Got it, since there has been no word if the PR will be merged or if Erwin doesn't like the approach I though it to be a little bit early. Let's hope things get moving soon :)
