### ISSUE TITLE
Tiles web part for modern pages

### ISSUE THREAD

**Issue by computepros** [SharePoint/sp-starter-kit#172]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Without deploying the entire starter kit, is it possible to extract and deploy just the tiles web part for use on other sites? Or does anyone know of a similar solution for modern pages?

**Comment by eoverfield** [comment]
@computepros I know that @bcameron1231 has been working on splitting aspects of the kit solution up into individual parts. You can definitely do this yourself as well by creating your own SPFx solution from scratch then migrating over the specific webpart code.

**Comment by bcameron1231** [comment]
You can find an isolated tiles solution in my repo here. https://github.com/bcameron1231/SP-StarterKit-IsolatedTiles
 
Hope this helps.
