### ISSUE TITLE
Move SPFx webparts into sp-dev-fx-webparts

### ISSUE THREAD

**Issue by alirobe** [SharePoint/sp-starter-kit#173]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior

I should be able to use a single webpart (e.g. Stock Information) from this starter kit, via the PnP webparts. Also, the starter kit should allow me to easily package whichever sp-dev-fx-webparts I like into my customized starter kit.

#### Observed Behavior

Starter kit has webparts that are unnecessarily distinct from PnP.

#### What I'd like to happen

Publish an NPM package containing the sp-dev-fx-webparts repository.

Move most of the webparts out of this repository, and into that repository.

Leave one or two webparts in this repository.

*OR*

Import sp-dev-fx-webparts as a git submodule.

**Comment by bcameron1231** [comment]
I am going to close this ticket. We are actively working on breaking out the web parts into their own solutions so they can be used individually.
