### ISSUE TITLE
Is Contributing.md correct? It says to make pull requests against Master only.

### ISSUE THREAD

**Issue by thomasberman** [SharePoint/sp-starter-kit#174]
#### Category
- [x] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

The contributing.md document seems like it might be copied from the sp-dev-docs repo. It says that in order to contribute you should fork this repo and make changes in master, then make pull requests against master. I assume this isn't what you want. It should probably say "dev" instead. Just want to check that this is actually the case.

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
@thomasberman Vesa just addressed this as well. https://github.com/SharePoint/sp-starter-kit/pull/170#issuecomment-427809517. We are to be making PR's to the dev branch.

**Comment by thomasberman** [comment]
Ah gothca. Thanks
