### ISSUE TITLE
Error in the SPPKG file in the App Catalog

### ISSUE THREAD

**Issue by esjimenezp** [SharePoint/sp-starter-kit#18]
Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When upload the SPPKG file to the App Catalog it shows me the following "**Error in the application**"

#### Observed Behavior

It not show the options to deploy on the App Catalog it's only upload and immediately show the error mentioned above.  

#### Steps to Reproduce

Download from this link [https://github.com/SharePoint/sp-starter-kit/tree/master/package](url) after that it only upload from the App Catalog

Thanks for your contribution! Sharing is caring.

**Comment by jstrugnell** [comment]
I think the solution for this (currently) is to ensure the tenant is in First Release mode. Then you will be able to see API Management in the new SharePoint Admin area. Once you can see that try re-uploading the app package.

**Comment by pcfilicetti** [comment]
I put my tenant into First Release mode for everyone as well as First Release for selected users and attempted a re-upload with both settings, and the bug still persists... I am still getting the "Error in the application." message, preventing the deployment. Is this a human error on my part, or did this not work for others?
Thanks, and have a nice day.

**Comment by jstrugnell** [comment]
Can you see the API Management area in the new SharePoint Admin portal?

https://{yourdomain}-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement

**Comment by esjimenezp** [comment]
Yes, I can see it

**Comment by jstrugnell** [comment]
Have you tried deleting and re-uploading the App now? If still not working, have you been able to build the package yourself? I've only uploaded the self-built version, not the downloadable version?

**Comment by westerdaled** [comment]
I get the same issue in a newly created dev tenant. Again, I have just the supplied SPPKG. I followed the advice from @pcfilicetti and added my admin account to first release. Deleted and uploaded the SPPKG same issue.
Incidentally,  I cannot see the API Management - Maybe the new SharePoint Admin Centre hasn't been rolled to my dev tenant.   


API management
Control the third-party APIs that can be called by apps and custom script.


[HTTP]:500 -  [CorrelationId]:2981709e-506d-0000-1d28-001386853eb0 [Version]:16.0.0.7730 - The requested operation is part of an experimental feature that is not supported in the current environment.

[HTTP]:500 -  [CorrelationId]:2981709e-8063-0000-0801-8642f60263c5 [Version]:16.0.0.7730 - The requested operation is part of an experimental feature that is not supported in the current environment.

**Comment by esjimenezp** [comment]
Ok, just let me build the package and I comment later, thanks for your help, best regards.

**Comment by westerdaled** [comment]
I  uploaded the supplied package this morning without any errors. In my case,  I just needed  First Release mode for the whole tenant to be applied and the API Management to [verified](https://{yourdomain}-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement) . Then the package uploaded without any errors.

**Comment by SPDan** [comment]
The steps described by @westerdaled are working. I also have to logout and re-login seeing the First Release features.

**Comment by esjimenezp** [comment]
It works, thank you for all support
