### ISSUE TITLE
Tiles Web Part not opening to correct site

### ISSUE THREAD

**Issue by Holden15** [SharePoint/sp-starter-kit#184]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

We deployed the Starter Kit on our dev tenant.  I added the Tiles web part to a page and configured it to open a new google.com page:

![image](https://user-images.githubusercontent.com/43765678/46964638-38a33480-d06e-11e8-94f9-b13bbd0135de.png)

When the tile is clicked on, it is opening to

`https://companyDev.sharepoint.com/sites/.../SitePages/www.google.com
`

I did not change the source code.

**Comment by eoverfield** [comment]
please add "http://" before "www.google.com" and see if that works for you.

**Comment by Holden15** [comment]
That fixed it.  Thank you!  

I might go in to the code and change that to include it by default, most people are not going to type that in.
