### ISSUE TITLE
Apply-PnPProvisioningHierarchy -Path starterkit.pnp -Parameters @{"SiteUrlPrefix"="demo"}

### ISSUE THREAD

**Issue by ryball** [SharePoint/sp-starter-kit#185]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Apply-PnPProvisioningHierarchy -Path starterkit.pnp -Parameters @{"SiteUrlPrefix"="demo"}
Expected to run and deploy some demo sites. 

#### Observed Behavior

Alle sites are created, spfx package uploaded, Api Managment (All Approved) 
Looks like its getting error when deploying the design templates.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Apply-PnPProvisioningHierarchy : Can't find file.
At line:1 char:1
+ Apply-PnPProvisioningHierarchy -Path starterkit.pnp -Parameters @{"Si ...
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningHierarchy], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningHierarchy
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#### Steps to Reproduce

Tried on different tennants same result.
When using the design templates after i run it, i get error when when "Getting a few things ready" is running:

When using : "Contoso Electronics Communication Site"

Add to hub site
One or more of the properties on this action has an invalid type.

**Comment by bcameron1231** [comment]
Hi, I realize this is an old ticket, but we are trying to clean up some of the issues list. As this ticket is roughly 1.5 years old, I understand if it's no longer an issue for you. If it please, could you please open a new issue in the issues list? Thanks!
