### ISSUE TITLE
"User Information List" does not exist at url....

### ISSUE THREAD

**Issue by RajputDeepak** [SharePoint/sp-starter-kit#186]
#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Site Collection of type "TeamSiteNoGroup" in Language="1044" should be created.
The command used is "Apply-PnPProvisioningHierarchy" 

#### Observed Behavior
Error "User Information List does not exist at url https://tenantname/sharepoint.com/sites/teamsitenogroup"

#### Steps to Reproduce

In provisioning xml file,specifiy a site collection of type "TeamSiteNoGroup" and put language attribute as "1044" (Any value apart from english)

Generate a .pnp file and execute it using Apply-PnPProvisioningHierarchy

**Comment by Willemstijn** [comment]
I have had the same problem in Duch (Nederlands). Here the message is:

"**Apply-PnPTenantTemplate : De lijst Lijst met gebruikersgegevens bestaat niet op de site met de URL**"

Like Schoier said, I had to remove my native language (dutch) from the sites that were already created and then rerun the script (Site settings > Site Administration > Language settings > uncheck Dutch > Save)
After that, the script executed succesfully.
![2018-11-16 16_00_59-taalinstellingen](https://user-images.githubusercontent.com/21262346/48629613-60155600-e9ba-11e8-9ac7-52b1c32c333c.png)

**Comment by mmsharepoint** [comment]
Can confirm that behavior even with non-english sites and Groups:
A customer environment is "German" and removing the alternative language "English" (default of the provisioning account) _circumvents_ the problem.
It occurs on a modern Teamsite belonging to a Group but NOT to modern communication sites
Here the error is:
Apply-PnPProvisioningTemplate : List 'User Information List' does not exist at site with URL 'https://tenanturl.sharepoint.com/...'

**Comment by wpo365** [comment]
Same for me: Created two communication sites, both with Lcid set to German 1031. Created a template with Get-PnPProvisioningTemplate from the first site and then applied it to the latter. Got the same error **List 'User Information List' does not exist at site with URL**. Only after I disabled all alternate languages in the latter site and reapplied the template the error would go away.

**Comment by mmsharepoint** [comment]
This seems to be a PnP core issue:
https://github.com/SharePoint/PnP-Sites-Core/issues/1948 
I can confirm that if the executing user has a different language than site default and this language is available as alternative in the site the error occurs (in my case on a customer environment the default langauage was German [don't ask who and why ;-) ] and my user had English as preferred language and I also faced that error. No relation to the PnP-Starter-Kit, just standard PnP Provisioning ...

**Comment by wpo365** [comment]
Thanks @mmsharepoint for the pointer - I overlooked the fact that I was in the sp-starter-kit as my issue is basically not related to the starter kit. But I agree that it's in fact the same issue.

**Comment by bcameron1231** [comment]
Hi, I am working through some of the issues in the issues list. Sounds like this issue is more related to  PnP Core than it is the Starter Kit?

I'd be happy to close to this stick if possible, or if I don't hear from you.
