### ISSUE TITLE
Portal footer is stuck in the middle of the page on a mobile

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/sp-starter-kit#190]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
The footer is always at the bottom of the page

#### Observed Behavior
On a mobile, the footer is stuck in the middle of the page when user starts scrolling the page as soon as it opens for the first time. When the page is refreshed, the footer always stays at the bottom.

<img width="242" alt="footerstuckinthemiddle" src="https://user-images.githubusercontent.com/10626435/47203639-9491f400-d3b3-11e8-8d57-3b694dafcb9b.PNG">

#### Steps to Reproduce
Open the portal page that has other SPFx webparts on it and where the footer is configured. As soon as the page opens, start scrolling down.  The footer gets stuck in the middle of the page and scrolls together with other webparts. Refreshing the page fixes this behaviour.

**Comment by ashishshukla1183** [comment]
@elenanakhmanson Ia m also facing the same issue.
Did you found any way to fix it?

**Comment by elenanakhmanson** [comment]
@ashishshukla1183, we didn't find a solution and just removed the footer. We'll be using the built in footer when it gets released.

**Comment by ashishshukla1183** [comment]
> @ashishshukla1183, we didn't find a solution and just removed the footer. We'll be using the built in footer when it gets released.

Is this suppose to be the issue with this footer only of is the issue with bottom placeholder?
Already I am facing multiple issues with bottom placeholder. 
Another example is the below issue:
https://github.com/SharePoint/sp-dev-docs/issues/2799 
We have the footer deployed in production and this certainly is not helping the cause of pushing modern sites.
