### ISSUE TITLE
Portal Footer is not working in IE 11

### ISSUE THREAD

**Issue by ashishshukla1183** [SharePoint/sp-starter-kit#192]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Portal Footer should work in IE 11. 

#### Observed Behavior

Portal Footer is not rendering in IE 11. It works fine on Edge and other standard browsers.

**Comment by mag210** [comment]
I wonder if this is a case of needing to polyfill the solution for IE 11. I had to do something similar for a 1.6 webpart which made use of the newer @pnp libraries. I added the above to my TS file to resolve:
//Polyfills to fix IE11 compatibility issues
import "core-js/es6/array";
import "es6-map/implement";
import "core-js/modules/es6.array.find";

**Comment by ashishshukla1183** [comment]
I changed sp/pnp version from 1.0.4-4 to 1.0.3 and now it is working on IE11. Since our organization may be moving away from IE 11 in near future, I thought this would be a better approach than  including polyfills.
