### ISSUE TITLE
Timezone in Upcoming Meetings web part

### ISSUE THREAD

**Issue by gdavisMDA** [SharePoint/sp-starter-kit#194]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I have the Upcoming Meetings web part. I would expect meetings to display in my timezone.

#### Observed Behavior

I am in central US time zone and meetings are displaying +5 hrs from central.

#### Steps to Reproduce

No steps needed.

Is there a setting somewhere that I missed? Is this a bug?

**Comment by gdavisMDA** [comment]
This could be a duplicate of issue #166

**Comment by bcameron1231** [comment]
Closing. Duplicate of #166
