### ISSUE TITLE
Unable to set up the SharePoint starter kit -Errors | Contoso portal is not created

### ISSUE THREAD

**Issue by Marianniranjan** [SharePoint/sp-starter-kit#195]
Issue : Unable to set up the Starter kit. My goal to create a Contoso portal with tiles and footer with predefined templates as shown in the tutorial. Please check the erorrs on the screenshot listed below.

Note: 

I did not record in the screenshots with the steps involving the changes made in the portal such as organization - release preference etc It is already done.

**Screenshot**

![image](https://user-images.githubusercontent.com/44459820/47483263-7a925e80-d856-11e8-9313-89d3c97b9955.png)

**Steps followed** 

1 Add used tenant administrator account as Term Store Administrator in the Taxonomy Term Store - Done
2 Created  tenant app catalog - Done
3 Installed Node js version 12 
4 installed the SPO PNP shell module with  Install-Module SharePointPnPPowerShellOnline -SkipPublisherCheck -AllowClobber

Connected to SPO
Connect-SPOService -Url "https://famouscomp-admin.sharePoint.com"  –Credential me@famouscomp.onmicrosoft.com

5 connect to PNP shell using the below command 
Connect-PnPOnline -Url  "https://famouscomp-admin.sharePoint.com"  –Credential me@famouscomp.onmicrosoft.com

6 changed the powershell to the provisioning folder on the package.
7 Made sure the latest pnp powershell is installed.
8 Accessed Term store - Try the preview - App management under advanced - approved the graph
9 Applied the following command
this 
Apply-PnPProvisioningHierarchy -Path starterkit.pnp -Parameters @{"SiteUrlPrefix"="trial"}
OR 
./deploy.ps1 -TenantUrl https://famouscomp-admin.sharePoint.com -SitePrefix trial

> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Bug
- [ ] Enhancement

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue on generic SharePoint topic or dev documentation, please use the (sp-dev-docs Issue list)[http://aka.ms/spdev-issues]
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Looks like you are working on an old version of the starter kit. Check out the new release for the starter kit, it simplifies some of the deployment process (there is no deply.ps1 anymore).

**Comment by bcameron1231** [comment]
hi, I am working on some of the older issues in the issues list. I understand this is an old issue and may not be relevant anymore. Can you confirm if this ticket can be closed?
