### ISSUE TITLE
Apply-PnPProvisioningHierarchy : Access denied. You do not have permission to perform this action or access this resource.

### ISSUE THREAD

**Issue by KaushalKhamar** [SharePoint/sp-starter-kit#196]
**Issue: Getting Access Denied while running "Apply-PnPProvisioningHierarchy" command.**

**Error Message: Apply-PnPProvisioningHierarchy : Access denied. You do not have permission to perform this action or access this**

![capture3](https://user-images.githubusercontent.com/7072474/47700991-624b8680-dc3e-11e8-9945-fdc53181b428.PNG)

Step followed:
1. Import-Module "C:\Kaushal\Stuff Data\spfx\Starter Kit\PowerShellGet-development\src\PowerShellGet\PowerShellGet"
2. Install-Module SharePointPnPPowerShellOnline
3. Connect-PnPOnline https://tenent.sharepoint.com/
4. cd "C:\Kaushal\Stuff Data\spfx\Starter Kit\sp-starter-kit-master\provisioning\"
5. Apply-PnPProvisioningHierarchy -Path .\starterkit.pnp -Parameters @{"Company"="CompanyName";"SiteUrlPrefix"="Company";"WeatherCity"="City"}

**Comment by erwinvanhunen** [comment]
Hi!

The moment this error occurs, can you execute:

```powershell
Get-PnPException
```

and include output here?

**Comment by umaknow-francis** [comment]
Same error here. Output is:
Message          : Accès refusé. Vous n’êtes pas autorisé à effectuer cette action ou à accéder à cette ressource.
Stacktrace       :    à Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      à Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      à Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__4.MoveNext()
                   --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a
                   été levée ---
                      à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      à Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                   --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a
                   été levée ---
                      à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      à Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                   --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a
                   été levée ---
                      à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      à Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                   --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a
                   été levée ---
                      à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      à Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                   --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a
                   été levée ---
                      à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      à Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext
                   clientContext, Int32 retryCount, Int32 delay, String userAgent)
                      à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenDefinitions.SiteCollectionTermGrou
                   pNameToken.GetReplaceValue()
                      à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TermGroupHelper.ProcessGroup(
                   ClientContext context, TaxonomySession session, TermStore termStore, TermGroup modelTermGroup,
                   TermGroup siteCollectionTermGroup, TokenParser parser, PnPMonitoredScope scope)
                      à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceTermGroups.Provi
                   sionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser parser,
                   ProvisioningTemplateApplyingInformation applyingInformation)
                      à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvision
                   ingHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId,
                   ProvisioningTemplateApplyingInformation provisioningInfo)
                      à SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningHierarchy.ExecuteCmdlet()
                      à SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1

**Comment by ArnulfoWing** [comment]
yes, that was it.

thanks... :)

**Comment by neothoms** [comment]
Thank you, I had the same problem.
For a fresh Tenant, nobody is administrator of the term store.

**Comment by bcameron1231** [comment]
Hi, we are working on cleaning up the issues list. I realize this ticket is about 1.5 years old. If this still applies to you, could you please open up a new issue in the issues list? Thanks!
