### ISSUE TITLE
Search webpart on Team sites

### ISSUE THREAD

**Issue by Mandylf** [SharePoint/sp-starter-kit#200]
Hi
I have deployed the PNP starter kit 
I would like to find out is on the Hub site, in the heading area, is the search box, would it be possible to add that to the Team site too?
I have removed the quick launch - and along with that is the search functionality for the site.
I don't want the quick launch displayed but need the search functionality

Thanks for your contribution! Sharing is caring.
![image](https://user-images.githubusercontent.com/44191278/48152054-cca59c00-e2ba-11e8-9156-c5487cdb3bdc.png)

**Comment by bcameron1231** [comment]
Unfortunately this is out of the box functionality when hiding the quick launch. If you want to use the search box, you'll have to enable the quick launch. 

If you wish to suggest a change to how this works, please head over to the  UserVoice https://sharepoint.uservoice.com .

**Comment by Mandylf** [comment]
Okay - thank you - I have added the suggestion to UserVoice
