### ISSUE TITLE
Add Wiki to HubSite

### ISSUE THREAD

**Issue by Mandylf** [SharePoint/sp-starter-kit#201]
.Hi there
Suggestion:
Using the PNP Hubsite, I am not able to add a Wiki App?  I have created a Wiki on another team site, but was wondering if that was deliberate not o be able to add it to the Hub
![image](https://user-images.githubusercontent.com/44191278/48152439-ce239400-e2bb-11e8-988c-6853c4addd0b.png)

**Comment by bcameron1231** [comment]
Hi @Mandylf . Wiki's are classic SharePoint features and are not available in modern SharePoint. It may work on Team sites because they have a "Classic" and a "Modern" view. Communication sites (your hub) doesn't have this, so Wikis are not supported.

**Comment by Mandylf** [comment]
Thanks, I have created a team site and added the Wiki there, then added the URL in the HUB Navigation.
I just wanted to create a Wiki so that it would act as a quick reference guide on how to add an event, or news feed, how to delete a site page etc

**Comment by bcameron1231** [comment]
Hi Mandy. Is there any reason you can't just use a regular SharePoint Site Page for this? Wiki pages have a classic interface, which means when your end users are navigating, they will have an inconsistent UX/UI experience when going from a Modern Hub to your classic wiki page.

Modern Page pages offer essentially the same functionality as Wiki pages.

**Comment by Mandylf** [comment]
Hi Beau
To be honest, I didn’t even think it would work.  Guess the old habits are really hard to get rid of.
I will add a Page, and move all the info over from the old Wiki Page
Thank you for the help, really appreciate it

**Comment by Mandylf** [comment]
Wiki pages are now available
