### ISSUE TITLE
Personal page - Something went wrong

### ISSUE THREAD

**Issue by Mandylf** [SharePoint/sp-starter-kit#202]
Bug
(or probably user error)
I am getting an error message on the Personal page - I tried to approve the API, but also get an error message

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "ac41debd-d92c-4de0-9d67-e7bc191030ee" (pnpPersonalEmail).
Original error: ***Failed to load component dependency "ac41debd-d92c-4de0-9d67-e7bc191030ee" from component "pnpPersonalEmail" (***Failed to load component "4d5eb168-6729-49a8-aec7-0e397f486b6e" (SPClientPreview).
Original error: ***loadComponent() returned an empty object for component "4d5eb168-6729-49a8-aec7-0e397f486b6e" (SPClientPreview).).
Original error: {3}

***INNERERROR:
***Failed to load component dependency "ac41debd-d92c-4de0-9d67-e7bc191030ee" from component "pnpPersonalEmail" (***Failed to load component "4d5eb168-6729-49a8-aec7-0e397f486b6e" (SPClientPreview).
Original error: ***loadComponent() returned an empty object for component "4d5eb168-6729-49a8-aec7-0e397f486b6e" (SPClientPreview).).
Original error: {3}
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-10-26.012/sp-pages-assembly_en-gb_7920a70b7a82916d8fe4ea135527e251.js:838:15996)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-10-26.012/sp-pages-assembly_en-gb_7920a70b7a82916d8fe4ea135527e251.js:1714:22256)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-10-26.012/sp-pages-assembly_en-gb_7920a70b7a82916d8fe4ea135527e251.js:1714:16574)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-10-26.012/sp-pages-assembly_en-gb_7920a70b7a82916d8fe4ea135527e251.js:1714:12605)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-10-26.012/sp-pages-assembly_en-gb_7920a70b7a82916d8fe4ea135527e251.js:1714:71681
![image](https://user-images.githubusercontent.com/44191278/48187130-14b3d580-e332-11e8-9470-101347bd55ab.png)

![image](https://user-images.githubusercontent.com/44191278/48187311-a1f72a00-e332-11e8-95d6-474180848ca6.png)

**Comment by Katli95** [comment]
I'm experiencing the same issue :/

**Comment by bcameron1231** [comment]
The reason you have this error is because the SPFx-LOB-Function service principal doesn't exist in your environment. In order to be able to configure these permissions, applications must be registered inside Azure AD to create these principals first. Once application is deployed and configured, you'll be able to approve these permissions.

Please see this documentation.
https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/components/wp-lob-integration.md

**Comment by gristy58** [comment]
Im seeing the same thing - i have reauthorised all API Requests.

![image](https://user-images.githubusercontent.com/37768717/51796134-190ad300-223d-11e9-98b5-db6ff7a4a1e1.png)
