### ISSUE TITLE
Need to update instructions for AlphaVantage API key

### ISSUE THREAD

**Issue by BobGerman** [SharePoint/sp-starter-kit#203]
#### Category
- [] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When following the instructions to install the AlphaVantage API key, I expected to find a .\deploy.ps1 PowerShell script to pass it to, as explained in the tenant-settings.md documentation file

#### Observed Behavior

The .\deploy.ps1 is no longer part of the solution.
I was able to deploy the API key using this command:

Set-PnPStorageEntity -Key "PnP-Portal-AlphaVantage-API-Key" -Value "<key value>" -Comment "API Key for Alpha Advantage REST Stock service" -Description "API Key for Alpha Advantage REST Stock service"

Is that the best approach? 

#### Steps to Reproduce

Attempt to follow the instructions for adding the AlphaVantage API key and notice that the referenced PowerShell script no longer exists

**Comment by PaoloPia** [comment]
Thanks @BobGerman, I just fixed in the DEV branch the tenant-settings.md file accordingly.

https://github.com/SharePoint/sp-starter-kit/commit/07eb16591422de6a37365c9ea515702dfa19cd19
