### ISSUE TITLE
Portal Footer is not showing at all

### ISSUE THREAD

**Issue by Rajesh-Pradhan** [SharePoint/sp-starter-kit#204]
I've installed the .Sppkg file into my tenant and did the configuration for UserProfiles and Custom List But, there is nothing showing up. Am I missing anything

**Comment by bcameron1231** [comment]
Hi Rajesh, did you add the Footer to your site collection?

**Comment by sramakuri** [comment]
Hi Rajesh , Try to add manually using PNP powershell about this. 

Connect-PnPOnline https://yoursite.sharepoint.com/sites/siteportalname
Remove-PnPCustomAction -Identity "PortalFooter"

Add-PnPCustomAction -Name "PortalFooter" -Title "PortalFooter" -ClientSideComponentId b8eb4ec9-934a-4248-a15f-863d27f94f60 -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentProperties "{""linksListTitle"":""PnP-PortalFooter-Links"",""copyright"":""@Copyright Auritas, 2018"",""support"":""admin@auritas.com"",""personalItemsStorageProperty"":""PnP-CollabFooter-MyLinks""}"
