### ISSUE TITLE
How to activate the extensions?

### ISSUE THREAD

**Issue by diver7** [SharePoint/sp-starter-kit#207]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Are there any instructions on how to activate the extensions in this solution? I mean step by step instructions.

**Comment by bcameron1231** [comment]
If you aren't deploying through the provisioning template, you'll have to do it manually through PowerShell using Add-PnPCustomAction and passing in the information for the Custom Action

https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpcustomaction?view=sharepoint-ps

You can find the name and the component id inside the provisioning XML around line 900 https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/starterkit.xml

I have a couple blog posts that show how to add them at the bottom. 
https://beaucameron.net/2018/07/19/customizing-the-pnp-starter-kit-for-office-365-part-1-portal-footer/

**Comment by diver7** [comment]
> If you aren't deploying through the provisioning template, you'll have to do it manually through PowerShell using Add-PnPCustomAction and passing in the information for the Custom Action
> 
> https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpcustomaction?view=sharepoint-ps
> 
> You can find the name and the component id inside the provisioning XML around line 900 https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/starterkit.xml
> 
> I have a couple blog posts that show how to add them at the bottom.
> https://beaucameron.net/2018/07/19/customizing-the-pnp-starter-kit-for-office-365-part-1-portal-footer/

@bcameron1231 
Thanks for the info on activating this extension but I am still having issues. I installed the starter-kit by dropping the sppkg file into my app catalog. I can see the web parts on my Modern Comm Site. 
1. I navigated to my Comm site and created a List called "Alerts" based on the [specs](https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/components/ext-alert.md)
2. I created one item in that list
3. Using PS I executed the following
4. Connect-PnpOnline -Url https://mytenant.sharePoint.com/sites/CommunicationSiteModern
5. Add-PnPCustomAction -Title AlertNotification -Name AlertNotification -Location ClientSideExtensi
on.ApplicationCustomizer -ClientSideComponentId aa8dd198-e2ee-45c5-b746-821d001bb0e1

PS C:\> Get-PnPCustomAction

Name              Location                                  Scope Id
----              --------                                  ----- --
AlertNotification ClientSideExtension.ApplicationCustomizer Web   0e5d82eb-df83-4201-a4d9-e045db54be48

When I go to the site now I do not see any notifications. What else am I missing?

**Comment by bilalkhan870** [comment]
I installed the starter-kit by dropping the sppkg file into my app catalog. I can see the web parts on my modern comm site. also created the Alerts list with given spec 

When I go to the site now I do not see any notifications. What else am I missing?

![image](https://user-images.githubusercontent.com/39082648/61179380-61168a00-a612-11e9-8c60-0c7a797508a9.png)

@eoverfield @bcameron1231 

Thanks in advance

**Comment by eoverfield** [comment]
When I look to debug these types of problems, my common approach is to open Chrome dev tools and watch the console log and the network tab.

In the console log I am looking for any specific errors that are being thrown that look to be a part of alerts.

The network tab may be more interesting in the beginning. First, is the alert extension JS being loaded? Something tells me it is, though PS should give you that insight into the custom action being added. If you do see the alerts js being downloaded, you can assume it is being at least initialized. At that point, check to see if the alerts list get request is throwing an error or otherwise providing bad data.
