### ISSUE TITLE
Apply-PnPTenantTemplate : File Not Found.

### ISSUE THREAD

**Issue by westerdaled** [SharePoint/sp-starter-kit#213]
#### Category
[x ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

This should work given when I read the tenant provisioning template it normally shows me errors regarding missing reources
 `
Save-PnPTenantTemplate -Template $enwlDemo -Out enlwDemo.pnp
Apply-PnPTenantTemplate -Path enlwDemo.pnp
`>
> 
#### Observed Behavior

> powershell.exe Information: 0 : 2018-12-06 22:44:00.9926        [Tenant Settings]       [18]    [Debug] Code execution scope ended      20397ms 1b9cb464-e273-48d3-bb80-9c8852a086d3
> powershell.exe Information: 0 : 2018-12-06 22:44:00.9936        [Term Groups]   [18]    [Debug] Code execution scope started    0ms     1b9cb464-e273-48d3-bb80-9c8852a086d3
> powershell.exe Information: 0 : 2018-12-06 22:44:04.9302        [Term Groups]   [18]    [Debug] Code execution scope ended      3936ms  1b9cb464-e273-48d3-bb80-9c8852a086d3
> powershell.exe Information: 0 : 2018-12-06 22:44:04.9312        [Provisioning]  [18]    [Debug] Code execution scope started    0ms     1b9cb464-e273-48d3-bb80-9c8852a086d3
> powershell.exe Information: 0 : 2018-12-06 22:44:07.3272        [Provisioning]  [18]    [Debug] Code execution scope ended      2395ms  1b9cb464-e273-48d3-bb80-9c8852a086d3
> powershell.exe Information: 0 : 2018-12-06 22:44:07.3272        [Provisioning]  [18]    [Debug] Code execution scope ended      29603ms 1b9cb464-e273-48d3-bb80-9c8852a086d3
> Apply-PnPTenantTemplate : File Not Found.
> At line:1 char:1
> + Apply-PnPTenantTemplate -Path enlwDemo.pnp
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ServerException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

#### Steps to Reproduce

Se above.  Would be good if there was more detail or even a line number given it is referencing the XML ( sort off)
The only way I can resolve this is comment huge chunks of the XML.  could take a while ;-(

Thanks for your contribution! Sharing is caring.

**Comment by erwinvanhunen** [comment]
Please execute Get-PnPException straight after the error. You will see in more detail where in the engine it went wrong and that can help to pinpoint the issue.
________________________________

**Comment by westerdaled** [comment]
Wow that was a quick response. Yes will do, when I. get in. the office tommorow morning . This sharing is caring really works!

**Comment by westerdaled** [comment]
It looks like this is my bad as in I made significant changes to the supplied starterkit.xml  which did partially deploy . We have since deployed the original to another dev tenant.  Looks like we need to retrofit all changes , line by line...

**Comment by joaojmendes** [comment]
I have the same error but I didn't change anything ....

**Comment by westerdaled** [comment]
@joaojmendes  can you confirm you have followed all the prereqs inc admin for term store and app deployed in app catalogue. , I got the issue in a FR dev tenant. Just tweeted my colleague who successfully deployed to her dev tenant without changes.  She confirmed her tenant was FR albeit only just enabled prior to deployment.

**Comment by nkhamis** [comment]
hey @westerdaled, any updates on this?  I get the same error, I have ensure prereqs inc admin for term store, I can verify that the app gets deployed to app catalog but does not get Deployed successfully: 

Deployment failed.  Correlation ID: dd36ae9e-f082-7000-a4f4-b5b244bf5546 | Deployment failed.  Correlation ID: dd36ae9e-f082-7000-a4f4-b5b244bf5546
Deployment failed.  Correlation ID: dd36ae9e-f082-7000-a4f4-b5b244bf5546

**Comment by westerdaled** [comment]
@nkhamis  Glad to hear.  I have since successfully deployed it another dev tenant.  As regards debugging the original deployment script  we could certainly do with better error reporting as these deployment files could get fairly large.

**Comment by bcameron1231** [comment]
@westerdaled  Looks like this may have resolved for you?

Can you confirm this old issue, we'd love to close out this ticket. Thanks!

**Comment by westerdaled** [comment]
Yes, this looks like an old issue please close.
