### ISSUE TITLE
PNP Starter kit home page custimzation

### ISSUE THREAD

**Issue by sramakuri** [SharePoint/sp-starter-kit#215]
#### Category
**- [ ] Question**
- [ ] Bug
- [ ] Enhancement

#### Steps to Reproduce

On Contosoportal home, we are planning to do some customizations like remove head content and merge with 1 row . Could you please update is it any possibilities is exist to remove/hide the rows in homepage ?  much appreciated if you provide suggestions on my query. 

Thanks in advance.

FYI : attached the screenshot for hide/remove rows

![2018-12-10_14-44-09](https://user-images.githubusercontent.com/44281108/49758022-dc364d00-fc8b-11e8-97b2-8ee5459bc8d0.jpg)

**Comment by waldekmastykarz** [comment]
Unfortunately, at this moment, it's not possible to remove/hide rows in a supported way. You could achieve the desired results using CSS or DOM manipulation, neither of which are reliable nor supported.

**Comment by bcameron1231** [comment]
Closing as it was it was answered and guidance was provided.
