### ISSUE TITLE
Save-PnPTenantTemplate : Can not access a closed Stream.

### ISSUE THREAD

**Issue by nkhamis** [SharePoint/sp-starter-kit#224]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I've modified my startkiter.xml file with custom settings and I'm trying to generate a new pnp template file using the Read-PnpTenantTemplate and the Save-PnpTenantTemplate PowerShell commands.

#### Observed Behavior

PS C:\sp-starter-kit\provisioning> $kit = Read-PnPTenantTemplate -Path .\starterkit.xml
PS C:\sp-starter-kit\provisioning> Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp
**Processing template
Processing ..\package\sharepoint-starter-kit.sppkg
Save-PnPTenantTemplate : Can not access a closed Stream.
At line:1 char:1
Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp
    + CategoryInfo          : NotSpecified: (:) [Save-PnPTenantTemplate], ObjectDisposedException
    + FullyQualifiedErrorId : System.ObjectDisposedException,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.SaveTenantTemplate**

#### Steps to Reproduce

I'm running the following to generate a new pnp starterkit pnp template file:

Connect-PnPOnline https://mytenant.sharepoint.com
$kit = Read-PnPTenantTemplate -Path .\starterkit.xml
Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp

**Comment by Sunni-at-Tecology** [comment]
I have the same issue even with unmodified starterkit.xml.

**Comment by Eldanno2004** [comment]
I have the same issue as well. It does create a new starterkit.pnp file, but it appears to be empty compared to the original.

![image](https://user-images.githubusercontent.com/348927/50694320-9446e380-1007-11e9-8f4e-b0dfbfb8ec2e.png)

**Comment by memsim1010** [comment]
I'm having the same issue.

**Comment by memsim1010** [comment]
@mohan23 Thank you!  This worked for me as well!

**Comment by eoverfield** [comment]
@nkhamis In the root of your SPFx solution, this is the folder that contains your package.json file including other primary project files, run the command:

gulp clean

This should remove your build folders including dist, lib, and temp. You can also manually remove these file as well. If you then run the following commands, in order, you can rebuild your sppgk file that will be placed in your sharepoint/solution folder
gulp build
gulp bundle --ship
gulp package-solution --ship

There are ways to optimize this and clean does a little more than stated above, yet this should help you with this issue.

**Comment by Eldanno2004** [comment]
@mohan23 & @eoverfield - I tried to follow those directions, but I do not have a dist,lib and temp folder within the project. 

I tried to extract a clean download of the "sp-starter-kit" and work from a fresh environment. I then made one single change to the starterkit.xml where I changed the line:

`<pnp:Parameter Key="Company">Contoso Electronics</pnp:Parameter>`
to
 `<pnp:Parameter Key="Company">temp</pnp:Parameter>`

and tried to repackage the solution using 
`$kit = Read-PnPTenantTemplate -Path .\starterkit.xml
Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp`

and get the same error as before.

`PS D:\pnp\provisioning> Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp
Processing template
Processing ..\package\sharepoint-starter-kit.sppkg
Save-PnPTenantTemplate : Can not access a closed Stream.
At line:1 char:1
+ Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Save-PnPTenantTemplate], ObjectDisposedException
    + FullyQualifiedErrorId : System.ObjectDisposedException,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.SaveTenantTemplate`

![image](https://user-images.githubusercontent.com/348927/51334448-d16e9500-1a4d-11e9-8e9e-2f6fe47c90f7.png)

Unfortunately, my experience with pnp/powershell is limited so I am not understanding where this error is coming from. If you have any other ideas or a different way to change the hierarchy of the site please let me know!

The end goal would be to deploy this starter kit with additional sites for additional departments.

**Comment by eoverfield** [comment]
@Eldanno2004 my response was in regards to cleaning / rebuilding just the SPFx solution, .sppkg. If you wanted to rebuild the sppkg file, you would want to execute the gulp commands from the solution folder.

**Comment by eoverfield** [comment]
@Eldanno2004 The particular error associated with this issue is the closed stream issue. We have found this error occurs if the sppkg is over 10MB. You might need to rebuild the sppkg to repack the starterkit.pnp file. Can you confirm the size of the solution .sppkg you are attempting to use when repacking starterkit.pnp?

**Comment by Eldanno2004** [comment]
Yes - the default sharepoint-starter-kit.sppkg is 11.6MB.

And you guessed what comes next.... How do I rebuild the sppkg?

Is that what the gulp actions above are doing?

Thanks in advance.

**Comment by eoverfield** [comment]
@Eldanno2004 that will likely do it. You do need to have node installed, and then the gulp package. Once you address those SPFx requirements, you can execute the following from your "solution" folder.

gulp build
gulp bundle --ship
gulp package-solution --ship

Then you should be able to rebuild your .pnp file.

**Comment by bcameron1231** [comment]
I just downloaded a new package from this repo. I made the same change as @Eldanno2004 in the xml file. I re-packaged the pnp file by running...

$kit = Read-PnPTenantTemplate -Path .\starterkit.xml
Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp


The Save-PnPTenantTemplate command worked successfully for me.

Can you confirm what version  of PnP-PowerShell you are using so I can match version  in my testing?

**Comment by Eldanno2004** [comment]
@bcameron1231 & @eoverfield 
VS is version 1.30.2

![image](https://user-images.githubusercontent.com/348927/51348857-bada3500-1a71-11e9-85bb-08239a37f4a5.png)

I think there must be an issue in which libraries I have installed as well. I tried the gulp commands above, but am getting quite a few errors there as well.

`internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\pnp\solution\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)`

**Comment by eoverfield** [comment]
@Eldanno2004 what version of pnp-powershell are you using?

Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

for gulp build to work, you will need to first install all node packages. you can run the following command in the solution folder:
npm install

**Comment by Eldanno2004** [comment]
@eoverfield I have two evidently. I believe 3.5 is the latest?

SharePointPnPPowerShellOnline 3.5.1901.0
SharePointPnPPowerShellOnline 3.4.1812.2


I've tried running npm install in the solutions folder but get error's stating I couldn't load VCBuild.exe and that I needed the .net framework or VS2005. I went and found the .net install and installed that, I am using VS....

Could I just not have set up VS correctly? Is there another IDE that I should try?

This is the error when running npm install:
`Build started 1/17/2019 4:15:17 PM.
Project "D:\pnp\solution\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\pnp\solution\node_modules\node-sass\build\binding.
sln]
Done Building Project "D:\pnp\solution\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"D:\pnp\solution\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Vis
ual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\pnp\solution\node_modules\node-sass\build\bindin
g.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.57
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\pnp\solution\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\pnp\\solution\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\pnp\solution\node_modules\node-sass
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.0.0 requires a peer of tsutils@1.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DanGi\AppData\Roaming\npm-cache\_logs\2019-01-17T21_15_20_601Z-debug.log
PS D:\pnp\solution>`

**Comment by bcameron1231** [comment]
Yes 3.5 is the latest. You should probably uninstall the older one (there are issues with having multiple versions installed).  

 Uninstall-Module SharePointPnPPowerShellOnline -RequiredVersion 3.4.1812.2

With that being said, I have tested with the same configuration as you and haven't been able to reproduce the issue, in regards to the packaging of the pnp file.

**Comment by bcameron1231** [comment]
Hi, I am working through the issues list. I understand this is an old issue, and may not be relevant anymore. 

I was unable to reproduce the issue, can you confirm if this is relevant or if this ticket can be closed?
