### ISSUE TITLE
sp-starter-kit/solution/src/webparts/personalEmail/components/PersonalEmail.tsx

### ISSUE THREAD

**Issue by Grunge** [SharePoint/sp-starter-kit#226]
#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I expext that the Sample
sp-starter-kit/solution/src/webparts/personalEmail/
will show only Emails.

#### Observed Behavior
Unfortunately i get all kind of Messages like MSTeams, Skype and so on.

#### Steps to Reproduce
I guess that there should be a search or filter parameter used.
unfortunately i didn't know how to get it to work:

sp-starter-kit/solution/src/webparts/personalEmail/components/PersonalEmail.tsx
//?search="kind:email"
//contacts, docs, email, faxes, im, journals, meetings, notes, posts, rssfeeds, tasks, or voicemail.	

    this.props.graphClient
      .api("me/messages") 
      .version("v1.0")         
      .select("bodyPreview,receivedDateTime,from,subject,webLink")
      //.query({search: "\"kind:email\""})
      .top(this.props.nrOfMessages || 5)
      .orderby("receivedDateTime desc")
      .get((err: any, res: IMessages): void => {
        if (err) {
          // Something failed calling the MS Graph
          this.setState({
            error: err.message ? err.message : strings.Error,
            loading: false
          });
          return;
        }

Thanks for the great work!

**Comment by waldekmastykarz** [comment]
I've just merged #182. Sorry for the delay

**Comment by bcameron1231** [comment]
Closed, Fixed via #182
