### ISSUE TITLE
Error provisioning script 

### ISSUE THREAD

**Issue by iainl** [SharePoint/sp-starter-kit#228]
#### Category
- [ ] Question
- [ X] Bug
- [ ] Enhancement

#### Observed Behavior

PS C:\users\iainl\downloads\sp-starter-kit-master\sp-starter-kit-master\provisioning> Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SiteUrlPrefix"="demosites"}
Apply-PnPTenantTemplate : {"d":{"CreateGroupEx":{"__metadata":{"type":"Microsoft.SharePoint.Portal.GroupSiteInfo"},"Doc
umentsUrl":null,"ErrorMessage":null,"GroupId":"5b7fe3a2-687d-4271-a316-57a0876adf52","SiteStatus":1,"SiteUrl":null}}}
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SiteUrlPr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

#### Steps to Reproduce

Run script -  Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SiteUrlPrefix"="deletethissite"}

**Comment by bcameron1231** [comment]
Hi. We are working through some of these old issues. 

Can you confirm if this is still an issue for you, or if we can close out this ticket?

**Comment by betasoft365** [comment]
Issues resolved, please close. Thanks
