### ISSUE TITLE
Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.

### ISSUE THREAD

**Issue by PaulMac66** [SharePoint/sp-starter-kit#230]
I have created a number of communication sites using the SPFX Starter Kit. This was the older version using deploy.ps1. The tenant is on first release.

All of which worked fine up until today. The portal footer does not load at all now.

I have attached the solution package for you to look at:

[sharepoint-starter-kit.zip](https://github.com/SharePoint/sp-starter-kit/files/2736651/sharepoint-starter-kit.zip)

I get this error message
**_Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.b8eb4ec9-934a-4248-a15f-863d27f94f60'. Error information is '***Extension failed to initialize for componentId "b8eb4ec9-934a-4248-a15f-863d27f94f60".'.
    at sp-pages-assembly_en-gb_df22aec1cceb5720092e8a67086ee1fa.js:2246_**

Has anyone got any ideas on what might be causing this or even better the answer?

#### Category
- [ ] Question

#### Expected or Desired Behavior

The expected behavior is the portal footer loads and all is good

#### Observed Behavior

The portal footer does not load. 
However, the collaboration footer works fine on all team sites.

Thanks for your contribution! Sharing is caring.

**Comment by Nickens** [comment]
> I have created a number of communication sites using the SPFX Starter Kit. This was the older version using deploy.ps1. The tenant is on first release.
> 
> All of which worked fine up until today. The portal footer does not load at all now.
> 
> I have attached the solution package for you to look at:
> 
> [sharepoint-starter-kit.zip](https://github.com/SharePoint/sp-starter-kit/files/2736651/sharepoint-starter-kit.zip)
> 
> I get this error message
> **_Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.b8eb4ec9-934a-4248-a15f-863d27f94f60'. Error information is '***Extension failed to initialize for componentId "b8eb4ec9-934a-4248-a15f-863d27f94f60".'. at sp-pages-assembly_en-gb_df22aec1cceb5720092e8a67086ee1fa.js:2246_**
> 
> Has anyone got any ideas on what might be causing this or even better the answer?
> 
> #### Category
> * [ ]  Question
> 
> #### Expected or Desired Behavior
> The expected behavior is the portal footer loads and all is good
> 
> #### Observed Behavior
> The portal footer does not load.
> However, the collaboration footer works fine on all team sites.
> 
> Thanks for your contribution! Sharing is caring.


Make sure you have the "PnP-PortalFooter-Links" list on the site?

/N

**Comment by eoverfield** [comment]
I have received errors similar to:
*Extension failed to initialize for componentId "b8eb4ec9-934a-4248-a15f-863d27f94f60"
When I added a new module without updating the sppkg package in the app catalog.

Were any changes made to the footer at all?

**Comment by PaulMac66** [comment]
No Changes have been made to the footer. All was working fine on all 40 sites. Then less than a week ago the portal footer has stopped working, giving out the above error.

**Comment by PaulMac66** [comment]
Ok People i have fix my own issue.

It turns out that in the "**PnP-PortalFooter-Links**" list if an item does not have a valid "**LINKURL**", the footer will break.

A user had added a link to the list and left the **LINKURL** blank, this then caused the footer not to render on the page at all.

@eoverfield you could look at this for your issue. Hope this helps some people.
