### ISSUE TITLE
Getting "Apply-PnPTenantTemplate : Too Many Requests" error when trying to install SpStarterKit

### ISSUE THREAD

**Issue by leandrowebb** [SharePoint/sp-starter-kit#233]
Getting "Apply-PnPTenantTemplate : Too Many Requests" error when trying to install SpStarterKit

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Successful installation of spstarterkit

#### Observed Behavior

**1. Error was returned:**
Apply-PnPTenantTemplate : {"error":{"code":"-1, System.Net.WebException","message":{"lang":"en-US","value":"The remote server
returned an error: (429)."}}}
At line:1 char:1
+ Apply-PnPTenantTemplate -Path C:\Users\admin\Downloads\sp-starter-kit ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

**2.App catalog:** 
sharepoint-starter-kit.sppkg was deployed on the target site and the webparts seems to be installed

**3. Sites**
Portal, HR and Marketing were created

![capture](https://user-images.githubusercontent.com/46533673/50913770-b327ea00-13fa-11e9-8ed1-81358c4229e3.PNG)

**4. Provisioning**
Template Provisioning was not completed, i don't see custom footer on the portal site.

#### Steps to Reproduce

PS > Apply-PnPTenantTemplate -Path C:\Users\admin\Downloads\sp-starter-kit-master\sp-starter-kit-master\provisionin
g\starterkit.pnp -Parameters @{"SiteUrlPrefix"="amwarepnp"}

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, I noticed this ticket is over a year old. We are actively working on cleaning up the issues list and this item may have already been address in a previous update. If this is still an issue for you, could you please re-create a new issue in the issues list, so we can better track it.
