### ISSUE TITLE
People Directory webpart free text search only returns a maximum of 4 results

### ISSUE THREAD

**Issue by colinrippeyfinarne** [SharePoint/sp-starter-kit#234]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Using the free text search I should see all expected results.

#### Observed Behavior

I only ever see a maximum of 4 results.

#### Steps to Reproduce

Execute a free text search for a surname/forename that should return more than 4 results.

I believe that this is an issue with the underlying search REST API, I have raised an issue on the API page here:

https://github.com/SharePoint/sp-dev-docs/issues/3261

Thanks for your contribution! Sharing is caring.

**Comment by colinrippeyfinarne** [comment]
I am wondering if anyone else is seeing the same issue as I am, I have updated https://github.com/SharePoint/sp-dev-docs/issues/3261 with examples of what I am seeing.

Basically we are now going to remove the Starter Kit people directory as it does not return the correct results.

**Comment by mickyc1** [comment]
I have the same issue as well. Had a look at the code and cannot see anywhere obvious that handles this

**Comment by bcameron1231** [comment]
I am not able to reproduce this. Can you confirm if this is still an issue for you? If not, feel free to close out this ticket.

Thanks,

**Comment by colinrippeyfinarne** [comment]
This issue is no longer present.
