### ISSUE TITLE
Deploy issue.

### ISSUE THREAD

**Issue by jamescarr1988** [SharePoint/sp-starter-kit#235]
Hi,

I get the following error when running the deploy. 

WARNING: Tenant app catalog doesn't exist. ALM step will be skipped!
Apply-PnPTenantTemplate : There is no app catalog site for this tenant.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SiteUrlPr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

**Comment by bcameron1231** [comment]
Sounds like your Tenant App Catalog isn't configured in your environment. Please follow the pre-requirements checklist to confirm.

https://github.com/SharePoint/sp-starter-kit#pre-requirements

**Comment by eoverfield** [comment]
@jamescarr1988 
https://docs.microsoft.com/en-us/sharepoint/use-app-catalog
