### ISSUE TITLE
 MyLinksDialog opens once only

### ISSUE THREAD

**Issue by Krak86** [SharePoint/sp-starter-kit#236]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

> When I am using spfx 1.7.0 with "CollabFooter" extension I have issues with "MyLinksDialog", it opens only once, then the grey background appears only.
>

#### Observed Behavior

> When you are editing "MyLinksDialog" in  "CollabFooter" extension the modal window should be opened every time while you're clicking on it, not once.
>

#### Steps to Reproduce

> Install extension and click on edit "Edit My Links" button more than 1 times.
>
> I found a solution to fix it: onAfterClose and  ReactDOM.unmountComponentAtNode methods hsould be added just to clean up the element for the next dialog. I've created [pull request](https://github.com/SharePoint/sp-starter-kit/pull/237) for it.
>

**Comment by bcameron1231** [comment]
I noticed you had a PR for this. I believe this was also fixed in #232

**Comment by simonagren** [comment]
@krak86 @bcameron1231 I'ts fixed aswell in my PR. 
Using OnAfterClose will only solve this issue in Chrome etc.
My way of doing it works in all browsers. It's essentially the same thing but done before we close the dialog, not after 😀
