### ISSUE TITLE
Can the Portal Footer, deployed on the hub site, be shown other sites in the hub?

### ISSUE THREAD

**Issue by elpinto007** [SharePoint/sp-starter-kit#239]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Is there a way, or a new feature, where if the portal footer is deployed on the hub site, the same footer can be shown on all the sites in the hub?

#### Observed Behavior
At present, the footer is only showing on the hub site, but not on the other sites in the hub.

**Comment by eoverfield** [comment]
@elpinto007 The footer for the hub site included in the starter kit is the collab footer. You could set a default site design for all sites associated with a hub post deployment.
https://docs.microsoft.com/en-us/sharepoint/set-up-site-design-hub-site

**Comment by elpinto007** [comment]
> hub



> @elpinto007 The footer for the hub site included in the starter kit is the collab footer. You could set a default site design for all sites associated with a hub post deployment.

I thought the Collab footer was for Team sites and the Portal footer for Communication sites. I made a communication site my hub site. I assume I can still deploy the collab footer on a Communication site and remove the portal footer. 
I havent tried using the site designs yet - I will read a bit more into this. Thanks for the tip!

**Comment by eoverfield** [comment]
@elpinto007 yes, true. Collab footer by default is used for Team sites. I do not see any specific reason why the collab footer couldn't be used for a comm site though.

**Comment by elpinto007** [comment]
Using the collaboration footer, I can achieve a footer across my sites. I just need to install the app (which can be done using site designs).
Thanks!
