### ISSUE TITLE
Apply-PnpTenantTemplate Issue : DocumentsUrl null

### ISSUE THREAD

**Issue by philippe-entringer** [SharePoint/sp-starter-kit#241]
here is the Powershell Commands & Output 
`
$targetPortalSite = "https://m365x311235.sharepoint.com/sites/pnp3_portal"
$creds = Get-Credential
Connect-PnPOnline -Url $targetPortalSite -Credentials $creds
Apply-PnPTenantTemplate -Path .\starterkit.pnp

`**
PS C:\Sources\sp-starter-kit-master\provisioning> Apply-PnPTenantTemplate -Path .\starterkit.pnp
Apply-PnPTenantTemplate : 
{"d":{"CreateGroupEx":{"__metadata":{"type":"Microsoft.SharePoint.Portal.GroupSiteInfo"},"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"293f2be8-f4cb-4625-b7a3-7b100e887432","SiteStatus":1,"SiteUrl":null}}}
Au caractère Ligne:1 : 1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate**
 `

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

MoreInfo: 
Update on my Windows 10 machine
3.5.1901.0 SharePointPnPPowerShellOnline

**Comment by Marmalade118** [comment]
Did you manage to find a workaround for this? I'm facing the same issue and if I run Apply-PnpTenantTemplate again I then get an error saying 'Url of the site is required' and can't progress any further.

**Comment by philippe-entringer** [comment]
The "Apply-PnpTenantTemplate" solution doesn't work for me so I prefer to use the  Waldek Bash script that did the job
https://blog.mastykarz.nl/setup-sharepoint-starter-kit-any-platform/

**Comment by jaywellings** [comment]
I have run into this error a number of times now, and the following are my observations:

The `DocumentUrl ` error seems to occur intermittently when provisioning sites that have `BaseSiteTemplate="GROUP#0"` attribute on the provisioning template element.  It would appear if the provisioning process fails to successfully create the group this is the error that is thrown. However, the site is still created but appears to be left in an incomplete state.  

the second error of `Url of the site is required` will happen if you attempt to provision the site again with the same URL as one that errored with the `DocumentUrl `error. 

In attempting to delete this site that was created that threw the `DocumentUrl` error I have noticed it is missing this checkbox on the delete pop up message: 
![image](https://user-images.githubusercontent.com/1410735/58130096-234d4480-7c13-11e9-9fba-bf8e550e3980.png)

That site was unable to be deleted for at least an hour from the Active Sites page in the Admin.  

Work arounds that worked for me
- use another BaseSiteTemplate, I quickly threw in "STS#0" this seemed to work, but I don't really know the full impact of this ( i think it just skips group creation)
- If you get the `Url of the site is required` error, change the URL of the site you are provisioning as this is probably a site in a "bad state" and you wont be able to re-deploy to that site.
--
