### ISSUE TITLE
Sites not getting created

### ISSUE THREAD

**Issue by karthikmakam** [SharePoint/sp-starter-kit#245]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

Hi Team,

I followed the deployment steps in my tenant and after running the command
Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"SitePrefixUrl"="company"}
the script gets executed and i dont see any errors but when i check in my tenant site collections, no new sites are created. Only TermSets are created.

Please advise.

**Comment by eoverfield** [comment]
Could you please re-run, then provide a snapshot of what is returned in PowerShell?
