### ISSUE TITLE
Open phone software from footer

### ISSUE THREAD

**Issue by ricmaic** [SharePoint/sp-starter-kit#247]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

How can a phone number (instead of the e-mail address) be stored in the footer so that the phone client / softphone opens when you click on the phone number?

#### Observed Behavior

The e-mail software opens.

Thanks.

**Comment by bcameron1231** [comment]
You will need to pull down the source code and do a new build of the SPFx solution and upload the package to your environment.

This control is in the ["PortalFooter" Application Customizer](https://github.com/SharePoint/sp-starter-kit/blob/master/solution/src/extensions/portalFooter/components/PortalFooter/PortalFooter.tsx)

On line 40 there is a line that specifies to open the mail application using "mailto". You will need to change this to "tel"

OLD
```
  private _handleSupport(): void {
    **const supportUrl: string = `mailto:${this.props.support}`;**
    location.href = supportUrl;
    console.log(supportUrl);
  }
```
NEW
```
  private _handleSupport(): void {
    **const supportUrl: string = `tel:${this.props.support}`;**
    location.href = supportUrl;
    console.log(supportUrl);
  }
```
