### ISSUE TITLE
Errors on using PortalFooter extension codes - Property state / props / 'setState' does not exist on type 'PortalFooter'

### ISSUE THREAD

**Issue by Rxie12** [SharePoint/sp-starter-kit#248]
I created a solution folder for portalFooter extension using Application Customizer, and then copies the codes of PortalFooter to my solution files. In the file PortalFooter.tsx (c:/solution/src/extensions/portalFooter/components/PortalFooter/) and MyLinksDialog.tsx,  I got the following errors:
  Property 'state' does not exist @ this.state = {...} inside constructor(props: IPortalFooterProps);
  Property 'props' does not exist @ const wasExpanded: boolean = this.state.expanded;
  Property 'setState' does not exist @   
     this.setState({
      expanded: !wasExpanded,
      toggleButtonIconName: wasExpanded ? 'DoubleChevronUp' : 'DoubleChevronDown'
    });

**Comment by Rxie12** [comment]
I am new to React component and typescripts.  have tried to import 'react-autobind' but not help

**Comment by eoverfield** [comment]
Did you also copy of IPortalFooterProps.ts and IPortalFooterState.ts? If you did, ensure that you have the proper "import" references at the top of PortalFooter.tsx.

**Comment by Rxie12** [comment]
yes. they both are imported without problems.
import {IPortalFooterProps} from './IPortalFooterProps';
import {IPortalFooterState} from './IPortalFooterState';

**Comment by Rxie12** [comment]
In the package.json, it shows:
  },
  "dependencies": {
    "@microsoft/decorators": "1.7.1",
    "@microsoft/sp-application-base": "1.7.1",
    "@microsoft/sp-core-library": "1.7.1",
    "@microsoft/sp-dialog": "1.7.1",
    "@microsoft/sp-office-ui-fabric-core": "^1.7.1",
    "@pnp/common": "^1.2.9",
    "@pnp/logging": "^1.2.9",
    "@pnp/odata": "^1.2.9",
    "@pnp/sp": "^1.2.9",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "^5.21.0",
    "react-autobind": "^1.0.6"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.7.1",
    "@microsoft/sp-tslint-rules": "1.7.1",
    "@microsoft/sp-module-interfaces": "1.7.1",
    "@microsoft/sp-webpart-workbench": "1.7.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }

**Comment by eoverfield** [comment]
Would you please provide the entire line of code where you are creating the PortalFooter class, which should be extending React.Component? 

Similar to:
export class PortalFooter extends React.Component<IPortalFooterProps, IPortalFooterState> {

The error you are receiving is saying that this.state does not exist. It is declared for you when you inherit the React.Component class, yet is only available when you provide the second class parameter, in the sample above, IPortalFooterState.

**Comment by Rxie12** [comment]
export class PortalFooter extends React.Component<IPortalFooterProps, IPortalFooterState> {
  constructor(props: IPortalFooterProps) {
    super(props);
       this.state = {
      expanded: false,
      toggleButtonIconName: 'DoubleChevronUp',
      loadingLinks: false,
      links: props.links,
    };  
  }

**Comment by Rxie12** [comment]
Here is the export interface IPortalFooterState.ts which I got from starter-kit:

import { ILinkGroup } from ".";

export interface IPortalFooterState {
  // state variable to show the result of saving my links
  myLinksSaved?: boolean;
  // used to hold the expanded/collapsed state for menu
  expanded: boolean;
  // used to hold the link groups
  links: ILinkGroup[];
  // used to determine if we are loading the links
  loadingLinks: boolean;
  // used to manage the expand/collapse button icon
  toggleButtonIconName: string;
}

**Comment by Rxie12** [comment]
I found out these issues only happened in .tsx files (e.g. those example.tsx files under \src\components\ folder

**Comment by Rxie12** [comment]
I solved this issue.
