### ISSUE TITLE
PnP Web Parts all display the same error

### ISSUE THREAD

**Issue by thisidiotsays** [SharePoint/sp-starter-kit#25]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Tiles, Personal and other PnP should display information and render properly

#### Observed Behavior
All custom web parts display a variation of the same error message (I've hidden my domain name). The message below is from the pnpTiles web part:

 [SPLoaderError.loadComponentError]:
***Failed to load component "26cb4af3-7f48-4737-b82a-4e24167c2d07" (pnpTiles).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/#######.sharepoint.com/sites/AppCatalog/ClientSideAssets/3624777a-337d-4b34-8384-5ab774c069aa/solution-controlstrings_en-us_9fdf3a263d9b4c41bea5ddcb4928cf9d.js' for resource 'ControlStrings' in component '26cb4af3-7f48-4737-b82a-4e24167c2d07' (pnpTiles). There was a problem in the server.

I also notice that I can't Approve any of the APIs in the SharePoint Admin Center. I receive the [HTTP]400 error and the message "A service principal with the name xxxxxx could not be found"

#### Steps to Reproduce
I followed the steps from the front page of the sp-starter-kit GitHub Page.

I have also 
- Ensured the account I am using is a Global Admin
- It is a Term Store Administrator
- I have tried uploading the solution from the package directory. I also tried rebuilding the solution and uploading the new package into the App Catalog

**Comment by andreasblueher** [comment]
@thisidiotsays I'm seeing the same message all over my sites so I think there might be an issue with the CDN.

**Comment by thisidiotsays** [comment]
@andreasblueher thanks for the update. I will keep an eye on it and see if it resolves itself later.

**Comment by VesaJuvonen** [comment]
This is generic CDN issue. If you disable Office 365 CDN from your tenant, that will solve it for now. We are working on fixing the actual root issue. Closing this one as this issue is nothing on the Starter Kit. You can follow up on the CDN issue resolution from the following item at sp-dev-docs issue list - https://github.com/SharePoint/sp-dev-docs/issues/1731

**Comment by thisidiotsays** [comment]
@VesaJuvonen Thanks. I'll check out that link

**Comment by andreasblueher** [comment]
To disable your Office 365 CDN from your tenant you need to run the following command:

`Set-SPOTenantCdnEnabled -CdnType Private -Enable $false`

More information can be found [here](https://support.office.com/en-us/article/use-the-office-365-content-delivery-network-with-sharepoint-online-bebb285f-1d54-4f79-90a5-94985afc6af8)

**Comment by VesaJuvonen** [comment]
Actually, this should be as following as we are talking about Public CDN, not Private CDN.

`Set-SPOTenantCdnEnabled -CdnType Public -Enable $false`
