### ISSUE TITLE
Provisioning folder missing Files

### ISSUE THREAD

**Issue by kartikvega** [SharePoint/sp-starter-kit#250]
#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

If i look at the provisioning folder, i see its empty, the deploy.ps1, function.ps1 various xml files are missing. have they been moved or deprecated? Say we modify something how do we deploy our changes to SPO now?

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
@kartikvega please review to https://github.com/SharePoint/sp-starter-kit/tree/master/provisioning, you should see the same files as listed here if you pull the latest master branch.

Within the documentation, under common notes, you will see that you can make changes to starterkit.xml, then save a new .pnp package, i.e.:

$kit = Read-PnPTenantTemplate -Path .\starterkit.xml
Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp

This allows you to customize your installation.

**Comment by kartikvega** [comment]
Thanks for the reply, however on the master branch i do not see the files, really puzzling. 
As an example look at the files in this commit: https://github.com/SharePoint/sp-starter-kit/tree/2c2dfa872b4df68c0db606e51caf3243103206d3/provisioning, i see deploy.ps1. 

using this and hubsite.xml and other files i see references in documentation where i can modify the solution branding and the heirarchy, the footer text etc. 

The goal is to see if i can get this working or atleast take components out of this solution and reproduce this on a chinese tenant(provided by 21Vianet). 

I did see the startkit modification and that might be one way of doing it but the deploy process was too long , the deploy.ps1 made sense to push required components.

**Comment by eoverfield** [comment]
Yes, the provisioning process had a major overhaul a few months ago, utilizing the newish Apply-PnPTenantTemplate commandlet.

You should be able to make the customization you are looking for to starterkit.xml, although I cannot say how well that will work on a chinese tenant.

**Comment by kartikvega** [comment]
Thanks you for the update.

**Comment by Michael1958** [comment]
Where is the deploy.ps1 file?  I don't seem to see it anywhere.
Thanks

**Comment by eoverfield** [comment]
Hi @Michael1958 , the deploy.ps1 was for a previous version of the starter kit. The new provisioning process uses Apply-PnPTenantTemplate that utilizes a .pnp file. You can review documentation here: https://github.com/SharePoint/sp-starter-kit/tree/master/provisioning
