### ISSUE TITLE
Customize StarterKit.pnp

### ISSUE THREAD

**Issue by hbash** [SharePoint/sp-starter-kit#253]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

Using the following, I expected the customized starterkit.xml to read and then save a starterkit.pnp.
I ran the following:

- $kit = Read-PnPProvisioningTemplate -Path '.\starterkit.xml' -Verbose  (<--Worked fine)
- Save-PnPTenantTemplate $kit -Out starterkit.pnp  (<--failed)

#### Observed Behavior
The assignment to $kit worked.  I was able to review the object in PowerShell immediate window.
The save failed with the following:

"
Save-PnPTenantTemplate : A positional parameter cannot be found that accepts argument 'OfficeDevPnP.Core.Framework.Provisioning.Model.ProvisioningTemplate'.
At line:1 char:1
+ Save-PnPTenantTemplate $kit -Out starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Save-PnPTenantTemplate], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.SaveTenantTemplate
"

#### Steps to Reproduce
To reproduce run the commands listed above.

**Comment by bcameron1231** [comment]
Hi, I'm working through the issues list. I understand this issue may be old and not relevant to you anymore. 

Can you confirm whether you still have this issue, or if this ticket can be closed?
