### ISSUE TITLE
Web Part Missing

### ISSUE THREAD

**Issue by colapig1114** [SharePoint/sp-starter-kit#259]
Hi, 
I would like to deploy the SharePoint Starter Kit web parts to my existing site collections. I have deployed package to my app catalog site and tenant deployed is Yes.  I also can see the App in my site collection. But the web parts are missing when I edit the page. Any ideas?

Thanks a lot.

Travis
![image](https://user-images.githubusercontent.com/35762617/54862203-0e337100-4d9c-11e9-895c-4f7a526d61f0.png)
![image](https://user-images.githubusercontent.com/35762617/54862207-22776e00-4d9c-11e9-880b-633026a9ac98.png)
![image](https://user-images.githubusercontent.com/35762617/54862214-3c18b580-4d9c-11e9-83da-be35e62054ca.png)

**Comment by eoverfield** [comment]
Did you deploy to a tenant app catalog or a site collection app catalog? Are you able to add other solutions to your app catalog and then use their included webparts / extensions?

Based on what you have provided, the webparts certainly should appear without further effort.

**Comment by colapig1114** [comment]
Hi, eoverfield
The solution works on my another tenant. It can be an environment issue. I am investigating at moment. will update this thread if I make any progress.

Thanks

**Comment by bcameron1231** [comment]
@colapig1114 Reviving this old thread. Did you resolve this issue? We'd love to close out this issue if possible.
