### ISSUE TITLE
Version Conflict error when provisioning

### ISSUE THREAD

**Issue by diver7** [SharePoint/sp-starter-kit#263]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Provisioning completes without error

#### Observed Behavior
I get this error when provisioning. Not sure what item has a bad version.
![image](https://user-images.githubusercontent.com/18582794/55098778-8051d180-508c-11e9-9daa-c06ebd4dd0a1.png)

**Comment by bcameron1231** [comment]
Hi. We are working on cleaning up some old issues. 

Did you ever get this resolved / is this still an issue for you?

**Comment by HHZZUUJH** [comment]
I have successfully performed provisioning

**Comment by bcameron1231** [comment]
Thank you. Closing this issue!
