### ISSUE TITLE
Apply-PnPTenantTemplate gives Task Cancelled error if you customize starterkit.pnp

### ISSUE THREAD

**Issue by Sunni-B** [SharePoint/sp-starter-kit#269]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Using Apply-PnpTenant template with a customized StarterKit.PnP file should work as described in the provisioning documentation.

#### Observed Behavior

Run the command: Apply-PnPTenantTemplate -path mystarterkit.pnp -Parameters @{"SitePrefixUrl"="ZZZZ_"}

Get error:
Apply-PnPTenantTemplate : A task was canceled.
At line:1 char:1
+ Apply-PnPTenantTemplate -path mystarterkit.pnp -Parameters @{"SitePre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], TaskCanceledException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

#### Steps to Reproduce

1. Clone new copy of repository.
2. Verify that the deployment works correctly with unmodified starterkit.pnp.
3. copy starterkit.xml to mystarterkit.xml (no edits necessary to repro)
4. In elevated PS, update to latest PNP module version if needed.
5. Run commands to build PNP:
     $kit = Read-PnPTenantTemplate -Path .\mystarterkit.xml
     Save-PnPTenantTemplate -Hierarchy $kit -Out mystarterkit.pnp
6. Verify that mystarterkit.pnp is created (note that it is much larger than starterkit.pnp)
7. Run Apply-PnPTenantTemplate -path mystarterkit.pnp -Parameters @{"SitePrefixUrl"="ZZZZ_"}

**Comment by kidfilkings** [comment]
Hi,
Are you having this issue here?
![image](https://user-images.githubusercontent.com/48958144/56364463-fb5a6380-61c4-11e9-8aa8-8964775e06c5.png)

If so, go to classic CA SharePoint Online >> Apps >> Apps Catalog >> SharePoint Apps >> delete 'sharepoint-starter-kit-client-side-solution' app.
After that it will redeploy the solution and continue the StarterKit deployment.

**Comment by Sunni-B** [comment]
Thanks for the reply. No, that's not the same error. I have done that. As I mentioned in my note, I can deploy without error if I don't modify the pnp file. If I create a new PNP with the solution (I don't even need to make a change, just create a new PNP given what's already there), then I get the error. And the error is a total failure - not skipping the solution.

**Comment by Sunni-B** [comment]
**deleted previous comment
@kidfilkings just tried again on my test tenant and it worked; resuming t-shooting on client tenant. Thanks!

**Comment by omishamisha** [comment]
@Sunni-B  I am getting the same error. Did you find a resolution?

**Comment by aharbold** [comment]
We haven't customized the pnp and we are still getting this error. We have tried removing the app and running again. Still no luck. Any resolution on this issue?

**Comment by mmahmud01** [comment]
getting same error. any help please?

Apply-PnPTenantTemplate : A task was canceled.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path C:\Users\mmahm\Downloads\sp-starter-k ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], TaskCanceledException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

**Comment by bilalkhan870** [comment]
i am facing the same issue on m tenant

**Comment by omishamisha** [comment]
I was able to pull an older copy of the starterkit and it worked.

Michelle Willard | Digital Workplace Consultant | Klarinet Solutions LLC

**Comment by bilalkhan870** [comment]
@omishamisha 
Thanks for your reply 

i did it using below link 
https://provisioning.sharepointpnp.com/home/details?packageId=5c3f13eb-e7c0-4d71-8154-d33dee71356d

**Comment by bcameron1231** [comment]
Hi, I noticed this ticket is over a year old, and it looks like you may have found a resolution.

We are actively working on cleaning up the issues list and this item may have already been address in a previous update. If this is still an issue for you, could you please re-create a new issue in the issues list, so we can better track it.
