### ISSUE TITLE
Developer Tenant cannot use this package?

### ISSUE THREAD

**Issue by cheynen** [SharePoint/sp-starter-kit#27]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Deploy SP Starter Pack to Developer Tenant

#### Observed Behavior

Uploading the sharePoint-starter-kit.sppkg results in "error in application" 
![image](https://user-images.githubusercontent.com/13007634/41428628-82db2216-6fbf-11e8-958b-a512e13dbc62.png)

#### Steps to Reproduce

Upload sppkg to app catalog in developer tenant

**Comment by jonasbjor** [comment]
Same here!

**Comment by bcameron1231** [comment]
@cheynen Can you confirm that your tenant is "targeted release for everyone" and that API Management is  available for you in the new SharePoint Admin Center?

**Comment by cheynen** [comment]
Yes, my tenant is targeted release.  
As it turns out, I deleted the app, waited an hour and uploaded it without error.  Unfortunately not one single bit of the deploy.ps1 would work thereafter.  This is discouraging.  
I am getting a lot of NuGet package errors that I don't seem able to correct in Code.

**Comment by VesaJuvonen** [comment]
As noted in the pre-requirements, this does require that the whole tenant is in Targeted release setting due to dependency on preview capabilities around the Microsoft Graph.

Notice also that if you move your tenant to Targeted release mode, it can take up to 24 hours for the setting to fully taken into account. I just tested this with one clean new tenant and got exactly the same exception around "Error in package", but after 18 hours from changing the settings, all works fine. We do understand that the wait time is not optimal, but can't fix that right now.

So - please do wait a while and try to install the sppkg file again on the app catalog. You cannot use deploy.ps1 unless you can successfully deploy the package to the tenant level.

**Comment by cheynen** [comment]
Thank you so much.  Waiting was the answer for the app package.  No errors today.

 

Now however I have npm errors – even though I ran npm update…  What does this mean?


 

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

**Comment by cheynen** [comment]
And then, when I run it again, it has been sitting here for half an hour, just like this…


 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

 

From: carolee.heynen@gmail.com <carolee.heynen@gmail.com> 
Sent: Friday, June 15, 2018 6:13 AM
To: 'SharePoint/sp-starter-kit' <reply@reply.github.com>
Subject: RE: [SharePoint/sp-starter-kit] Developer Tenant cannot use this package? (#27)

 

Thank you so much.  Waiting was the answer for the app package.  No errors today.

 

Now however I have npm errors – even though I ran npm update…  What does this mean?


 

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

**Comment by cheynen** [comment]
End result – incomplete installation…  Help?


From: carolee.heynen@gmail.com <carolee.heynen@gmail.com> 
Sent: Friday, June 15, 2018 7:05 AM
To: 'SharePoint/sp-starter-kit' <reply@reply.github.com>
Subject: RE: [SharePoint/sp-starter-kit] Developer Tenant cannot use this package? (#27)

 

And then, when I run it again, it has been sitting here for half an hour, just like this…


 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

 

From: carolee.heynen@gmail.com <mailto:carolee.heynen@gmail.com>  <carolee.heynen@gmail.com <mailto:carolee.heynen@gmail.com> > 
Sent: Friday, June 15, 2018 6:13 AM
To: 'SharePoint/sp-starter-kit' <reply@reply.github.com>
Subject: RE: [SharePoint/sp-starter-kit] Developer Tenant cannot use this package? (#27)

 

Thank you so much.  Waiting was the answer for the app package.  No errors today.

 

Now however I have npm errors – even though I ran npm update…  What does this mean?


 

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

**Comment by cheynen** [comment]
PS D:\git\sp-starter-kit\provisioning> .\deploy.ps1 -TenantUrl https://scleraca.sharepoint.com -SitePrefix MyDemo

Reading Site Hierarchy from ./hierarchy.json

Creating https://scleraca.sharepoint.com/sites/MyDemoportal

Creating MyDemohr

Creating MyDemomarketing

 

> deasync@0.1.12 install D:\git\sp-starter-kit\solution\node_modules\deasync

> node ./build.js

 

`win32-x64-node-8` exists; testing

Binary is fine; exiting

 

> node-sass@4.7.2 install D:\git\sp-starter-kit\solution\node_modules\node-sass

> node scripts/install.js

 

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-57_binding.node

Download complete

Binary saved to D:\git\sp-starter-kit\solution\node_modules\node-sass\vendor\win32-x64-57\binding.node

Caching binary to C:\Users\CaroleeHeynen\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

 

> phantomjs-prebuilt@2.1.16 install D:\git\sp-starter-kit\solution\node_modules\phantomjs-prebuilt

> node install.js

 

PhantomJS not found on PATH

Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip

Saving to C:\Temp\phantomjs\phantomjs-2.1.1-windows.zip

Receiving...

 

Received 17767K total.

Extracting zip contents

Removing D:\git\sp-starter-kit\solution\node_modules\phantomjs-prebuilt\lib\phantom

Copying extracted folder C:\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1529076395212\phantomjs-2.1.1-windows -> D:\git\sp-starter-kit\solution\node_modules\phanto

mjs-prebuilt\lib\phantom

Writing location.js file

Done. Phantomjs binary available at D:\git\sp-starter-kit\solution\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

 

> @microsoft/sp-loader@1.4.1 install D:\git\sp-starter-kit\solution\node_modules\@microsoft\sp-loader

> node npm-postinstall.js

 

 

> spawn-sync@1.0.15 postinstall D:\git\sp-starter-kit\solution\node_modules\spawn-sync

> node postinstall

 

 

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\git\sp-starter-kit\solution\node_modules\uglifyjs-webpack-plugin

> node lib/post_install.js

 

 

> node-sass@4.7.2 postinstall D:\git\sp-starter-kit\solution\node_modules\node-sass

> node scripts/build.js

 

Binary found at D:\GIT\sp-starter-kit\solution\node_modules\node-sass\vendor\win32-x64-57\binding.node

Testing binary

Binary is fine

 

> @pnp/spfx-controls-react@1.4.0 postinstall D:\git\sp-starter-kit\solution\node_modules\@pnp\spfx-controls-react

> node postinstall/install.js

 

INFO: Adding the required localized resource configuration to the config.json file.

npm : WARNING: it seems something is wrong with the config.json file or the "ControlStrings" reference was already set.

At D:\git\sp-starter-kit\provisioning\deploy.ps1:76 char:5

+     npm install

+     ~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (WARNING: it see...as already set.:String) [], RemoteException

    + FullyQualifiedErrorId : NativeCommandError

npm

WARN

optional

SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):

npm

WARN

notsup

SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1817 packages from 1672 contributors and audited 264619 packages in 4416.716s

found 10 vulnerabilities (1 low, 5 moderate, 4 high)

  run `npm audit fix` to fix them, or `npm audit` for details

Building solution

Bundling solution

Packaging solution

Provisioning solution

WARNING: An OAuth permission with the resource Microsoft Graph and scope Sites.Read.All already exists.

Parameter name: permissionRequest

WARNING: An OAuth permission with the resource Microsoft Graph and scope Contacts.Read already exists.

Parameter name: permissionRequest

WARNING: An OAuth permission with the resource Microsoft Graph and scope User.Read.All already exists.

Parameter name: permissionRequest

WARNING: An OAuth permission with the resource Microsoft Graph and scope Mail.Read already exists.

Parameter name: permissionRequest

WARNING: An OAuth permission with the resource Microsoft Graph and scope Calendars.Read already exists.

Parameter name: permissionRequest

Applying template to portal

WARNING: You specified to remove existing content types for the list with url '/sites/MyDemoportal/Lists/Alerts'. We found a list with the same url in the site. In case o

f a list update we cannot remove existing content types as they can be in use by existing list items and/or documents.

 

Id                                   Title                      Site Scripts                          

--                                   -----                      ------------                          

aae18efc-49e1-434c-9566-db7cad53438d Contoso Team Site          {cb3f84ac-8a5c-436f-b4ba-bfc9c839e128}

751e0fe8-5000-4466-a852-7a89e9543dc0 Contoso Communication Site {481c053a-0e5f-4de5-b763-8e2737128a28}

Updating navigation and applying collab templates

Connect-PnPOnline : The remote server returned an error: (404) Not Found.

At D:\git\sp-starter-kit\provisioning\deploy.ps1:139 char:28

+ ... onnection = Connect-PnPOnline -Url "$TenantUrl/sites/$SitePrefix$($ch ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], WebException

    + FullyQualifiedErrorId : System.Net.WebException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline

WARNING: The source site from which the template was generated had a base template ID value of GROUP#0, while the current target site has a base template ID value of SITE

PAGEPUBLISHING#0. This could cause potential issues while applying the template.

Connect-PnPOnline : The sign-in name or password does not match one in the Microsoft account system.

At D:\git\sp-starter-kit\provisioning\deploy.ps1:139 char:28

+ ... onnection = Connect-PnPOnline -Url "$TenantUrl/sites/$SitePrefix$($ch ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], IdcrlException

    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.IdcrlException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline

WARNING: The source site from which the template was generated had a base template ID value of GROUP#0, while the current target site has a base template ID value of SITE

PAGEPUBLISHING#0. This could cause potential issues while applying the template.

Done. 

 

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

 

From: carolee.heynen@gmail.com <carolee.heynen@gmail.com> 
Sent: Friday, June 15, 2018 7:42 AM
To: 'SharePoint/sp-starter-kit' <reply@reply.github.com>
Subject: RE: [SharePoint/sp-starter-kit] Developer Tenant cannot use this package? (#27)

 

End result – incomplete installation…  Help?


From: carolee.heynen@gmail.com <mailto:carolee.heynen@gmail.com>  <carolee.heynen@gmail.com <mailto:carolee.heynen@gmail.com> > 
Sent: Friday, June 15, 2018 7:05 AM
To: 'SharePoint/sp-starter-kit' <reply@reply.github.com>
Subject: RE: [SharePoint/sp-starter-kit] Developer Tenant cannot use this package? (#27)

 

And then, when I run it again, it has been sitting here for half an hour, just like this…


 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

 

From: carolee.heynen@gmail.com <mailto:carolee.heynen@gmail.com>  <carolee.heynen@gmail.com <mailto:carolee.heynen@gmail.com> > 
Sent: Friday, June 15, 2018 6:13 AM
To: 'SharePoint/sp-starter-kit' <reply@reply.github.com>
Subject: RE: [SharePoint/sp-starter-kit] Developer Tenant cannot use this package? (#27)

 

Thank you so much.  Waiting was the answer for the app package.  No errors today.

 

Now however I have npm errors – even though I ran npm update…  What does this mean?


 

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

**Comment by VesaJuvonen** [comment]
We do recommend using the spppkg file in the package folder, as noted in the readme file. You can install that to your app catalog in your tenant and that will then skip the npm install etc. commands in the flow, which would require development setup.

**Comment by cheynen** [comment]
Thank you,

 

Installing the sppkg is simple enough, and in fact, I do that before ruining the .ps1.  Is there a link to how to make the example sites from that though?

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

**Comment by cheynen** [comment]
Thanks Beau,

 

I was able to install the starter kit after coming back to the project a couple days later.  Evidently, because my dev tenant was new, I needed to wait a while?  In any case the script worked.  EXCEPT FOR the departmental sites.  They did not get provisioned with any of the custom content and do not inherit branding from the hub.  Have you heard of this issue?

 

Kind Regards,

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

**Comment by eoverfield** [comment]
@cheynen Expected behavior for a new dev tenant. With a new dev tenant, you will need to enable targeted release, which will take about 24 hours to fully propagate.

Regarding the issue with the department sites, I suggest you start a new issue and provide more details if possible.

**Comment by cheynen** [comment]
Thank you, will do.  

 

 

Carolee A. Heynen

Cell: +1 616.516.6739

 <mailto:carolee.heynen@gmail.com> carolee.heynen@gmail.com 

 

 <http://www.facebook.com/caroleeheynen> . <http://www.linkedin.com/in/caroleeheynen> .

**Comment by 88naveen** [comment]
![image](https://user-images.githubusercontent.com/37876354/52149887-2fae9100-2666-11e9-9724-a91ec0aebb3a.png)

**Comment by 88naveen** [comment]
I cant change the contoso to MSFT or any other stocks

**Comment by eoverfield** [comment]
Closing issue, solved via described expected behavior with a developer tenant that has been configured to requirements and the recommended time as transpired before installation of starter kit.
