### ISSUE TITLE
Can not see banner web part 

### ISSUE THREAD

**Issue by mukeshhope** [SharePoint/sp-starter-kit#270]
Hi Team,

I was trying to the webparts given in starter kit. but it looks like banner webpart is missing.
please note that other webparts are available.
Please have a look on attached image.
![image](https://user-images.githubusercontent.com/18657453/55856071-d3488000-5b86-11e9-8aa1-215a92f9af68.png)

Steps to reproduce :  
I added sharepoint-starter-kit.sppkg in my app catalog and i can see other webparts but banner webpart is missing.

Please suggest.

**Comment by mukeshhope** [comment]
Hi Team,

Please let me know if did not properly explained the question.
I am waiting for a reply from several days

Thanks,

**Comment by DeanGross** [comment]
I have the same issue, but

**Comment by dmitryrogozhny** [comment]
Hi @mukeshhope, @DeanGross,

The Banner web part is not available with the current version of the solution. I'm not aware of the reasoning behind that.

If you have an ability to rebuild the solution by yourself, you can make it available by modifying the [solution/src/webparts/banner/BannerWebPart.manifest.json](https://github.com/SharePoint/sp-starter-kit/blob/master/solution/src/webparts/banner/BannerWebPart.manifest.json) file. You'd need to change the `"hiddenFromToolbox": true,` value from `true` to `false`.

Probably, @VesaJuvonen can comment more on that as he has committed that change [https://github.com/SharePoint/sp-starter-kit/commit/1bd7600735bacfa96f838ca752f685593c744ce9#diff-bfcafc8f333e4d19dc74329b830a1b8d](https://github.com/SharePoint/sp-starter-kit/commit/1bd7600735bacfa96f838ca752f685593c744ce9#diff-bfcafc8f333e4d19dc74329b830a1b8d).

**Comment by dmitryrogozhny** [comment]
In addition to my previous comment: 
I don't know the reason, but my guess is that the Banner web part has been deprecated. That is why it has been hidden.

The standard Image web part provides almost the same functionality. The Image web part lacks the parallax effect, but its look is more in line with the overall style of communication sites.

As a confirmation for this assumption, the current version of a home page that got provisioned contains 3 Image web parts at the bottom, where 3 custom Banner web parts were previously.

BTW, the same is with the custom Weather web part - it has been hidden as the standard Weather web part is now available.

**Comment by bcameron1231** [comment]
Hi, yes the following contributions to this issue are correct. As mentioned, if you want to use this web part, you could set 'hiddenFromToolbox' to false.  

Thanks!
