### ISSUE TITLE
Portal Footer, disappears after navigating away

### ISSUE THREAD

**Issue by Bart2s4** [SharePoint/sp-starter-kit#272]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

After installing portal footer, navigating away from the  Hub (Communication Site) to another  site, then navigating back to Hub, the portal footer should still be visible. Also if  different "parameters" are installed on other "Hubs" or "Comm Sites", these should be retrieved and when going back and forth each time the portal footer should be refreshed by the application not manually by refreshing the browser.

#### Observed Behavior

On load the  portal footer  is visible
Navigating away to another site collection and then to another communication site "without" a portal footer, when going back to  Hub (with portal footer) the "Portal Footer" is missing.

#### Steps to Reproduce

Install PNP-StarterKit
Create a new "Communication Site"
Open portal from starterkit (Notice the portal footer is visible)

![image](https://user-images.githubusercontent.com/47592514/56016794-b1253e00-5cfd-11e9-8136-f385baaa724f.png)

Click on new communication site, (without portal footer installed) and promote to Hub

![image](https://user-images.githubusercontent.com/47592514/56016931-10834e00-5cfe-11e9-83cc-3ef65aa1d710.png)

(Footer is missing, but this is correct, since extension was not deployed to this site collection)

Navigate back from "link in hub" to the default portal (hub) generated by the PNP starterkit

![image](https://user-images.githubusercontent.com/47592514/56017119-9d2e0c00-5cfe-11e9-94bb-8bc07cd22e0e.png)

(Notice now, the portal footer is not loaded)

Fix:

Reload whole page with the browser-refresh button

![image](https://user-images.githubusercontent.com/47592514/56017234-f138f080-5cfe-11e9-9e08-1d809ff15d5f.png)

It looks like the  application only "works" in one site collection with the pages, but when navigating away to other  "sites" you have to refresh the browser to restore the portal.

**Comment by bcameron1231** [comment]
This should be fixed with PR #282 . Please test and if you are still having issues could you open another issue?
