### ISSUE TITLE
Portal Footer availabe on First Hub site only

### ISSUE THREAD

**Issue by Luksharp** [SharePoint/sp-starter-kit#273]
#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

Since it is my first time posting on this website and if i am not following any protocols apologies in advance.

#### Observed Behavior

Followed instructions step by step, created everything empty demo O365 account. 

Creates everything as it's supposed to, no reported issues. No permissions nothing.

First hub site gets the footer, any consequent website does not.

I am able to enable collab footer with powershell on subsequent sites but can't do anything with portalfooter. Any suggestions or powershell command to run?

Thanks

**Comment by bcameron1231** [comment]
The Portal Footer was only installed on the main hub site collection.

Two site designs get provisioned with this solution. One for Communication Sites and one for Team sites. The team sites use the collab footer, communication sites use the portal footer.

This can be changed if you want to update the site designs. Here is some documentation on how site designs and site scripts work. https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview

If you would like the portal footer on the team sites, instead of the collab footer, just update the site script that belongs in the site design. 

Here is the current team site - site script

```
{
    "$schema": "schema.json",
    "actions": [
        {
            "verb": "joinHubSite",
            "hubSiteId": "<THIS IS YOUR HUBSITE ID>"
        },
        {
            "verb": "associateExtension",
            "title": "Collab Footer",
            "location": "ClientSideExtension.ApplicationCustomizer",
            "clientSideComponentId": "c0ab3b94-8609-40cf-861e-2a1759170b43",
            "clientSideComponentProperties": "{\"sourceTermSet\":\"PnP-CollabFooter-SharedLinks\",\"personalItemsStorageProperty\":\"PnP-CollabFooter-MyLinks\"}",
            "scope": "Site"
        }
    ],
    "bindata": {},
    "version": 1
}
```
You'll want to modify it to look like this

```
{
    "$schema": "schema.json",
    "actions": [
        {
            "verb": "joinHubSite",
            "hubSiteId": "<THIS IS YOUR HUBSITE ID>"
        },
              {
            "verb": "associateExtension",
            "title": "Portal Footer",
            "location": "ClientSideExtension.ApplicationCustomizer",
            "clientSideComponentId": "b8eb4ec9-934a-4248-a15f-863d27f94f60",
            "clientSideComponentProperties": "{\"linksListTitle\": \"PnP-PortalFooter-Links\", \"copyright\": \"(c) Copyright {parameter:Company}, 2018\", \"support\": \"support@contoso.com\", \"personalItemsStorageProperty\": \"PnP-CollabFooter-MyLinks\"}",
            "scope": "Site"
        }

    ],
    "bindata": {},
    "version": 1
}
```

To modify the site scripts, using PowerShell (shown in the documentation above), you'll use the following commands to get the site scripts and subsequently update the site script.

Get-SPOSiteScript
Set-SPOSiteScript

After doing so, all new sites you create from  SharePoint home, will have the portal footer.

**Comment by Luksharp** [comment]
Thank you @bcameron1231 

All i want is other communications sites to get portal footer as well but they don't. However if i apply Contoso teamsite template collab footer applies successfully.

Is there any way to create separete/standalone communications sites, apply contoso communications site template and have the footer?

Thanks

**Comment by bcameron1231** [comment]
By default, the Portal Footer is only installed on the main hub site collection. Two site designs get provisioned with this solution. One for Communication Sites and one for Team sites. The team sites use the collab footer, communication sites use the portal footer.

When you create a new communication site from SharePoint Home (sharepoint.aspx) using the Site Design provisioned with the Starter Kit, it should automatically add the Portal Footer to your sites.

Alternatively, if you have a site create already, you apply the site design. 

The site design is named {Company} Communication Site.

**Comment by Bart2s4** [comment]
@Luksharp , you can use the powershell comment to add the "custom-action" to another "Communication Site". You first need to  "retrieve" the identifier of the existing "sharepoint extensions" by running the command on the HUB site you created automatically with the starter kit:

> Get-PnPCustomAction

Next find the id which  has the name "PortalFooter" and copy the "ClientsComponentId"

Now connect to the communication site you created from the template and run the following command:

> Add-PnPCustomAction -Name "PortalFooter" -Title "PortalFooter" -ClientSideComponentId <"enter your id here"> -Location "ClientSideExtension.ApplicationCustomizer"

Note however i have reported a bug, that if you navigate away from another communication site with a footer, it is not automatically reloaded, see the bug report i have uploaded, but this is a solution to add the portal footer to another communication site.

Bart

**Comment by Sunni-B** [comment]
@Bart2s4 I can't seem to add the portal footer to any other sites. When I create a new site with the communications template, the footer doesn't load. I followed your instruction but it still doesn't load. I can see it when I do Get-PnPCustomAction, but it doesn't work. I only works on the first site I deployed.

**Comment by Sunni-B** [comment]
BTW, I've tried this on two different tenants

**Comment by Bart2s4** [comment]
@Sunni-B are you using the communication template from the starterkit and your default language of the site you want to deploy is English? Then it should work, however it is a bit buggy, when navigating to another site. Also the footer uses an "list" for all the other data, so you also need to duplicate that list on the first portal.

Off course you need to connect to the site where you want to deploy this footer (must be a communication Site).

So first connect-pnponline -url <communicationsite>

Check with Get-PnPCustomAction which "Extensions" are installed.

If you do not see the extension "PortalFooter", you first need to add this extension.

The client component ID, is NOT de id , you need to use this command:

> Get-PnPCustomAction | Select Name, ClientSideComponentId

Then find the "ClientSideComponentId" 

You can also find this id in the "starterkit.xml" file

If you now add this component, you will sure get the portal footer.

Bart

**Comment by Bart2s4** [comment]
You are probably missing all the "ContentTypes" en "Lists" needed for the portal footer, if you do not have those then it will not work.

You need the list "PnP-PortalFooter-Links" with the exact columns and content type (PnPPortalLink) used for this list.

**Comment by Sunni-B** [comment]
I finally got the footer to show up on another hub site, but without the links. I think there was an error in the content types as you suggested. But as I tried to fix that, the footer stopped loading again and I can't seem to figure out how to get it back. It still works great on my originally deployed site. I think the navigation bug is complicating my testing.

**Comment by Bart2s4** [comment]
Yes I agree, sometimes it disappears, so you have to reload. I therefor only use it for the "main hub" all other navigations I use the "collab-footer", this one works fine on all sites and with a simple adjustment you can have separate "fields" for different hubs. You manage those at the term store.

**Comment by bcameron1231** [comment]
Is this still an issue for you? Would love to close out this issue if it's no longer an issue for you.
