### ISSUE TITLE
pply-PnPTenantTemplate: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by tomobak** [SharePoint/sp-starter-kit#275]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Provision three sites without error.

#### Observed Behavior
Successfully provisioned with dev environment using Apply-PnPTenantTemplate -Path starterkit.pnp.  However, getting error "Apply-PnPTenantTemplate: Object reference not set to an instance of an object" when trying to provision on prod tenant.
Verified all prerequisites were done, use Tenant Admin id, run command from provisioning folder, have full access right to tenant app catalog etc., but still getting the same error message "Apply-PnPTenantTemplate: Object reference not set to an instance of an object".

#### Steps to Reproduce
We could successfully provisioned in dev environment using same client machine but getting above error only when try to do it in production tenant, so we are not sure how to reproduce.

**Comment by eoverfield** [comment]
@tomobak could you provide any additional insight into the difference between your dev and production tenants? Are they using the same type of authentication?

**Comment by tomobak** [comment]
Hello, yes we use the same type of authentication on dev and prod tenants.  There is a difference that on the production site we have to go through PIM to get GA access so we don't know if it is something to do with policy.  But we have not changed any default settings.  Thank you for your help in advance.

**Comment by tomobak** [comment]
Hello, we just found out our tenant has LegacyAuthProtocolsEnabled as False and failing authentication with "Connect-PnPOnline".  We need to either turn on this LegacyAuthProtocolsEnabled as true or change the starter kit code to do modern authentication.  This might be the reason why we cannot do -Apply-PnPTenantTemplate.  We can close this issue for now.
