### ISSUE TITLE
Apply-PnPTenantTemplate : A task was canceled.

### ISSUE THREAD

**Issue by mgmjtech** [SharePoint/sp-starter-kit#277]
#### Category
- [ ] Question
- [ x] Bug
- [ ] Enhancement

Version - SharePointPnPPowerShellOnline 3.8.1904.0
Apply-PnPTenantTemplate -Path starterkit.pnp
Errors:
Apply-PnPTenantTemplate : A task was canceled.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], TaskCanceledException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

Debug:
powershell.exe Information: 0 : 2019-04-29 10:51:43.1961        [OfficeDevPnP.Core]     [0]     [Information]   File starterkit.pnp retrieved from folder    0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.2547        [OfficeDevPnP.Core]     [0]     [Information]   File starterkit.pnp retrieved from folder    0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.6044        [OfficeDevPnP.Core]     [0]     [Information]   File starterkit.xml retrieved from folder    0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.7320        [Provisioning]  [14]    [Debug] Code execution scope started    0ms     6a3cc406-cdb6-40a7-9d3f-bb4aa1b1fc64
powershell.exe Information: 0 : 2019-04-29 10:51:43.7325        [Provisioning]  [14]    [Information]   ProgressDelegate registered     0ms     6a3cc406-cdb6-40a7-9d3f-bb4aa1b1fc64
powershell.exe Information: 0 : 2019-04-29 10:51:43.7330        [Provisioning]  [14]    [Information]   MessagesDelegate registered     1ms     6a3cc406-cdb6-40a7-9d3f-bb4aa1b1fc64
powershell.exe Information: 0 : 2019-04-29 10:51:43.7425        [OfficeDevPnP.Core]     [0]     [Information]   File resources\resources-core.en-us.resx retrieved from folder       0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.7430        [OfficeDevPnP.Core]     [0]     [Information]   File resources\resources-core.es-es.resx retrieved from folder       0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.7435        [OfficeDevPnP.Core]     [0]     [Information]   File resources\resources-core.fr-fr.resx retrieved from folder       0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.7445        [OfficeDevPnP.Core]     [0]     [Information]   File resources\resources-core.de-de.resx retrieved from folder       0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.7455        [OfficeDevPnP.Core]     [0]     [Information]   File resources\resources-core.nl-nl.resx retrieved from folder       0ms
powershell.exe Information: 0 : 2019-04-29 10:51:43.7556        [Tenant Settings]       [14]    [Debug] Code execution scope started    0ms     6a3cc406-cdb6-40a7-9d3f-bb4aa1b1fc64
powershell.exe Information: 0 : 2019-04-29 10:51:45.1717        [OfficeDevPnP.Core]     [0]     [Information]   File sharepoint-starter-kit.sppkg retrieved from folder ..\package   0ms
powershell.exe Information: 0 : 2019-04-29 10:53:59.3208        [Tenant Settings]       [14]    [Debug] Code execution scope ended      135568ms        6a3cc406-cdb6-40a7-9d3f-bb4aa1b1fc64
powershell.exe Information: 0 : 2019-04-29 10:53:59.3218        [Provisioning]  [14]    [Debug] Code execution scope ended      135593ms        6a3cc406-cdb6-40a7-9d3f-bb4aa1b1fc64

I checked my app catalog and I do see that SharePoint-starter-kit deployed.

**Comment by mgmjtech** [comment]
any suggestions?

**Comment by IK2019** [comment]
I had worked with starter kit before but from last one week, I am not able to deploy the starter kit if any modifications are made.

Error : Apply-PnPTenantTemplate : A task was canceled.

Steps : 
$kit = Read-PnPTenantTemplate -Path .\starterkit.xml
Save-PnPTenantTemplate -Hierarchy $kit -Out starterkit.pnp
Apply-PnPTenantTemplate -Path starterkit.pnp

If I clone a new copy and deploy, it works well. Any change to starter kit would cause the error.

**Comment by mgmjtech** [comment]
clone works. Deploy with no error. Thanks!

**Comment by bilalkhan870** [comment]
i am facing the same issue on my tenant ?
