### ISSUE TITLE
Solution Version

### ISSUE THREAD

**Issue by DeanGross** [SharePoint/sp-starter-kit#279]
#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

#### Observed Behavior
the app catalog is showing me version 1.3.0.0, what version should be shown?

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
The latest solution should show as v 1.5.0.0 in the app catalog. Did you pull the latest commits from the master branch?

**Comment by DeanGross** [comment]
No, i just used the site at https://provisioning.sharepointpnp.com/ and followed the instructions

**Comment by bcameron1231** [comment]
Closing - Answered.
