### ISSUE TITLE
App Package not working

### ISSUE THREAD

**Issue by albandrod** [SharePoint/sp-starter-kit#28]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Some time ago, I configured my tenant in First Release, I am able to see the API management, and I have uploaded the .sppag package to the App catalog. It shows no errors, but when I create wether a classic or a new TeamSite, I am not able to add the app to test the new WebParts shown in the video

#### Observed Behavior
Some time ago, I configured my tenant in First Release, I am able to see the API management, and I have uploaded the .sppag package to the App catalog. It shows no errors, but when I create wether a classic or a new TeamSite, I am not able to add the app to test the new WebParts shown in the video

#### Steps to Reproduce

Tenant configures in FR
API in new SPO portal is showed
App uploaded to the App Catalog

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by robertcaretta** [comment]
20180619 - I'm having issues deploying the sharepoint-starter-kit package as well. I provisioned a new office developer tenant, set up the app site collection, then uploaded the .sppkg file found in the repo "package" directory. The app package error message is "Error in the application".

![capture](https://user-images.githubusercontent.com/1613085/41615306-802f0528-73c0-11e8-8caf-263b7933918b.PNG)

**Comment by eoverfield** [comment]
Stale issue, closed. Described solution should address issue.
