### ISSUE TITLE
Collaboration Footer Application Customizer - Term Store related links not show

### ISSUE THREAD

**Issue by selvaag** [SharePoint/sp-starter-kit#280]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
NA

#### Observed Behavior
The Collaboration Footer Application with links from TermSets is not showing up. Only the My Links from User Profiles is visible. The Term Store has been populated with values but not shown in the Footer.

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Are you able to take a screenshot of your term store? Just to make sure it's pulling from the right group.

**Comment by bcameron1231** [comment]
Can you confirm my previous comment on your term store?
Is this still an issue for you?

If this isn't an issue for you anymore, we'd like to close out this issue.
