### ISSUE TITLE
V1.5.2.0 Portal Footer does not display correctly

### ISSUE THREAD

**Issue by tomobak** [SharePoint/sp-starter-kit#284]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Portal Footer bar shows up one row high with Copyright text on the left, Support contact in the middle and expansion arrow on the right in the bar.

#### Observed Behavior
The current version of portal footer now about three rows high and all contents are aligned left.

#### Steps to Reproduce
Deploy v1.5.2.0 package to app catalog.  Clear the cache.

#### Submission Guidelines
If you add a certain webpart, clear cashe, it started recognizing css and make footer look like as it should be.
There is no work around for like list view or site content as webpart cannot be added there.

v1.4.0.0 does not have this issue.

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, this has been fixed with PR #335. The changes have been merged in to Dev will show up in the next release.
