### ISSUE TITLE
Dead Link (SharePoint Starter Kit)

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-starter-kit#286]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When click "[term set provisioning may be modified to assist with installation](https://sppnpprovisioningapp.blob.core.windows.net/templates/tenant/SP-Starter-Kit/documentation/term-store.md#non-english-tenants)." should show configuration

#### Steps to Reproduce
Go to SharePoint Starter Kit ans scool down to Prerequisites
[Here](https://provisioning.sharepointpnp.com/home/details?packageId=5c3f13eb-e7c0-4d71-8154-d33dee71356d)

Reproduce Expected or Desired Behavior

**Comment by bcameron1231** [comment]
This will be fixed in the next release. Thanks!
