### ISSUE TITLE
failed to save my links

### ISSUE THREAD

**Issue by pik10** [SharePoint/sp-starter-kit#287]
#### Category
- [ ] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Save footer links.

#### Observed Behavior

I get an error message when trying to save new links in the footer. 
Failed to save my links!

#### Steps to Reproduce

Expand the footer.  Click on Edit.  In the My Links window add a new link.  Click on Save.  
I get an error message Failed to save my links! The new link is not saved.

![footerlinks](https://user-images.githubusercontent.com/24878616/59207238-ac9dca00-8b74-11e9-9211-46ad8af057ed.png)

**Comment by Bart2s4** [comment]
As a work-a-round,  you can first edit a link in a "collaboration" site, it seems that it happens only on the portal footer extension and  for the first personal link. 
Another solution is to add a value for all "users" in the user-profile parameter (you need to be a SharePoint admin to do this last solution.

**Comment by pik10** [comment]
How do I edit a link in a "collaboration" site? 
Where do I add a value for all "users" in the user-profile?
Do you have some instructions? Thank you.

**Comment by Bart2s4** [comment]
If you use the PnP starterkit, you can open a "collaboration" site, bij choosing one of the default departments: for example the HR department. You will notice that the "footer" is a bit different, but also has a "Mylinks". Click on this "MyLinks" and add a new link. After you have successfully added this link, the link is also visible on the  portal page and now you can edit this link on the portal page.

![image](https://user-images.githubusercontent.com/47592514/59279045-899e1380-8c63-11e9-8e0d-9a927ccecff3.png)

**Comment by pik10** [comment]
The footer does not have Mylinks.  I realized that I didn't add the user profile property. I will try to add it.
![Annotation 2019-06-11](https://user-images.githubusercontent.com/24878616/59282375-cef81c00-8c36-11e9-8fa2-76819f30244e.jpg)

**Comment by Bart2s4** [comment]
Make Sure the name is exactly as the instruction, because this name is hardcoded linked to the extension, including capital letters

**Comment by pik10** [comment]
Now my links are working. Thank you.
