### ISSUE TITLE
Edit Footer Groups

### ISSUE THREAD

**Issue by JOE5117** [SharePoint/sp-starter-kit#288]
- [x] Question
- [ ] Bug
- [ ] Enhancement

![image](https://user-images.githubusercontent.com/51747144/59349436-a4b26700-8ce7-11e9-9df9-855c5ee8314e.png)
 
I am not able to figure out how to edit the groups in the footer list.  I would like to change there names to somthing else.  I am new to this.

TY

**Comment by eoverfield** [comment]
There are a few methods to make this change.

1. The easy way, edit a given list item in the PnP-PortalFooter-Links list. You will find a dropdown field, PnPPortalLinkGroup, that also allows for new custom values. If you add a new group name, that will appear in the list view and be used elsewhere.

2. This field is being driven by a Content Type, PnPPortalLink, found in the Content Type Group, "PnP Content Types". You could update the site column there, just ensure that updates get applied to lists already using the content type.

**Comment by JOE5117** [comment]
Got it working thanks for the guidance.
