### ISSUE TITLE
People Directory Syncing

### ISSUE THREAD

**Issue by bwarring24** [SharePoint/sp-starter-kit#290]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

After updating on-premise Active Directory with updated employee information the People Directory doesn't seem to sync up with Azure Active Directory and pull the new employee information. Is the people directory caching the query for a specific amount of time? The only way I've found to get the directory to update was through re-deploying the templates. It be nice to have just a manual sync button when editing the web part.

**Comment by bcameron1231** [comment]
Thank you for the question. There isn't a "sync" per se that happens with the people directory. The People Directory uses the SharePoint Search "People" Result Source. When you synchronize your on-premises AD to Online, there is a time period to update the User Profiles in SharePoint. Subsequently, the profile values are then put into the Search Index in SharePoint.

Long Story Short, There may be a delay as a result... unfortunately, this delay is not something we can specifically control.
