### ISSUE TITLE
Portal Footer Cant remove

### ISSUE THREAD

**Issue by JOE5117** [SharePoint/sp-starter-kit#292]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

Portal footer still appears after i have removed the custom action from the site collection.

![image](https://user-images.githubusercontent.com/51747144/59464791-60ae8780-8df7-11e9-821e-8d80b85e4a3a.png)

![image](https://user-images.githubusercontent.com/51747144/59464749-44124f80-8df7-11e9-8f35-fb46c5913622.png)

Prior to this happening i removed the footer to edit and then readded footer.  Was working fine until i added a new site page.  After adding site page footer appeared with two lines in it.

The default line on top and my custom footer below it with a single entry for the footer in custom actions.  I when through and removed custom action but the default footer still remains and i cant find an entry for it anywhere.

![image](https://user-images.githubusercontent.com/51747144/59465251-78d2d680-8df8-11e9-920a-f959ecd2552b.png)

**Comment by awvala** [comment]
I am receiving this error as well. In addition, One of my associated hub sites is displaying the collab Footer in addition to the portal Footer.  This occurred after switching the Site Design from Collaboration to Teams in an attempt to clear the duplicate portal footers.

**Comment by pik10** [comment]
After I uploaded the sharepoint-starter-kit.sppkg version 1.5.3.  the footer is duplicate.  I removed the footer from the hub communication site using the command Remove-PnPCustomAction -Identity "PortalFooter" the footer is not removed from other associated communication sites.

**Comment by bcameron1231** [comment]
@pik10 You would need to execute the command on all sites where the footer was loaded. Removing the footer from the hub site, would not remove it from the associated sites.
