### ISSUE TITLE
Recently used docs: last accessed "undefined"

### ISSUE THREAD

**Issue by webbrewer** [SharePoint/sp-starter-kit#294]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

"Last accessed" field would show date logged in user opened doc 

#### Observed Behavior

Output renders as `<span class="ms-DocumentCardActivity-activity activityActivity_0d598d25">Last accessed: undefined</span>`

#### Steps to Reproduce

Add recently used docs web part to a page

``

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, I am unable to reproduce this issue. Could you try with the latest starter kit and let me know if your issue is resolved?

Also, if this issue no longer applies to you, would you mind closing it?

**Comment by webbrewer** [comment]
Thanks - no longer an issue - closing.
