### ISSUE TITLE
Upgrade Instruction 

### ISSUE THREAD

**Issue by shemp321** [SharePoint/sp-starter-kit#295]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

I need to upgrade from version 1.3 to the latest version to solve some bug issues.  Are there instructions to complete this?  Please let me know.  Thanks.

**Comment by pik10** [comment]
I am looking for upgrade instruction also.  I want to upgrade the existing starter kit to a new version.

**Comment by bcameron1231** [comment]
Are you looking to just upgrade the web parts? You can download the solution and upload the .sppkg file into your environment's app catalog.

**Comment by shemp321** [comment]
Thanks for the info.  I figured this out as being the solution.  It worked well.  Thanks again!

**Comment by pik10** [comment]
> Are you looking to just upgrade the web parts? You can download the solution and upload the .sppkg file into your environment's app catalog.

I am looking to update changes to the starter kit.  I see that there are some changes to the footer code.  If I upload the solution .sppkg will it update any code changes?

**Comment by bcameron1231** [comment]
Yes they will.

**Comment by bcameron1231** [comment]
Closing - Answered and Confirmed by Author
