### ISSUE TITLE
How to add new Team Sites?

### ISSUE THREAD

**Issue by SSorennaa** [SharePoint/sp-starter-kit#298]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

I am trying to modify starterkit.xml to add 3 more team sites. As @erwinvanhunen explained in this video: PnP Webcast - Introduction to PnP Tenant Templates, I modified the xml file, and saved it as a new .pnp file. However, when I am trying to apply it, I am getting an error as below: 

Message: {"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"41caf2ed-db30-4b5d-bd0d-f46e7b007d8a","SiteStatus":1,"SiteUrl":null}

Is there something else that I need to change/add? There is not any hierarchy.json to modify. Thank you for the help. 

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, I noticed this was an old ticket, and I'm just checking to  see if you found a solution ,or if you no longer need support on this.  If so, we'll close the ticket. Thanks!
