### ISSUE TITLE
sp-starter-kit provisioning error

### ISSUE THREAD

**Issue by sctdan** [SharePoint/sp-starter-kit#300]
I'm not able to get the sp-starter-kit provisioned.  

Pre-reqs should be fine (I was able to install O365 Custom Learning a couple weeks ago).
-My account is tenant admin
-App catalog exists, tenant admin set as primary owner
-Tenant admin set as Term store administrator
-release preferences for tenent are correct

----

Unfortunately, your request to provision
"SharePoint Starter Kit" 
template failed.

`Here is the exception that occurred:
Type = System.Exception Message = {"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"8afe30f0-3447-4d2d-9c88-8f35bc30c259","SiteStatus":1,"SiteUrl":null} Source = OfficeDevPnP.Core TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.Sites.SiteCollection.<CreateAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at OfficeDevPnP.Core.Sites.SiteCollection.Create(ClientContext clientContext, TeamSiteCollectionCreationInformation siteCollectionCreationInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser tokenParser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation applyingInformation) at SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext() in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line 388 HResult = -2146233088`

`PnP Correlation ID: 3f23c29e-f727-45fd-869d-88f35541bb76`

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

**Comment by bcameron1231** [comment]
Hi, thank you for the issue. I realize this is an older issue and it may not be an issue for you anymore. We are working on cleaning up the issues list, does this still apply to you? If so, could you create a new issue in the issues list. Thanks!
