### ISSUE TITLE
Package is not working in Sharepoint 2019 on prem

### ISSUE THREAD

**Issue by pdhameliya** [SharePoint/sp-starter-kit#302]
#72 ## Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

This solution perfectly working fine in my tenant, I would like to deploy solution in SP on prem.  
I am new in SPFx development but downloaded sharepoint-starter-kit.sppkg and tried to deploy in on SP 2019, it didn't work. So I tried to downloaded the source code and bundle it again. I upload the sharepoint-starter-kit.sppkg but solution not deployed and generic error "Error in the application". 
Please provide steps to use source code in SP 2019 onPrem. 
![onPremError](https://user-images.githubusercontent.com/48958309/61243229-804a1000-a715-11e9-9721-0d7bb4e65282.PNG)

**Comment by eoverfield** [comment]
@pdhameliya This solution is not designed for onprem. Among a handful of the webparts that will not work on prem, the project also includes a hub site which is also not supported, as well as other components and settings.

You could reference the source and strip out many of the webparts, placing the source code directly into your own new SPFx solution for SP2019. You might run into roadblocks around SPFx versions, it would take some time, yet is definitely possibly.

As for the provisioning template itself, That would take more work. Much of the PnP Provisioning Template would have to be stripped down as well.

For now there are no specific instructions I have seen getting compatible parts of this project to work on prem, nor am I aware of it being on a roadmap.

**Comment by pdhameliya** [comment]
Thank you for quick reply. I would be fine to strip out couple of web parts like Tiles, weather etc. and some extensions

**Comment by pdhameliya** [comment]
@eoverfield Let say If I strip out webparts and keeping the same solution name and deploy. will it be smooth upgrade if SPFx updated in SharePoint 2019?

**Comment by eoverfield** [comment]
The solution name itself is not as important than the solution id, and the id's of the underlying components. That being said, I would not attempt to re-use the solution or component ids from this project in a custom built package.

Unfortunately I do not see a smooth upgrade from any customized SPFx package to an updated StartKit package, if it were ever upgraded to work with SP2019.

My suggestion, if you are looking to use some of the webparts found in this project, copy the component codebase you are interested in over to your own new SPFx project and assume you will have to maintain those moving forward.

**Comment by bcameron1231** [comment]
If interested, you could try out this repo. When the starter kit first came out, it was SPFx 1.4.1 (A supported SPFx version for 2019).  I removed all of the Personal Web Parts (the ones that use Microsoft Graph & Office 365 services).

Be aware: I haven't tested this on-premises, and I haven't maintained this since June of last year. So there may be bug fixes / enhancements that aren't included in this solution.

https://github.com/bcameron1231/PnP-Starter-Kit-Non-FR

Otherwise, as @eoverfield mentioned, if you are only going to use a couple of the web parts, you should probably start your own SPFx Solution and port over the code from the starter kit.

**Comment by bcameron1231** [comment]
Closing as this has been answered.
