### ISSUE TITLE
Personal Calendar -  Retrieving your upcoming meeting

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-starter-kit#308]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Personal Calendar to show upcoming invites

#### Observed Behavior

I just updated to the latest package file as i saw that it had local timezone support - previously the webpart was working OK, other webparts such as tasks work OK. It just sits and spins on 
Retrieving your upcoming meeting.

There are no outstanding API approvals.

**Comment by manhhdt97** [comment]
Hi @gristy58, i have the same issue, could you guide me how do you resolve this bug?
