### ISSUE TITLE
SP Starter Kit - Hyperlink field value not resolving value like {site}/SiteAssets/contoso_sitelogo.png

### ISSUE THREAD

**Issue by pk091990** [SharePoint/sp-starter-kit#309]
In the current xml, Hyperlink  field i.e. "PnPPortalLinkUrl" value is passing like a normal url i.e. https:\\

![image](https://user-images.githubusercontent.com/46436213/61773383-30a0ce00-ae12-11e9-8bea-8f360137b0d9.png)
I need to pass a image url from site ->Site Assets folder and page url from site-> Site Pages in PnPPortalLinkUrl field.
Earlier I used to pass like in  **{site}/SiteAssets/contoso_sitelogo.png** format. However this is not working now.

![image](https://user-images.githubusercontent.com/46436213/61773648-ce949880-ae12-11e9-9913-76352fcd3cd5.png)

![image](https://user-images.githubusercontent.com/46436213/61773535-86757600-ae12-11e9-80ae-b0ca93d3887b.png)

I've tried with multiple ways like {site}, {sitecollection}, {sitecollection}/SiteAssets/... but kit is just skipping that Datarow . Is there any change from your end or anyother way to implement it as it was working earlier. Please help !

**Comment by bcameron1231** [comment]
Hi. We are working through many of the issues on this list. Can you confirm if this still an issue for you, or if this ticket can be closed?
