### ISSUE TITLE
API Management Requests

### ISSUE THREAD

**Issue by LouFarho** [SharePoint/sp-starter-kit#31]
#### Category
- [ x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Approve API Management Requests 

#### Observed Behavior

After execution of the deploy script, I later noticed I had several entries in the API Management page. 
Was the script supposed to handle the Approval of these requests or is this a step that needs to be identified in the Read Me?

After noticing the entries, I tried to Approve them but they would error.

#### Steps to Reproduce
Review API Management after execution of the deploy script.

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
The script does not approve these automatically. They are required for the Graph integrated capabilities. What was the exception for the approval? - You can also try to get them approved with PowerShell, which will give you more descriptive exception messages.

**Comment by andreasblueher** [comment]
Hey Vesa, he is most likely talking about https://github.com/SharePoint/sp-starter-kit/issues/5#issuecomment-395430316 which haven't been reported in a separate issue yet.

**Comment by LouFarho** [comment]
@andreasblueher It is not the same as #5 I had deployed the package to the app catalog.

When I go to the API Management, I get errors on most of the requests. I have had only one get approved. This happened in my DEV Tenant as well as a Quasi-Production Tenant (We got acquired so the tenant will be shutdown soon).

Screenshot attached
![image](https://user-images.githubusercontent.com/20116742/41538908-fb2cce9e-72d1-11e8-880b-391a5de4e751.png)

**Comment by LouFarho** [comment]
Here is the output from trying to approve all the API requests. All these requests were generated from the deploy command. This has only been executed once in the Tenant.
It logs the currently approved request, the current version of PnP PowerShell, all the API request, and finally the output from trying to approve them. Let me know if there is anything else I should check.
[PowerShellLog.txt](https://github.com/SharePoint/sp-starter-kit/files/2111841/PowerShellLog.txt)

**Comment by bcameron1231** [comment]
Going to have a guess it has to do with the LOB-Application Registration in Azure, which looks to use a custom permission scope for the API and that application + the corresponding principal w/custom scope doesn't exist in the AAD?

**Comment by eoverfield** [comment]
The SPFx-LOB... AAD apps are not yet fully included with the project. I believe @PaoloPia is working on this but I could be wrong. I suggest you leave these two pending requests alone for now, or at least until further documentation is provided.

As for the "already exists" messages, I have seen those as well and do not know what is causing them. I leave them alone as well, often those additional pending requests will disappear on their own after a few hours. As long as the approved section includes the Microsoft Graph permissions, you should be set.

**Comment by LouFarho** [comment]
@eoverfield All of mine are still there. They didn't go away after 5 days. I will ignore the SPFx until further notice.

**Comment by eoverfield** [comment]
The API Management page appears to have gone through a series of updates and appears to be more reliable. Closing this issue as it should now have been addressed directly by management page updates.
