### ISSUE TITLE
SP Starter Kit - Hyperlink field not resolving value like {site}/SiteAssets/contoso_sitelogo.png

### ISSUE THREAD

**Issue by pk091990** [SharePoint/sp-starter-kit#310]
This issue is related to provisioning of [SP Starter KIt](https://github.com/SharePoint/sp-starter-kit/tree/master/provisioning)
In the starterkit.xml, Hyperlink field i.e. "PnPPortalLinkUrl" value is passing like a normal url i.e. https:\

![image](https://user-images.githubusercontent.com/46436213/61782154-32bf5880-ae23-11e9-9f67-4267733acaad.png)

I need to pass a image url from site ->Site Assets folder and page url from site-> Site Pages in PnPPortalLinkUrl field.
Earlier I used to pass like in {site}/SiteAssets/contoso_sitelogo.png format. However this is not working now.

![image](https://user-images.githubusercontent.com/46436213/61782168-39e66680-ae23-11e9-850d-5ef86009b459.png)

![image](https://user-images.githubusercontent.com/46436213/61782188-423ea180-ae23-11e9-854c-1f7f6dd9f6ee.png)

I've tried with multiple ways like {site}, {sitecollection}, {sitecollection}/SiteAssets/... but kit is just skipping that Datarow . Is there any change from your end or anyother way to implement it as it was working earlier. Please help !

**Comment by bcameron1231** [comment]
Closing. Duplicate #309
