### ISSUE TITLE
Sp-Starter-Kit | Portal Footer Not Appearing | Error: Failed to create application customizer...

### ISSUE THREAD

**Issue by JakeDuq** [SharePoint/sp-starter-kit#311]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

The portal footer should load on every page every time i go to that page.

#### Observed Behavior

All of the footers used to work perfectly until 2 weeks ago. Now the portal footer on the sub sites only load about 50% of the time. Normally refreshing the page will cause the footer to load again correctly, however this isn't always the case. The error that I receive in the developer tools is  Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.b8eb4ec9-934a-4248-a15f-863d27f94f60'. Error information is '***Extension failed to initialize for componentId "b8eb4ec9-934a-4248-a15f-863d27f94f60". All of the pages have the pnp-portalfooter-links list stored in it's site contents and all of these lists have at least one valid link in them. This is an error I am experiencing on all of my tenants, not just one so I am unsure what the issue is.

#### Steps to Reproduce

Provision the sp-starter kit like normal, use powershell to change the company name and the support email address. Use some css to hide the double up chevron (I have done this since the start and it hasn't caused any issues until now).

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, I realize this is an older ticket. We are currently going back through the issues list and trying to clean some things up. Is this still an issue for you?
