### ISSUE TITLE
PnP Power Shell install error

### ISSUE THREAD

**Issue by Plimmyri** [SharePoint/sp-starter-kit#314]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Question
If i wanna install the SharePoint PnP PowerShell, i get an message that i need to install "NuGet-anycpu.exe". If i want to install the package i get the message:  Unable to download from URI
'https://az818661.vo.msecnd.net/providers/nuget-anycpu-2.8.5.127.exe'.
Then they ask if i wanna install it manually, but i doesn't work either.

So my question is, what did i need to do, to install the NuGet for using the PnP Power Shell.

**Comment by eoverfield** [comment]
This looks like a PnP PowerShell issue that would be best addressed on the PnP PowerShell issue list.

https://github.com/SharePoint/PnP-PowerShell/issues
