### ISSUE TITLE
Icons does not display in peoples directory 

### ISSUE THREAD

**Issue by shwanthi** [SharePoint/sp-starter-kit#317]
I got the latest code and solution and added some properties to view in card in peoples directory. and bundled it and deployed. But i cannot view any of the fabric icons ?

Do u have any idea why>]?
 Screenshot 
![image](https://user-images.githubusercontent.com/16661859/64314026-dd18c700-cff0-11e9-87e9-5343d1feb879.png)

**Comment by ddmarsden** [comment]
I am also facing this issue.

**Comment by bcameron1231** [comment]
Hi, are you still facing this issue? Are you able to share the code you modified?
