### ISSUE TITLE
Errors with Webparts

### ISSUE THREAD

**Issue by Mgeslin** [SharePoint/sp-starter-kit#32]
- [x ] Bug
Hello, I installed the package for webparts on a Tenant FR. I have errors messages on several webparts as you can do on the screenshot. Is this normal?
![kit sharepoint](https://user-images.githubusercontent.com/40354267/41527850-b3bf6848-72e8-11e8-83aa-2b8d08f40d66.PNG)

**Comment by VesaJuvonen** [comment]
This indicates that you have not granted the permissions in the admin for the Graph scopes. You will need to go to new admin UI - chose API management from the left menu and approve scopes.

**Comment by Mgeslin** [comment]
Great, it works. thank you very much !!!!!!!!
