### ISSUE TITLE
Home page +Create missing!

### ISSUE THREAD

**Issue by dgiles53** [SharePoint/sp-starter-kit#322]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Observed Behavior
I used the https://provisioning.sharepointpnp.com/ to add to a couple of different tenants. On the first tenant it worked fine and the 2 teams sites were created along with the Hub site. The Home screen has the +Create to add additional Team sites. On the second tenant it creates the hub site and the 2 Team sites. The only problem is that on the Home screen there is no +Create. Both were created exactly the same way and the version in the app catalog is 1.5.3.0.  I have deleted the sites and tried numerous times. Everything else seems to be working just fine.

Any suggestions or help would be great!

![Capture](https://user-images.githubusercontent.com/52038837/67163296-db059000-f332-11e9-9b56-840c0bd59a74.PNG)

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, Can you confirm whether self-service site creation is disabled in that other Tenant? 

https://docs.microsoft.com/en-us/sharepoint/manage-site-creation

If it is turned off, the create site + link will not show up.

**Comment by dgiles53** [comment]
Yes it is turned on for the other tenant.  I think what happened a file got corrupted when installed so installed it again and went thru and saved all the site settings and saved them. Now it is working just fine. Weird but at least it works.
