### ISSUE TITLE
Error: Update-AppIfPresent : Cannot process argument transformation on parameter 'Connection

### ISSUE THREAD

**Issue by benjamingournay2** [SharePoint/sp-starter-kit#33]
Hi,

I have the following error when running the script:
Update-AppIfPresent : Cannot process argument transformation on parameter
'Connection'. Cannot convert the
"SharePointPnP.PowerShell.Commands.Base.SPOnlineConnection" value of type
"SharePointPnP.PowerShell.Commands.Base.SPOnlineConnection" to type
"SharePointPnP.PowerShell.Commands.Base.SPOnlineConnection".
At F:\SPCode\sp-starter-kit\provisioning\deploy.ps1:96 char:92
+ ... "sharepoint-starter-kit-client-side-solution" -Connection $connection
+                                                               ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-AppIfPresent], Paramete
   rBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Update-AppI
   fPresent

Set-ThemeIfNotSet : Cannot process argument transformation on parameter
'Connection'. Cannot convert the
"SharePointPnP.PowerShell.Commands.Base.SPOnlineConnection" value of type
"SharePointPnP.PowerShell.Commands.Base.SPOnlineConnection" to type
"SharePointPnP.PowerShell.Commands.Base.SPOnlineConnection".
At F:\SPCode\sp-starter-kit\provisioning\deploy.ps1:106 char:31
+ Set-ThemeIfNotSet -Connection $connection
+                               ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-ThemeIfNotSet], ParameterB
   indingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-ThemeIf
   NotSet

![image](https://user-images.githubusercontent.com/35489873/41529163-7507c790-72ec-11e8-8e04-88e4838fbe79.png)

The 3 site collections are created but they are standard teams and communication sites.

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue on generic SharePoint topic or dev documentation, please use the (sp-dev-docs Issue list)[http://aka.ms/spdev-issues]
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by andreasblueher** [comment]
Could you please check and confirm you're using the current PnPPowerShell version?

`Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending`

You should have `2.26.1805.1` at least.

**Comment by benjamingournay2** [comment]
Yes, I have the version 2.27.1806.1 :
[cid:image001.png@01D4070D.00317EC0]

Cordialement,

Benjamin

----------------------
Benjamin Gournay
Responsable de produit (SharePoint)
T. +41 22 372 75 57
M. +41 78 634 62 90


Hôpitaux universitaires de Genève
Direction des Systèmes d’Information
Service des applications
Rue Gabrielle-Perret-Gentil 4
CH-1211 Genève 14
www.hug-ge.ch<http://www.hug-ge.ch/>
[cid:image001.png@01D09FB6.D17BA530]
Le contenu de ce courriel est uniquement réservé à la personne ou l'organisme à qui il est destiné. Si vous n'êtes pas le destinataire prévu, veuillez nous en informer au plus vite et détruire le présent courriel. Dans ce cas, il ne vous est pas permis de copier ce courriel, de le distribuer ou de l'utiliser de quelque manière que ce soit.


De : Andi [mailto:notifications@github.com]
Envoyé : lundi, 18 juin 2018 13:47
À : SharePoint/sp-starter-kit <sp-starter-kit@noreply.github.com>
Cc : GOURNAY Benjamin <Benjamin.Gournay@hcuge.ch>; Author <author@noreply.github.com>
Objet : Re: [SharePoint/sp-starter-kit] Error: Update-AppIfPresent : Cannot process argument transformation on parameter 'Connection (#33)


Could you please check and confirm you're using the current PnPPowerShell version?

Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

You should have 2.26.1805.1 at least.

**Comment by bcameron1231** [comment]
Hi. I am working through reviewing all of the issues in the issue list. I understand this is an old issue and may not be valid for you anymore.

Can you confirm if this is still an issue for you with the latest solution? Otherwise, we'd like to close the issue.
