### ISSUE TITLE
Portal Footer: My Links dialog does not open

### ISSUE THREAD

**Issue by dmitryrogozhny** [SharePoint/sp-starter-kit#332]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When using Portal Footer extension, I want to define personal links.

1. I create new user profile property to store user's personal links.
2. I expand the footer and click "Edit" link on the top right of the footer to open My Links dialog.
3. I can view and modify my personal links.

#### Observed Behavior

For a newly created user profile property (i.e. no value in it) the My Links dialog appears and disappears right away.

The reason is that the new property's value would be `undefined` which is not processed properly in the code.

![broken dialog](https://user-images.githubusercontent.com/8382522/69743535-a49c0b80-114f-11ea-8b6a-e43b457b8b1f.gif)

#### Steps to Reproduce

1. Create new user profile property following the [Create a Custom Property in the User Profile Service](https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/tenant-settings.md#create-a-custom-property-in-the-user-profile-service) guide.
2. Configure the Portal Footer to use the new property.
3. Try to open My Links Dialog.

**Comment by eoverfield** [comment]
Addressed with PR, thank you @dmitryrogozhny for the patch.
