### ISSUE TITLE
Something went wrong - web parts

### ISSUE THREAD

**Issue by philshil** [SharePoint/sp-starter-kit#34]
Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Web parts are not loading as expected. 

I have deployed the starter kit as instructed. When the web page loads, I get multiple something went wrong messages on the custom web parts. 

#### Observed Behavior

The error messages references to https certificates. 

SPLoaderError.loadComponentError]:
***Failed to load component "4f87b698-f910-451f-b4ea-7848a472af0f" (pnpWorldTime).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/[Tenant name].sharepoint.com/sites/appcat/ClientSideAssets/3624777a-337d-4b34-8384-5ab774c069aa/solution-worldtimewebpartstrings_en-us_43c772cfafa761c2ba62e49cee712b3b.js' for resource 'WorldTimeWebPartStrings' in component '4f87b698-f910-451f-b4ea-7848a472af0f' (pnpWorldTime). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://publiccdn.sharepointonline.com/[Tenant name].sharepoint.com/sites/appcat/ClientSideAssets/3624777a-337d-4b34-8384-5ab774c069aa/solution-worldtimewebpartstrings_en-us_43c772cfafa761c2ba62e49cee712b3b.js' for resource 'WorldTimeWebPartStrings' in component '4f87b698-f910-451f-b4ea-7848a472af0f' (pnpWorldTime). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:656:15779
t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:1401:22637
t@[native code]
buildErrorWithVerboseLog@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:1401:14557
https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:1401:65144
promiseReactionJob@[native code]

**Comment by andreasblueher** [comment]
This already has been described and closed in #25

**Comment by eoverfield** [comment]
Closing as addressed via issue #25
