### ISSUE TITLE
Personal mail and appointment webpart throw errors

### ISSUE THREAD

**Issue by bpvisser** [SharePoint/sp-starter-kit#35]
Webparts for personal mail and appointments show an error:

n.setAttribute is not a function. (In 'n.setAttribute("sandbox","allow-same-origin allow-scripts allow-forms allow-pointer-lock")', 'n.setAttribute' is undefined)

After a couple of times refreshing the page (F5) the error goes away, but turns up now and again.

**Comment by eoverfield** [comment]
Possible issue may have been graph related. Closing as a stale issue with no updates.
