### ISSUE TITLE
SharePoint Online : Issue with OOB Section layouts

### ISSUE THREAD

**Issue by BattulaNarahari** [SharePoint/sp-starter-kit#351]
Hi team,
We are trying to create a couple of news pages in a modern communication site on SPO and we are having an issue with the layout of the page on laptop browsers.
When the page Zoom level is set to 100% the page is not displaying in two-column layout, instead, it is displaying the first column in full width of the page and the right column is being displayed at the bottom of the page after the first column content. 

We want to have the two-column layout working with default 100% zoom level on laptops. Can you please help us here?

Attached screenshots for reference.
<img width="290" alt="Page with zoom level 75%" src="https://user-images.githubusercontent.com/22288412/70148863-010da680-16cd-11ea-839d-3ff460cfe0f2.png">
<img width="300" alt="Page with zoom level 100%" src="https://user-images.githubusercontent.com/22288412/70148864-010da680-16cd-11ea-97d2-38ab23ac4a0b.png">

**Comment by bcameron1231** [comment]
Hello, Unfortunately, this repository is for questions/issues regarding the PnP Starter Kit. If you have dev related questions, please ask this question over at the SP-Dev-Docs repository. 

https://github.com/SharePoint/sp-dev-docs
