### ISSUE TITLE
Error provisioning st

### ISSUE THREAD

**Issue by carla1020** [SharePoint/sp-starter-kit#356]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I have ensured my tenant meets the prerequisites 
-  I'm the global admin
- I'm in an English tenant
- Targeted release for everyone is set
- I'm listed as the tenant term store administrator
- App Catalog created from SPO admin center

The expectation was to have 3 new provisioned sites created successfully without error.

#### Observed Behavior & Steps to Reproduce

Without any modifications to any of the downloaded files, I get the following error  when running the command outlined in the documentation

Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL"="/sites/demoportal"; "MARKETINGALIAS"="demomarketing"; "HRALIAS"="demohr" }

![image](https://user-images.githubusercontent.com/55769018/71000881-0cd47200-20aa-11ea-950a-846459afb34f.png)

I want to say that I get the error after 5 minutes or so but missed exactly what was occurring prior to this error.  I'm hoping the content type warning will give you some clues where things fell apart.

It's worth noting that I do see the 3 site collections but I'm not confident they were properly provisioned as I did not receive the "successful provisioning" outputs as indicated in the documentation.

![image](https://user-images.githubusercontent.com/55769018/71001573-8a4cb200-20ab-11ea-96a3-404824b38531.png)

**Comment by eoverfield** [comment]
My guess is this is nothing, in your first screenshot, when you are connecting to your site in powershell, there is an added # before Connect-PnPOnline. Is is possible that you were actually connected to somewhere unexpected?

Otherwise, there must be a timeout / throttling issue as the site, /sites/demoportal, should be new to your tenant yes? If so, there should be no existing content, thus no overwrite, unless the provisioning engine attempted to reapply the template because of a timeout.

**Comment by carla1020** [comment]
Thank you for responding. I was connected to the appropriate tenant. I only commented it out in the PS1 file since I was already connected. 

I do see the new sites in my tenant but I’m  It clear on how validate that they were provisioned properly. Do you have some documentation on how these 3 sites are supposed to operate and work together?

Again thanks for taking the time out to respond. 

Carla

**Comment by eoverfield** [comment]
@carla1020 AllowUnsafeUpdates should not be needed, did any of the sites, demoportal, demomarketing, or demohr already exist?

There is an overview of the starter kit using an order installation technique, though it does not go into too much depth as to what the final results should contain in its entirety. You can see the video here:
https://www.youtube.com/watch?v=Gq10EyEuS2U

You could also use the provisioning template as a guide as to what is expected outcome although I understand that can be a long document to wade through.
https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/starterkit.xml

**Comment by carla1020** [comment]
Thank you Eric!  The demo sites definitely did not exist before executing the script. Let me see what I can figure out based on the hints you provided. 

Happy Holidays!

Carla

**Comment by carla1020** [comment]
Seems that despite the errors originally reported the sites were provisioned.  With the exception of the Banner and Weather Information web parts, I validated the existence of all the other web parts. 
 I'm still working my way through the extensions now but suspect I will be okay.  I will also see if I can reverse engineer the strterkit.xml file.  If I have any other issues or questions after reviewing the xml file I will open a new request.  Thanks again for your guidance.
