### ISSUE TITLE
Which Custom WebParts in StarterKit are compatible with Standard Release Tenant ?

### ISSUE THREAD

**Issue by hsamdani12** [SharePoint/sp-starter-kit#36]
#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

Can I please know which web parts really need Targeted Release for Everyone ? If I've Production tenant with Standard Release - Can I deploy all these webparts by just deploying .sppkg to a Tenant where Release Preference is set to - Standard Release ?

**Comment by eoverfield** [comment]
You will be unable to deploy the sppkg file to an app catalog in a tenant that does not have targeted release for everyone enabled. This is because the spfx package itself contains components and configuration settings such as "webApiPermissionRequests" found in package-solution.json that require targeted release. You would need to strip out quite a bit from the package to make this work without targeted release.

**Comment by eoverfield** [comment]
I am unsure of the timeline of the cleanup script. 

Per the documentation under [getting started](https://github.com/SharePoint/sp-starter-kit), it is recommended you do not deploy aspects of the SP Starter Kit to a production tenant. I cannot stress this enough, I highly recommend you utilize the free [Office 365 developer program](https://developer.microsoft.com/en-us/office/dev-program) to create a playground.

Another option is that you wait for current targeted release features such as the Graph components to make it to GA. No pubic timeline on this I am aware of, could be a few weeks to a few months maybe?

I would not recommend turning on targeted release in a production tenant. There is no solid way to ensure that targeted release won't cause any issues.

**Comment by hsamdani12** [comment]
Ok thanks. I'll then look getting the source code and extract some of the webparts, which I can deploy to standard tenant, I just want Custom Tiles(Promoted list) webpart and the Height Adjustable Banner webpart.

**Comment by eoverfield** [comment]
@hsamdani12 Those two webparts should migrate well and work in GA tenants.

As of today, the following webparts that require MSGraphClient and thus Targeted release
Personal Calendar
Personal Contacts
Personal Email
Personal Tasks
Recent Contacts
Recently Used Documents
Recently Visited Sites

There is an extension that sort of requires targeted release
Discuss now - currently using AadHttpClient, but should be migrating to MSGraphClient at some point.

**Comment by bcameron1231** [comment]
@hsamdani12  I have created a solution that removes all of the FR required web parts. If you'd like to test/use this solution, I'll post it up to Github.

**Comment by hsamdani12** [comment]
Thanks @eoverfield and @bcameron1231 for the info.
@bcameron1231, Thanks! that would be very helpful, if you put it up on GitHub and share the link. Ye planning to first test them in a Dev\UAT tenant first.
Also I've one question not related to starter toolkit, I'm struggling to find a solution. For branding is it possible to put banner sized logo in the header using App Customizer, and not have the boxed sized Site logo. I know about logo setting in the O365 Suite Bar, but it applies to whole tenant across all the O365 products. sort of like this - http://blog.pixelmill.com/3322/add-image-custom-header-footer-modern-page
the way PixelMill logo in Suite Bar, to be shown in the header instead.

**Comment by bcameron1231** [comment]
@hsamdani12 You can find the repo [here ](https://github.com/bcameron1231/PnP-Starter-Kit-Non-FR) . Please be advised, I haven't tested a TON but it was working the last few times I deployed. You can either upload the .sppkg alone, or you can run the deploy.ps1 script to install the pages and sites as well.

**Comment by bcameron1231** [comment]
@hsamdani12 You can find the repo [here ](https://github.com/bcameron1231/PnP-Starter-Kit-Non-FR).. It's just a clone, not a fork... so I won't be pulling any new changes into it. But here is the quick link to it. Please be advised, I haven't tested a TON but it was working the last few times I deployed. You can either upload the .sppkg alone, or you can run the deploy.ps1 script to install the pages and sites as well.

**Comment by hsamdani12** [comment]
Thanks. @bcameron1231

**Comment by bcameron1231** [comment]
@hsamdani12 Happy to help. Did it work for your needs?

**Comment by bcameron1231** [comment]
You can provision the Links library using PnPProvisioning Template provided in the source code.
The pnp provisioning template is Portal-Footer-Links.xml

Navigate to that location, connect to your tenant and deploy using pnp
`Connect-PnPOnline -TenantUrl https://yoursite.sharepoint.com/sites/yoursite`
`Apply-PnProvisioningTemplate -Path PnP-PortalFooter-Links.xml`

Then if you want to add the Customizer to be running your site, you can run the following command.
`Connect-PnPOnline -Url https://yoursite.sharepoint.com/sites/beau
    
    $context = Get-PnPContext
    $web = Get-PnPWeb
    $context.Load($web)
    Execute-PnPQuery
    
    $ca = $web.UserCustomActions.Add()
    $ca.ClientSideComponentId = "b8eb4ec9-934a-4248-a15f-863d27f94f60"
    $ca.ClientSideComponentProperties = "{""linksListTitle"":""PnP-PortalFooter-Links"",""copyright"":""â’¸ Copyright Contoso, 2018"",""support"":""support@contoso.com"",""personalItemsStorageProperty"":""PnP-CollabFooter-MyLinks""}"   
    $ca.Location = "ClientSideExtension.ApplicationCustomizer"
    $ca.Name = "PortalFooter"
    $ca.Title = "PortalFooter"
    $ca.Description = "Portal Footer"
    
    $ca.Update()
    
    $context.Load($web.UserCustomActions)
    Execute-PnPQuery`

If you want to change what the footer says, you can modify the ClientSideComponentProperties in the command. Instead of Contoso put your company name, etc..
