### ISSUE TITLE
Weather WebPart is using invalid API

### ISSUE THREAD

**Issue by mhijazi** [SharePoint/sp-starter-kit#367]
Hey Guys,

The weather web-part in the starter kit is using an old API of Yahoo which they have already stopped.
```
Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired.
> To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Follow below instructions to get credentials and onboard to this free Yahoo Weather API service.
```

**Reference:**
https://developer.yahoo.com/weather/

**Comment by bcameron1231** [comment]
Thank you for the comment. We are aware and addressed this issue for the Weather Web Part. We have converted from using the Yahoo weather API, to start using the OpenWeatherMap.

Unfortunately, this change will not be made available until the next release of the Starter Kit.
