### ISSUE TITLE
Change Company and Copyright for ext-portal-footer

### ISSUE THREAD

**Issue by jonasesser** [SharePoint/sp-starter-kit#368]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

How could I change the copyright and company name in the footer after installation?

**Comment by bcameron1231** [comment]
Hi, please see the blog post I have written on this. In the section "Updating an already deployed footer"

https://beaucameron.net/2018/07/19/customizing-the-pnp-starter-kit-for-office-365-part-1-portal-footer/
