### ISSUE TITLE
PNP tiles list not configure in pnp starter kit 

### ISSUE THREAD

**Issue by hassannawaz1** [SharePoint/sp-starter-kit#37]
There is an issue in pnp tiles webpart  is that instead of list url the office fabric ui is configured not the url of pnp tiles list .

![pnpstarter](https://user-images.githubusercontent.com/40266804/41616689-00127296-7418-11e8-9c74-e7bf95e7e649.png)

**Comment by bcameron1231** [comment]
@hassannawaz1  This link is not meant to map to a SharePoint list. This is just a helpful link to the Office Fabric Site so you know what values to use for the "UI Fabric Icon Name" field in the **Configure the Tiles** menu.

Notice the value in the column highlighted in the image below.  If you'd like to change the icon that shows up for a given link, navigate to the UI Fabric site and find the icon you want and replace it in this field.

![image](https://user-images.githubusercontent.com/7944457/41618731-43c026d4-73c1-11e8-95fa-443f38b47fe8.png)

**Comment by hassannawaz1** [comment]
@bcameron1231   thanks to you but i ahve one more problem is that in my starter kit the footer and navigation is not showing in the communication site the. I also  attached the images . And i have some errors when running the code or scripts in powershell.
![interanet1](https://user-images.githubusercontent.com/40266804/41645560-ca095bce-748a-11e8-9490-228676a503f2.png)
![interanet2](https://user-images.githubusercontent.com/40266804/41645566-cde1ac74-748a-11e8-8949-31530ab0f8e1.png)
![errorpnp starterkit](https://user-images.githubusercontent.com/40266804/41645587-d8152a86-748a-11e8-882f-34dc85351e64.png)

**Comment by eoverfield** [comment]
Redirecting second request to new issue: [https://github.com/SharePoint/sp-starter-kit/issues/39](https://github.com/SharePoint/sp-starter-kit/issues/39)

**Comment by SarwarRana** [comment]
Hi,
Is there any way we can use custom icon rather than using UI Fabric Icons please?

Thanks

**Comment by eoverfield** [comment]
@SarwarRana, you could certainly update the Tile webpart to suit your needs. It is not natively supported though within the project.

**Comment by SarwarRana** [comment]
Thanks for quick response mate.

**Comment by Preethirasu** [comment]
I need to fetch the items from PnPTiles List.  please anyone share the code and the location of that list

**Comment by bcameron1231** [comment]
@Preethirasu All code for this solution is maintained in this repository, you are free to use it/change it as you please. However for this, there is no list for the tiles. The tiles information is held on the properties of the web part in a collection field control.

**Comment by Preethirasu** [comment]
how to do validation in PropertyFieldDataCollection control. i.e i want to restrict the title to be 150 characters.

**Comment by bcameron1231** [comment]
@Preethirasu Here is a link to the SPFx documentation for validating properties on web parts. [](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/validate-web-part-property-values) . I hope this helps!

**Comment by eoverfield** [comment]
Closing as recommendations have been provided.
