### ISSUE TITLE
Sharepoint Online Seattle master page header performance issue

### ISSUE THREAD

**Issue by BattulaNarahari** [SharePoint/sp-starter-kit#370]
We are working on one of the application which is built on SharePoint online modern communication  site and we have been observing the performance issue with Seattle master page header very frequently. However we didn’t made any customization's on master page header. Could you please help us on resolving the performance issue. 

Please find attached screen shots for reference.

**Before Loading Header Menu highlighted in Red**
<img width="950" alt="Before Loading Header Menu highlighted in Red" src="https://user-images.githubusercontent.com/22288412/72873029-c6aba780-3d14-11ea-9d2d-bb0116fda920.png">

**After Loading Header Menu highlighted in Red**
<img width="756" alt="After Loading Header Menu highlighted in Red" src="https://user-images.githubusercontent.com/22288412/72873038-cad7c500-3d14-11ea-86fc-fa279f495342.png">

**Comment by bcameron1231** [comment]
Thank you for the comment.

Unfortunately, this is outside of the support of the SharePoint Starter Kit.  My suggestion would be to raise a support ticket directly with Microsoft to have this addressed.
