### ISSUE TITLE
Error at Followed Sites webpart

### ISSUE THREAD

**Issue by pereirautv** [SharePoint/sp-starter-kit#374]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Steps to Reproduce
I tried to add (https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/components/wp-followed-sites.md) code to a react Sharepoint 2019 online and on-prem solution i created. 

I’m new to SharePoint and been elaborating with webpart solutions and are now stuck. I’m trying to implement the above code to a SPO&On prem 2019 webpart solution but are getting this error.  

> workbench.aspx:1 Access to XMLHttpRequest at 'https://waconatm.officeapps.live.com/apc/trans.gif?136b311d6bba9c0d0f0ecf4b72e514e2' from origin 'https://xxx.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
fp-min.js:1 

> GET https://waconatm.officeapps.live.com/apc/trans.gif?136b311d6bba9c0d0f0ecf4b72e514e2 net::ERR_FAILED

I even tried to add ‘_vt_bin/homeapi.ashx/sites/followed?’ Without success. How can i solve this problem?

**Comment by eoverfield** [comment]
This particular webpart uses the Rest API endpoint, /_api/social.following, in particular _api/social.following/my/followed(types=4) for followed sites. This is available in SPO and SP 2019 on prem. 

The default response from this endpoint does not include a CORS header, thus it is not meant to be utilized across the domain boundary. OOTB this webpart will not work for you unless you make some changes, or if you are in hybrid, you will want to always make requests to the local domain where the website is being loaded.

**Comment by pereirautv** [comment]
What changes do i have to do?

**Comment by eoverfield** [comment]
If you are making a cross domain request to the SharePoint rest API endpoints, you are basically out of luck. You would like need to create some sort of proxy service in Azure to handle the requests, or possibly someone else has a good strategy they can share.

**Comment by pereirautv** [comment]
Okej thank you

**Comment by bcameron1231** [comment]
Looks like Eric has answered your question. I am going to close this ticket, as it pertains to building your own implementation unrelated to the core Starter Kit web parts. If you have any issues on the SPFx Development side of things, the SP-Dev-Docs would be a great repo to seek more help.

**Comment by alexbradshaw1971** [comment]
May be worth checking this MS article out as it mentions using a function api to integrate with SPFx and you set up the CORS on the function app, https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi.
