### ISSUE TITLE
Issue: Personal Calendar not displaying items

### ISSUE THREAD

**Issue by RobertHoegner** [SharePoint/sp-starter-kit#375]
I am experiencing multiple issues with Graph-API related Web-Parts like Personal Calendar. It does not fetch nor display any items:
![image](https://user-images.githubusercontent.com/49672998/75138256-084fb980-56ea-11ea-933b-58e8b7e63519.png)

**Comment by eoverfield** [comment]
Is this with a new installation of the solution to your tenant, or have these webparts that utilize graph been working up to just recently?

Generally sounds as though your API management may need a review. This is found in your SharePoint Admin center. You could also consider reinstalling the SPFx solution, which should then trigger the API requirement process.

**Comment by RobertHoegner** [comment]
> Is this with a new installation of the solution to your tenant, or have these webparts that utilize graph been working up to just recently?
> 
> Generally sounds as though your API management may need a review. This is found in your SharePoint Admin center. You could also consider reinstalling the SPFx solution, which should then trigger the API requirement process.

@eoverfield  thanks for the lightning fast reply and sorry for robbing your time. You were totally right. Yesterday I re-published he solution from the app-catalog cause i had issues with timezones on the "personal calendar" which resulted in the graph api errors. I simply had to approve the pending API request from the admin-center!
