### ISSUE TITLE
Connect-PnPOnline : Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by krishnachaluvadi** [SharePoint/sp-starter-kit#376]
#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement
 I was able to work with Connect-PnPOnline -url https://tenant.sharepoint.com/ -Credentials $crds until this morning, and PnP version was 3.13.1909.0. But when started seeing the above error, tried to updated to latest version, 3.18. 2002.0, still same error.

#### Expected or Desired Behavior

It should connect to the tenant without error.

#### Observed Behavior
P.S - Replaced the tenant name.

Connect-PnPOnline : Exception has been thrown by the target of an invocation.
At line:1 char:1
+ Connect-PnPOnline -url https://tenant.sharepoint.com
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], TargetInvocationException
    + FullyQualifiedErrorId : System.Reflection.TargetInvocationException,SharePointPnP.PowerShell.Commands.Base.Conne
   ctOnline

#### Steps to Reproduce

Open PowerShell Window and type in the below command
Connect-PnPOnline -url https://tenant.sharepoint.com

#### Submission

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Thank you for the comment. However, this question isn't specific to the Starter Kit. The best place for this issue would be in the [PnP PowerShell Repository](https://github.com/SharePoint/PnP-PowerShell).
