### ISSUE TITLE
Continuous loading 

### ISSUE THREAD

**Issue by sheiknaveed** [SharePoint/sp-starter-kit#377]
Continuous loading for personal mail, personal contact, and personal calender

**Comment by eoverfield** [comment]
Hi, are you reporting a specific error you are seeing? If so, are you able to provide more context? If a feature request, could you describe in more detail?

**Comment by sheiknaveed** [comment]
Dear Eric,
Kindly see the snapshot below. It is loading continouously.
[cid:image001.jpg@01D5EE85.4BDF8AE0]


Sheik Naveed
شيك نافيد
Academic Systems Administrator
مسؤول النظم الأكاديمية
Smart Services and Projectsالخدمات الذكية والمشاريع
Tel: 800- MBRU (6278)
Direct +9714 383 8606
Naveed.Sheik@mbru.ac.ae
www.mbru.ac.ae
P.O. Box 505055, Dubai,  UAE

**Comment by sheiknaveed** [comment]
<img width="917" alt="loading" src="https://user-images.githubusercontent.com/60134901/75574943-a6d87380-5a78-11ea-89bf-5fe57801407d.PNG">

**Comment by sheiknaveed** [comment]
I am getting same loading for Task, Contacts, Calender, mail

**Comment by eoverfield** [comment]
Those webparts all use graph and thus require API permission consent.

Did these webparts ever work for you?
Did you authorize the required api permissions in the API management page?
Would you check your console.log and see what errors are being thrown and share them?

**Comment by sheiknaveed** [comment]
I had approved the API permission. It worked onces. now it is not working

**Comment by eoverfield** [comment]
Would you please look in your browser's console log and report back any errors related to one of these components?

**Comment by sheiknaveed** [comment]
Please find below the error which I received in Console
<img width="1033" alt="error" src="https://user-images.githubusercontent.com/60134901/75619255-0d51b480-5b93-11ea-95e4-b2d56ae22c09.PNG">

**Comment by bcameron1231** [comment]
@sheiknaveed Are you saying this same web parts works in another site, or another tenant?
