### ISSUE TITLE
Failed to create application customer after page reload

### ISSUE THREAD

**Issue by mkds2** [SharePoint/sp-starter-kit#378]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When I 'gulp serve' my sharepoint extension to my SP page, it renders on initial opening and I expect it to re-render successfully when I refresh the page.

#### Observed Behavior

After successful rendering of my extension app after running 'gulp serve', my app disappears when the page gets refreshed and the alert to choose 'load debug scripts' does not show up either. The following errors are thrown in console:

`sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:4 Uncaught (in promise) Error
    at t [as constructor] (sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:4)
    at new t (sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20)
    at Function.e.buildErrorWithVerboseLog (sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20)
    at Function.e.buildLoadComponentError (sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20)
    at sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20`

`sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:47 Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.13727db7-bbd0-462a-8a1c-90cf09ff6ee2'. Error information is '***Extension failed to load for componentId "13727db7-bbd0-462a-8a1c-90cf09ff6ee2".'.
    at sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:47
    at async Promise.all (index 1)`

#### Steps to Reproduce

1. run 'gulp serve' in console.
2. click load debug scripts.
3. after initial rendering of app, refresh browser tab.

**Comment by eoverfield** [comment]
Which application customizer are you referring to within this project?

**Comment by mkds2** [comment]
> Which application customizer are you referring to within this project?

I am referring to the Base application customizer for my 'PlaceholderContent' in the '_bottomPlaceholder'. Here is a snippet which includes my onInit():

`export default class ApplicationCustomizer
  extends BaseApplicationCustomizer<IChatProps> {
    private _bottomPlaceholder: PlaceholderContent | undefined;
  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);
this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);
// this.context.application.navigatedEvent.add(this, updateData)
this._renderPlaceHolders();

    return Promise.resolve<void>();`

**Comment by mkds2** [comment]
I must also add that this issue is now happening with all of my Sharepoint react extensions which never had this issue before however without the errors I posted in the initial request. Renders normally on initial 'gulp serve' but then fails on page reload. I am seeing this warning in console come up before anything:
`DevTools failed to parse SourceMap: https://localhost:4321/temp/manifestsFile.js.map`

also seeing this error:
`Key search-page-core.searchux.strings.ConversationVertical.labelName does not exist in string map`

**Comment by eoverfield** [comment]
This sounds as though you are having an issue with a general SPFx extension, and not one related to this project. Or at least you are having issues with other SPFx extensions as well. 

In that case, this is not the best forum for your issue, please repost over at the sp dev docs issues list:
https://github.com/SharePoint/sp-dev-docs/issues
