### ISSUE TITLE
Translation Error (DE-de) for Personal EMail, Calendar, Contacts

### ISSUE THREAD

**Issue by RobertHoegner** [SharePoint/sp-starter-kit#379]
View the full list has a translation error for german (DE-de). The correct Translation would be "Zeige die gesamte Liste an" and not
![image](https://user-images.githubusercontent.com/49672998/75803834-59614c80-5d7f-11ea-9b65-5e7f7e6f2c21.png). Could anyone fix and "repackage" the spppkg files, so I can re-deploy. Help is highly appreciated! (I have no dev-tools installed / setup).

**Comment by bcameron1231** [comment]
Hi @RobertHoegner , thank you for this. We'll take note of this, and submit a PR. However, it may take some time to make it into the release.

**Comment by StfBauer** [comment]
Thank you @RobertHoegner It will be changed to "Vollständige Liste anzeigen".

**Comment by eoverfield** [comment]
Thank you everyone for your patience. The German translation for the personal webparts has been updated and pushed to the master branch.

https://github.com/SharePoint/sp-starter-kit/commit/3cd1cd11dc8e3086e79adc57e22df0fe80e02fe0

If you re-install the project ./package/sharepoint-starter-kit.sppkg to your tenant app catalog, you should see the new translations. The new default provisioning process will also include the latest translations.
