### ISSUE TITLE
Documnet library Title to an html annoucement page

### ISSUE THREAD

**Issue by sheiknaveed** [SharePoint/sp-starter-kit#380]
Dear Team,
I know this is not the right channel but can anyone help me sort this issue.
I have an html announcement ticker and I would like to feed the title from the file in document library and when anyone click on the title, it will open the file.
please the snapshot.
![image](https://user-images.githubusercontent.com/60134901/76687909-9b24a980-6641-11ea-8ded-7e9e0bf449b9.png)

**Comment by eoverfield** [comment]
Hi, I do suggest you post this question over at the PnP Issues list: https://github.com/SharePoint/pnp/issues , or try stack exchange: https://sharepoint.stackexchange.com/questions/tagged/sharepoint-framework.

In general a common scenario. Using a tool such as PnPJS to help query the doc library in question, and get the data you want, all bundled into a SPFx extension.
