### ISSUE TITLE
Uncaught TypeError in browser for Tiles / Banner webpart

### ISSUE THREAD

**Issue by moniquid** [SharePoint/sp-starter-kit#381]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Thank for the hard work on the sp-starter-kit! The sample helps me to learn the function porvided in the SPFx! I have encounter some javascript error when running "Tiles" and "Banner" webpart in browser. 

Error in browser
Banner:
TypeError: this.propertyFieldNumber is not a function

Tiles:
TilesWebPart.ts:80 Uncaught TypeError: Cannot read property 'string' of undefined

Do you have any idea? 
Thank you for your help in advance

**Comment by bcameron1231** [comment]
Hi, Thank you for the question. Having a little trouble reproducing the issue you are having. Have you made any changes to the Banner or Tiles Web Parts?

**Comment by moniquid** [comment]
I have generate the web part solution using yeoman which target Sharepoint 2019 (on-prem). And copied the files under src/webparts and run gulp serve. No other changes were made. Please find the javascript error in the below screenshot for your reference: 

![2020-03-23 11_46_43-DevTools - localhost_4321_temp_workbench html](https://user-images.githubusercontent.com/6974131/77401247-88e7ff80-6de7-11ea-8d59-cd49eb78cba7.png)

![2020-03-23 11_55_58-DevTools - localhost_4321_temp_workbench html](https://user-images.githubusercontent.com/6974131/77401240-87b6d280-6de7-11ea-9ba4-4f71d5f06303.png)

Thanks again for your help!

**Comment by bcameron1231** [comment]
Hi Thank you. To confirm, are you trying to install this on SharePoint 2019? If so, this is not possible because the Starter Kit is currently using 1.9.1, which doesn't work on-premises. We are actively working on provided better cross platform SharePoint support.

**Comment by moniquid** [comment]
Thanks for your reply! Hope the Start Kit will be available to Sharepoint 2019 soon! 
Looking forward to it :)
