### ISSUE TITLE
Issues with pages since installing SP-starter-kit

### ISSUE THREAD

**Issue by Rock9742** [SharePoint/sp-starter-kit#382]
Hi,
I have installed the SP-starter-kit to use some of the included web parts. the web parts are all available and working as expected. I thought the new web parts would only deploy to the new "demo" sites that were created (as per the instructions) but it seems to have applied to the whole tenant. Upon reading again, it looks like this information was there to expect this, so my bad.

When on SharePoint home page on my hub site and I select a link to another SharePoint site in the same tenant (using the top bar navigation) and then select the “Home” button, I get an error as per the attachment. If you refresh the page, the page displays OK. It seems to only be when the page is loaded as companyname.sharepoint.com and doesn’t automatically redirect to company.sharepoint.com/sitepages/home.aspx. Do you know what this could be and any suggested fixes?

![SPPage Error](https://user-images.githubusercontent.com/62532996/77283112-c3866500-6d1f-11ea-8b52-2c6e9701429a.png)

**Comment by bcameron1231** [comment]
Hi, thank you for the question. Can you provide a bit more information? Is the error happening on a page that was deployed with the starter kit, or contain a web part deployed from the starter kit? 

Trying to determine if this is an issue from the starter kit, or a SharePoint Online issue. Thanks

**Comment by Rock9742** [comment]
Thanks so much for getting back to me so quickly. This error is happening on a page that existed before deploying the starter kit. I did add a web part to the page and the issue started immediately after. I have now restored the page from a previous version saved before I deployed the starter kit. The issue still remains.

 

Thanks again

**Comment by bcameron1231** [comment]
Interesting. Are you able to restore any version successfully? Does the page include any WebParts from the starter kit?

Can you reproduce this on any other sites, or is it just affecting the sites deployed with the starter kit.

**Comment by Rock9742** [comment]
The site affected is the hub site (home in the top bar navigation). I have a small SharePoint collection with only 1 hub site and 11 sites associated with the hub. The version of the hub site I restored, was created a few weeks before I deployed the starter kit. It restores and works OK, until you select another site via the top bar navigation and then select the hub site again. I get the error I attached. If I refresh the page it is OK again.

 

I have tested more and if I open the hub site, select another site from the top bar navigation and then another site, other than the hub site (Home) all is OK, no errors.

If I open the hub site, select another site then select the hub site via the top bar navigation (home link) I get the error I attached. If I then don’t refresh the page and select another site from the top bar navigation I keep getting the error attached for each page till I refresh the page.

 

I have attached a cropped video that may explain the behaviour better.

 

Thanks

**Comment by bcameron1231** [comment]
I am unable to see the video in GitHub, if you could upload it and post a link to it that would be great. From your description, I'm not sure this is related to the Starter Kit, but an issue relating to the restore of your hub site.

**Comment by Rock9742** [comment]
Thanks Beau,

I have linked the video below. To clarify, I haven’t restored the hub site, I restored the hub site home page only. I restored the home page to a version before the starter kit was deployed. I restored to that version of the page after I started experiencing the issue, to troubleshoot if the home page had been corrupted when the new web parts were added.

 

Link to the video:

http://tiny.cc/1a4ulz

**Comment by bcameron1231** [comment]
hmm very interesting.  So the home page, no longer has the PnP Starter Kit Web Parts on it? I'm not 100% sure it's an issue with the Starter Kit yet, especially if the home page doesn't have those web parts.

Can you open up Developer Tools (F12) and let me know if you are seeing any errors in the console when you reproduce this error? What it looks like, is a piece of code is grabbing the departmentId (which the Hub Site ID), and it's apparently not on the object. Maybe Developer Tools will give us a little bit more information.

**Comment by Rock9742** [comment]
Hi Beau, 

 

To clarify, the web parts are available to be added, I just haven’t added any. I was testing to see if the issue went away if the new web parts didn’t exist on the page.

 

I got the below from the console:

sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21 

TypeError: Cannot read property 'departmentId' of undefined

    

at b (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:1)

    

at e.render (chunk.sp-pages-search-init_68a2232a88da623bd1c1.js:1)

    

at xi (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21)

    

at ki (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21)

    

at sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21

    

at Ua (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21)

    

at Ia (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21)

    

at xo (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21)

    

at bo (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21)

    

at mo (sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js:21)

**Comment by bcameron1231** [comment]
Great thank you! So it looks like the error is originating from sp-pages-assembly_en-au_d60d189e38d8e86138621ee12c0ae21f.js 

This is client side code from Microsoft, and unfortunately not a piece of Starter Kit code. You may want to remove the hubsite (unregister it) and re-add/register the site as a hub site and see if it fixes your issue.

Otherwise, I would recommend going through Microsoft Support and see if they could be of assistance.

**Comment by Rock9742** [comment]
OK, thanks for all your help Beau, appreciate it!
