### ISSUE TITLE
Nothing happened 

### ISSUE THREAD

**Issue by maries1986** [SharePoint/sp-starter-kit#384]
I downloaded and uploaded to the SharePoint app catalogue and deployed......nothing happened?

I accepted in API also.  am i missing something??

**Comment by bcameron1231** [comment]
Hi there, You've only uploaded the App, which makes the web parts available to use,  it doesn't deploy the starter kit.

If you want to deploy the starter kit, please follow directions in the Pre-Requirements and the Getting Started section. https://github.com/SharePoint/sp-starter-kit
