### ISSUE TITLE
how to default to the Search box pnpPeople Directory webpart

### ISSUE THREAD

**Issue by tatikhokh** [SharePoint/sp-starter-kit#387]
Is there a way to default to a Search box pnpPeople Directory webpart? Thank you

**Comment by bcameron1231** [comment]
Hi there. You want the SharePoint search box to link to the PeopleDirectory, and utilize the search? This wouldn't be possible without some custom development done to the people directory. Let's tackle this in two parts.

1. Yes you can change the default location of the search box to point to another page. You can look into using PnP PowerShell to do this. https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsearchsettings?view=sharepoint-ps

2. If you want the people directory to filter from the search page, you will need to update the code in the people directory to support pulling search values from the query string.

**Comment by tatikhokh** [comment]
Hi @bcameron1231 ,
Thank you for your comments, however I need to achieve the following - to 
default to Search instead of A:
![image](https://user-images.githubusercontent.com/55210628/80231553-87e20200-8621-11ea-9f29-6e24ddcffa73.png)

**Comment by bcameron1231** [comment]
Ah I see what you mean. Sorry if I misread what you were after. 

You'll need to change your selectedIndex property from "A" to "Search" in your PeopleDirectory.tsx file

![image](https://user-images.githubusercontent.com/7944457/80233648-13549680-8614-11ea-9418-5e6de528ed20.png)

**Comment by tatikhokh** [comment]
@bcameron1231  - thank you!!!
