### ISSUE TITLE
Starter Kit Footer and navigation

### ISSUE THREAD

**Issue by hassannawaz1** [SharePoint/sp-starter-kit#39]
I have   problem in my starter kit is that in my starter kit the footer and navigation is not showing in the communication site the. I also  attached the images . And i have some errors when running the code or scripts in power shell .Please help as soon as possible.
![interanet1](https://user-images.githubusercontent.com/40266804/41645735-4b4cc11c-748b-11e8-9a48-d91b92417af9.png)
![interanet2](https://user-images.githubusercontent.com/40266804/41645739-4f56a0f2-748b-11e8-988e-54dfb361f0ae.png)
![errorpnp starterkit](https://user-images.githubusercontent.com/40266804/41645753-55cf488a-748b-11e8-8c24-c293dac74eea.png)

**Comment by eoverfield** [comment]
Is the primary language of your tenant English? A known limitation of the end to end provisioning is an english tenant.

I have seen one of the errors you are witnessing during provisioning regarding the null ClientObject, common when I am seeing timeout delays communicating with SPO. Can't say for sure this is one of the issues.

Regarding navigation, I would focus on the clean provision first as likely one of the required components has yet to properly provision.

**Comment by hassannawaz1** [comment]
@eoverfield  how can i resolve the issue of navigation and what is mean of clean provision

**Comment by bcameron1231** [comment]
@hassannawaz1  There is no navigation that shows up on top like you are describing in your photo. There is only hub site navigation which appears at the top top of the page. Can you confirm you have this?

As for the footer, I just noticed this on my tenant. I did a hard refresh (cleared my cache) and the footer showed back up. Can you try that?

**Comment by hassannawaz1** [comment]
@bcameron1231  sorry it was hub site navigation and  its not showing

**Comment by eoverfield** [comment]
@hassannawaz1  what I mean by "clean provision" is being able to run the deploy.ps1 script with no errors. There are a few steps in deploy.ps1 that create the hub site, update the navigation, as well as add the additional sites listed in hierarchy.json to the hub. Any of those steps might have failed, difficult to tell based on the screenshot provided, which could have caused issues with the hub being registered properly.

I believe you will find the comm site is not actually a hub yet.

**Comment by LouFarho** [comment]
@hassannawaz1  You can use Get-SPOHubSite to get your list of hub sites to verify. Make sure you use Connect-SPOService -url https://tenant-admin.sharepoint.com

**Comment by hassannawaz1** [comment]
@eoverfield ok thanks i am trying

**Comment by eoverfield** [comment]
@hassannawaz1 as this is a legacy issue, can you confirm if you were able to get the issue solved, or if a more recent version of the kit helped resolved this issue? If not, are you able to provide any additional information around this issue?
