### ISSUE TITLE
Site Information webpart default term set and group do not exist

### ISSUE THREAD

**Issue by eoverfield** [SharePoint/sp-starter-kit#46]
#### Category
- [X] Bug

#### Expected or Desired Behavior

When using the Site Information webpart, the Site Organization term picker should bring up default terms to pick.

#### Observed Behavior

The default term set and group hard coded into webpart properties is not created by default, thus when attempting to set the Site Organization, no terms are provided.

#### Steps to Reproduce

Add the Site Information webpart and attempt to set the Site Organization. Assuming you did not manually add the default term set and group, no terms are displayed.

#### Recommended solution

in provisioning/solution.xml, add a default group: Company, a default Term Set: Organization, along with a few default organization terms.

**Comment by PaoloPia** [comment]
Good catch @eoverfield !
The fix you proposed in PR #47 was ok to me, but I see you closed that one, most likely to create a dedicated PR, instead of a "multi-fix" one. Feel free to submit a new PR just for this issue and I will be more than happy to merge it. Thanks.

**Comment by eoverfield** [comment]
@PaoloPia I moved it to over here: https://github.com/SharePoint/sp-starter-kit/pull/64, but in copying this over, I missed the link, sorry about that. Thanks.

**Comment by bcameron1231** [comment]
Closing - This was fixed in a subsequent PR.
