### ISSUE TITLE
Error when running deploy.ps1

### ISSUE THREAD

**Issue by emailtosamit** [SharePoint/sp-starter-kit#49]
When i run first step deploy.ps1 i got below errors :- 

![image](https://user-images.githubusercontent.com/17134881/41760755-5826804a-7638-11e8-84dc-e158face2a51.png)

**Comment by raghu522** [comment]
after this script ran for a while and then getting this error
![image](https://user-images.githubusercontent.com/30563384/41767145-7a28c7b4-7626-11e8-82f3-edb58cdf1a97.png)

**Comment by eoverfield** [comment]
What version on PnP PowerShell do you have installed? Could you run the following and ensure you are using 2.27.1806.1?

Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Also when you say, after a long time, how long is that? Minutes? hours? The entire script should only take about 5-10 minutes to complete. If it is taking longer, I wonder if there is a timeout / context that goes missing.

**Comment by emailtosamit** [comment]
hi eoverfield,

I have updated the powershell version. It worked with error. I can see it created the SharePoint sites. But I am not sure why it gave error though.

![image](https://user-images.githubusercontent.com/17134881/41832052-a1e79a78-788d-11e8-9dec-19e1c437721c.png)

**Comment by eoverfield** [comment]
The first error is not a major cause for concern, that is being thrown by npm when npm install is executed on line 76, fsevents has known issues on different OS's. It isn't great, but that should not be causing major issues.

As for the error when provisioning the solution, do you have targeted release enabled for all users and if so, have you waited at least 24 hours before running the deployment script?

**Comment by eoverfield** [comment]
Closing as a stale issue, also addressed with newer provisioning methodology.
