### ISSUE TITLE
My extensions in the starter kit are not working.

### ISSUE THREAD

**Issue by hassannawaz1** [SharePoint/sp-starter-kit#50]
My extensions in the starter kit are not working. My all starter kit is complete but the extensions not working and so that's why footer is not working

**Comment by eoverfield** [comment]
Can you provide more background information? Are you not seeing the footer on the communication/portal/hub site, i.e. /sites/demo_portal/? If not, are any of the starter kit webparts available to be added to your portal pages? When you ran the deploy.ps1 script, were any errors returned?

**Comment by Javapower77** [comment]
Hi! I have the same issue. For example, I added a new alert in the Alert list but there is no banner in the portal home showing me the alert.

Another thing, is in the Group Site, the footer is not showing all the links. It is only showing MyLinks. 

No issues while running the deploy.ps1.

![image](https://user-images.githubusercontent.com/9665164/42051306-1a76224c-7ae2-11e8-927c-cb78d77b3e9d.png)


Any ideas?

**Comment by hassannawaz1** [comment]
eoverfield  this is only error i have and my footer in communication site not working 

Apply-PnPProvisioningTemplate : Culture is not supported.
Parameter name: name
en-EN is an invalid culture identifier.
At D:\hassannawaz\sp-starter-kit-master\provisioning\deploy.ps1:123 char:1
+ Apply-PnPProvisioningTemplate -Path "$PSScriptRoot\portal.xml" -Parameters @{"We ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], CultureNotFoundException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by eoverfield** [comment]
@hassannawaz1 were you able to get the extensions working or could you provide more information here to see if we can help you resolve this issue?
