### ISSUE TITLE
How to upload and deploy the sppkg file

### ISSUE THREAD

**Issue by Chris-Leeworthy** [SharePoint/sp-starter-kit#57]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Could I get some more detailed instructions on uploading and deploying the sppkg file or can someone point me to the correct documentation for doing this please?

Thanks in Advance

**Comment by eoverfield** [comment]
@Chris-Leeworthy I have a doc created and will be creating a PR in the next day or so.

**Comment by eoverfield** [comment]
@Chris-Leeworthy the PR is in. You can review at least the content at the following location although the images won't yet load. The content is correct though, I have verified it a few times. If you have any feedback, please let me know.

https://github.com/SharePoint/sp-starter-kit/pull/60/commits/4f468197b7a9899fb6bdd4c966282350cb3ff013

**Comment by Chris-Leeworthy** [comment]
Great, this is exactly what was needed.  Thank you
