### ISSUE TITLE
Personal Email and Calendar Web Parts: Getting "Additional credentials are required to show this page correctly" message, and does not show 

### ISSUE THREAD

**Issue by kylomon** [SharePoint/sp-starter-kit#58]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Expecting the web parts to show personal mail or events without prompting for additional credentials. 

#### Observed Behavior

When adding the Personal Mail or Personal Events web parts a message pops up that says "Additional credentials are required to show this page correctly." When I click "OK" I am prompted for a login. When attempting the additional login, I am getting an error. 

"Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'c58637bb-e2e1-4312-8a00-04b5ffcd3403'. "

and also a message: 

Request Id: 4b9e1a6f-7577-4f11-9dd1-5806903f1f00 
Correlation Id: 2d0969be-7b36-4147-a749-d8f1dc2d6353 
Timestamp: 2018-06-27T15:44:48Z 
Message: AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'c58637bb-e2e1-4312-8a00-04b5ffcd3403'. 
Advanced diagnostics: Enable 
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.
#### Steps to Reproduce
Add the Personal Email or Personal Calendar web parts to a Modern Page.

**Comment by eoverfield** [comment]
Those webparts are using the new SPFx Graph client. The url's should be provided by SP for us. First thoughts, have you approved the API requests that are required after the sppkg solution has been deployed? That is found in API management in the SPO Preview Admin Center.

**Comment by bcameron1231** [comment]
Closing - Answer and Feedback has been provided.
