### ISSUE TITLE
App Package Not Valid

### ISSUE THREAD

**Issue by bergersj** [SharePoint/sp-starter-kit#6]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

To package the solution and upload the sharepoint package file to my app catalog. 

#### Observed Behavior

Uploaded .sppkg file to app catalog, but Valid App Package column has value of No with Error in App Package also displayed on column value.

#### Steps to Reproduce

Inside Solution folder, install NPM and gulp, adjust the write-manifest.json to have a cdnBasePath value which is my sharepoint assets folder. run gulp bundle -ship, upload files from deploy folder to sharepoint asset folder. run gulp package-solution -ship. upload .sppkg file to app catalog.

**Comment by garrytrinder** [comment]
Same, also the same if I upload the sppkg file from the repo :(

**Comment by tchagan** [comment]
Same here, tried both bundling and packaging the source to a sppkg and the sppkg from the repo, both had this error.

**Comment by bcameron1231** [comment]
As talked about on the PnP SIG call this morning, it may be because API Management is missing from the admin center in your tenant. @garrytrinder  Thanks for the info as well.

**Comment by garrytrinder** [comment]
I've now got this working, it was a tenant issue for me.

The API Management section of the new SharePoint Admin Portal was not showing for me, which is required for the AAD integration in SPFX to work, see https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#manage-permission-requests

My tenant was on targeted release for specific users, I changed this to everyone and after 5-10 mins the API Management section appeared. I was then able to successfully upload the package to the App Catalog and deploy. (Admin Portal -> Settings -> Organization Profile)

![image](https://user-images.githubusercontent.com/11563347/40495074-37b9b6c8-5f6e-11e8-96bd-25ec5659a8af.png)

**Comment by asumner** [comment]
@garrytrinder  thanks for detailing that, we have wasted a few hours and we changed the release on our test tenancy and package upload worked!

**Comment by dpobo** [comment]
I had the same issue after install/uninstall the application.
I managed to resolve it by deleting manually the entry for my application in a list which it's hidden at 'Lists/ComponentManifests', so you can access from 'site/yourappcatalogsite/Lists/ComponentManifests
