### ISSUE TITLE
Error Provisioning Site

### ISSUE THREAD

**Issue by spo-theworst** [SharePoint/sp-starter-kit#62]
I have an o365 developer site. 
I am the tenant/global admin.
I set targeted release for everyone.
I am admin of Taxonomy/Term Store.
I have newest PnP PowerShell:

Name                          Version    
----                          -------    
SharePointPnPPowerShellOnline 2.27.1806.1
SharePointPnPPowerShellOnline 2.27.1806.1
SharePointPnPPowerShellOnline 2.27.1806.0

1. Download starter kit, extract.
2. Create PnP-CollabFooter-MyLinks property
3. Get StockInfo API key
4. Upload sharepoint-starter-kit.sppkg from package directory to my App Catalog
5. Deploy sharepoint-starter-kit.sppkg by sharing to myself
6. I run ISE as admin & issue Connect via PnP -url https://myspdevelopersite.sharepoint.com
7.  then issue:  Set-Location C:\Users\aspnetdev\somedir\spdir\starterkit\provisioning
8. Then I run:  PS C:\Users\aspnetdev\somedir\spdir\starterkit\provisioning> .\deploy.ps1 -TenantUrl https://myspdevelopersite.sharepoint.com -siteprefix demo

The following output occurs:

Reading Site Hierarchy from ./hierarchy.json
Creating https://myspdevelopersite.sharepoint.com/sites/demoportal
New-PnPSite :
{"d":{"Create":{"__metadata":{"type":"SP.Publishing.CommunicationSiteCreationResponse"},"SiteStatus":3,"SiteUrl":""}}}
At C:\Users\aspnetdev\somedir\spdir\starterkit\provisioning\functions.ps1:174 char:13
+             New-PnPSite @hubParams
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.NewSite

9. I stop script.

This happened several times. I found potential solution online, and have run these statements (prior to the .deploy ps1 script):

//permanently delete all deleted sites
Connect-SPOService -Url “https://myspdevelopersite-admin.sharepoint.com”
Get-SPODeletedSite | foreach { Remove-SPODeletedSite -Identity $_.Url }

//Remove hubsite associations
Get-SPOHubSite | ? {$_.Title -eq “PnP SP Starter Kit”} | Unregister-SPOHubSite

I have also tried changing prefix of 'demo' to something else.

Each time, same error. Previously I still let the entire script run in the SPO Mgmt Shell. Same thing. I have targeted different sites (team collections new experience). Same thing.

Am I doing it wrong?

Can I manually provision the first part, then run the rest of the script?

**Comment by eoverfield** [comment]
You are showing three versions of PnPPS installed, two of which are the same. Is that correct?

**Comment by spo-theworst** [comment]
Hello,

Thanks for getting back to me.

I do have 3 versions semi-installed:

Version 1: the PnP Business Intranet starter kit that I discovered when this version of the Starter Kit didn’t work for me.

Version 2: The version I tried to install a few minutes prior to submitting this ticket.

Version 3: The version I tried to install by changing the site name prefix immediately prior to submitting this ticket.

I can delete these versions, I do not need all 3. Just want 1 good working Starter Kit.

Thank you,

Jason Smith

**Comment by dougraheem** [comment]
@spo-theworst Please make sure you have installed stable release of PNP Powershell. I have 2.27.1806.0 installed and working fine. Just to avoid confusion, I will recommend uninstalling older versions.

**Comment by spo-theworst** [comment]
The documentation says to install the most recent version?

**Comment by eoverfield** [comment]
I don't believe the version of PS Is causing your issue, but it does not hurt to clean up your system as it may help. I suggest you uninstall all versions of PnP PS. The fact that you have two copies of the same version is not good. Verify all versions are gone.

Now reinstall manually the latest version from: https://github.com/SharePoint/PnP-PowerShell/releases
2.27.1806.1

**Comment by spo-theworst** [comment]
I have manually reinstalled as requested.

Next steps: delete installations, attempt new installation?

New parameters?

**Comment by dougraheem** [comment]
@spo-theworst in case you are referring to Deploy command, then just increment your prefix

In my case, I went up to 6 iterations. demo1, demo2 .. demo6 
=D

**Comment by dougraheem** [comment]
@spo-theworst  here is summary of my steps I put on some other thread:

Here is a summary of working steps:
1- Ensure that you meet the requirements for SharePoint Framework development and are using the latest version of PnP PowerShell

2- Prepare your tenant, by accomplishing the tasks highlighted in document Preparing your tenant for the PnP SharePoint Starter Kit.

3- Upload and deploy the sharepoint-starter-kit.sppkg from the /package folder to your app catalog.
This.will produce error "Error in the Application" when you upload package to app catalog but that is ok some how.
4- Make your account term store administrator.
5- Set your tenant to First Release

**Comment by spo-theworst** [comment]
awesome, thanks. one question: did you happen to run any site cleanup scripts/commands?

like the ones listed in this page:

https://beaucameron.net/2018/05/22/pnp-sp-starter-kit-hints-and-tips/

**Comment by dougraheem** [comment]
@spo-theworst  Nope. But I incremented my siteprefix every time I run Deploy PowerShell command. 
=D

**Comment by spo-theworst** [comment]
thank you, will try & let you know asap!

**Comment by spo-theworst** [comment]
Successful implementation. Thank you all for assistance. The site is itself is beautiful, excellent work.

**Comment by bcameron1231** [comment]
Closing - Author confirmed this was fixed.
