### ISSUE TITLE
error on uploading portal.xml

### ISSUE THREAD

**Issue by hassannawaz1** [SharePoint/sp-starter-kit#69]
Apply-PnPProvisioningTemplate : Specified argument was out of the range of valid values.
At D:\hassannawaz\sp-starter-kit-master\provisioning\deploy.ps1:124 char:1
+ Apply-PnPProvisioningTemplate -Path "$PSScriptRoot\portal.xml" -Parameters @{"We ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by dougraheem** [comment]
Please check your PNP Powershell version. It should be latest stable.

**Comment by eoverfield** [comment]
@hassannawaz1 could you turn on trace logging and try again. we want to know what aspect of applying the portal.xml provisioning template is failing.

Set-PnPTraceLog -On -Level Debug

**Comment by bcameron1231** [comment]
Hi, I am working through cleaning up some of the issues on this list. I understand this is an old ticket, and may not affect you anymore. Can you confirm whether this is still an issue for you?
