### ISSUE TITLE
shrink large images

### ISSUE THREAD

**Issue by alirobe** [SharePoint/sp-starter-kit#7]
#### Category
- [x] Enhancement

Could you please reduce the image size in the assets, as it increases bundle size significantly. My dodgy Australian internet thanks you!

**Comment by fthorild** [comment]
I can give this a go - I'll compress the jpegs as the png's are used in the wiki/readme and not in the starter-kit installation itself. I will keep the file names and make a PR when done.

**Comment by VesaJuvonen** [comment]
Thanks, @fthorild for the optimized images.
