### ISSUE TITLE
App Management Page not working (/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement)

### ISSUE THREAD

**Issue by BasantPandey** [SharePoint/sp-starter-kit#72]
> I am trying to deploy the sp-stater-kit. I am stuck in the App Management page. As I am not able to see this link in my Office 365 tenant site, to activate this feature do I need to enable the specific feature. 

![2018-07-03_16-04-29](https://user-images.githubusercontent.com/896016/42215329-b0e4e2ca-7edb-11e8-9a20-8bd4fd806188.jpg)

Can you please help me to fix this issue? 
 
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

**Comment by MarkusLanger** [comment]
Is your tenant in the "First Release" as [described](https://github.com/SharePoint/sp-starter-kit#pre-requirements) in the "Pre-requirements" section?

There should be a "Advanced" section with the "API management"
![image](https://user-images.githubusercontent.com/12131918/42221181-8cfccf26-7ed1-11e8-88ba-1ddd8eec6633.png)

**Comment by eoverfield** [comment]
@BasantPandey and per the documentation, ensure you wait at least 24 hours after enabling targeted release for all users to try again.

**Comment by BasantPandey** [comment]
@eoverfield yes, I waited for 24 hours, still I am not able to see the API Management section, is the there any specific licences required for this? I am using the tried version.

**Comment by BasantPandey** [comment]
Finally I updated the option suggest by @MarkusLanger. Now I am waiting for 24 hours to get the
