### ISSUE TITLE
GYP and NPM Errors when running scripts.

### ISSUE THREAD

**Issue by Lazermn03** [SharePoint/sp-starter-kit#74]
#### Category
- [X] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Expected behavior would be to have the tool deploy the sites as shown in the screenshots

#### Observed Behavior
When I run the Deploy.ps1 script I get the below output and the site doesn't look like the screenshots. It's missing web parts and the footer section.
![image](https://user-images.githubusercontent.com/35646712/42240700-bf1af57c-7ecd-11e8-967b-c5024b4cc667.png)

Screenshot of sites post build:
**Portal:
![image](https://user-images.githubusercontent.com/35646712/42240778-0a9eb768-7ece-11e8-9c82-e1ea475d7ebd.png)

HR:
![image](https://user-images.githubusercontent.com/35646712/42240808-1f4d81c6-7ece-11e8-9eef-941a5352afb9.png)

Marketing:
![image](https://user-images.githubusercontent.com/35646712/42240816-2a1101fa-7ece-11e8-9bf0-0bbad443fa8f.png)

**

#### Steps to Reproduce
I run the shown command in the screenshot after following the steps in the readme file.

**Comment by eoverfield** [comment]
It looks as though your sppkg is not deploying correctly. This could also be because the script is trying to rebuild the SPFx solution.

First, what version of node do you have installed?
node -v 

Next, I suggest you attempt to add the SPFx solution manually and then try again.
https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/manual-deploy-sppkg-solution.md

**Comment by Lazermn03** [comment]
[cid:image001.png@01D412DC.2B4D0540]

I uploaded the file before, but it must have failed to deploy. I redeployed it and it’s working now. Not sure why the script is still failing though.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MrsNaniPenny** [comment]
Hi there

I am using deploy.ps1 to rebuild my sppkg after making a change to one of the web parts. However, when the command runs, I also get the above error. I am not trying to deploy the solution or provision anything else. I just want the solution to rebuild. 

I did, however, notice that the package is being referenced in a file location (_\..\solution\sharepoint\solution\_) that does not exist in this version of SP-Starter-Kit. I have changed it to _\..\package_ but I still get the gyp errors and the solution does not build.

I use this command to run the script:
_.\deploy.ps1 -TenantUrl $TenantUrl -Credentials $userCredential -Build -SkipSiteCreation -SkipSolutionDeployment_

I get this error:
![image](https://user-images.githubusercontent.com/42998687/45086179-e41da880-b102-11e8-9729-5e8e35244d4b.png)
![image](https://user-images.githubusercontent.com/42998687/45086212-f4358800-b102-11e8-8936-a40246e6d3fd.png)
![image](https://user-images.githubusercontent.com/42998687/45086242-ff88b380-b102-11e8-97b7-26435017234c.png)

What is causing this error and what can I do to rectify it?

I am using node v10.7.0

**Comment by eoverfield** [comment]
Your version of node is likely a cause. SPFx is designed to work with node lts, which currently 8.11.4 https://nodejs.org/en/. I suggest you use NVM or downgrade to 8.11.4 and try again. You can also manually rebuild the spfx solution by running

gulp bundle --ship
gulp package-solution --ship

in the solution folder. That will rebuild the .sppkg file and you can then manually upload that to your app catalog.

**Comment by MrsNaniPenny** [comment]
Thanks, @eoverfield . I ended up doing a workaround where I:

- renamed the .sppkg to .cab and extracted it
- looked for the correct code to replace in the ClientSideAssets folder, and saved
- drag back into Cab and
- renamed cab back to .sppkg.

**Comment by bcameron1231** [comment]
Closing - Workaround provided and working
