### ISSUE TITLE
Adding additional team sites and associating with Hub Site 

### ISSUE THREAD

**Issue by nicholas-morris** [SharePoint/sp-starter-kit#75]
I cannot seem to find the location in the deployment powershell commands of where to add additional team sites and associate with the Hub site? can someone point me in the right direction?

**Comment by waldekmastykarz** [comment]
Team sites are listed here: https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/hierarchy.json. The specified sites are picked up by the deployment script at https://github.com/SharePoint/sp-starter-kit/blob/7706afe20994cb6aad7215862f4345161046c2dc/provisioning/deploy.ps1#L63
