### ISSUE TITLE
Changing default footer links

### ISSUE THREAD

**Issue by nicholas-morris** [SharePoint/sp-starter-kit#84]
Can the default information in the footer be edited prior to deployment including support@contoso.com and site links? 

![image](https://user-images.githubusercontent.com/6046855/42424950-7f4a172a-8369-11e8-9932-b0bd87e56a43.png)

**Comment by nicholas-morris** [comment]
PnP-PortalFooter-Links.xml does not appear to allow editing of the bottom orange bar is this possible?

**Comment by eoverfield** [comment]
@nicholas-morris  PnP-PortalFooter-Links.xml is the PnP Provisioning template that deploys the footer link list for the expanded footer, as well as a few site columns and a content type used by this list. If you want to change the content in the orange bar itself, there are two places you should review.

First, the footer itself is an application customizer that the provisioning process as well as a site script add to sites via custom actions. During the addition process, properties are set for the SPFx extension including the copyright and support properties.

You will need to set these properties in both ./provisioning/hubsite.xml around line 500 where you should find: <pnp:CustomAction Name="PortalFooter" as well as in the site script, ./provisioning/collabcommunicationsite.json, around line 13 where you should find: clientSideComponentProperties...

Once you update these two files, you will need to re-provision the starter kit, in particular you are looking to have hubsite.xml re-provisioned to your hub portal, and the site script updated.

**Comment by VesaJuvonen** [comment]
Closing as @eoverfield answered on this.

**Comment by gokello** [comment]
@eoverfield : We have followed the steps to change the footer text (@Corpyright Contoso).  We re-provisioned (i.e. re-ran the deploy.ps1 script).  Still the Copyright Tag is not getting updated.  What are we missing?

**Comment by eoverfield** [comment]
@gokello you might want to try removing the custom actions / extensions from the portal and then re-running the deploy script. It could be that the provisioning template is ignoring the already added custom action.

I suggest powershell, in particular remove-pnpcustomaction
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpcustomaction?view=sharepoint-ps

**Comment by gokello** [comment]
Thanks @eoverfield. I used the remove-pnpcustomaction as also recommended by @bcameron1231 and it worked.
Thank you very much:
https://beaucameron.net/2018/07/19/customizing-the-pnp-starter-kit-for-office-365-part-1-portal-footer/

**Comment by Pen-Ace** [comment]
This was driving me crazy, finally sorted it.  Run this as admin on PS (change the fields as needed):

Connect-PnPOnline https://<your sharpoint>.sharepoint.com/sites/<Your site name>
Remove-PnPCustomAction -Identity "PortalFooter"

Add-PnPCustomAction -Name "PortalFooter" -Title "PortalFooter" -ClientSideComponentId b8eb4ec9-934a-4248-a15f-863d27f94f60 -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentProperties "{""linksListTitle"":""PnP-PortalFooter-Links"",""copyright"":""@Copyright <company name>, 2020-2021"",""support"":""<Email>"",""personalItemsStorageProperty"":""PnP-CollabFooter-MyLinks""}"

Hope this help. 
ACE
