### ISSUE TITLE
Error everytime running deploy.ps1

### ISSUE THREAD

**Issue by sharepointsuz** [SharePoint/sp-starter-kit#85]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
The script completes without any errors

#### Observed Behavior
I have created a new trial site, followed the guides making the tenant targeted release for all, added the user profile property, added the admin user to the TermStore Administrators and updated my version of PnP. Waited 24 hours before running the script. That was 2 weeks ago. I still get the following:
The sites are created but after it starts Provisioning solution, Provisioning Taxonomy, Applying template to hubsite I get this:
![image](https://user-images.githubusercontent.com/40970718/42427307-e0444330-8381-11e8-943f-02a5ce460a0b.png)

#### Steps to Reproduce

Run the deploy script as normal.

**Comment by eoverfield** [comment]
Please refer to the following doc for a few commands:
https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/common-provision-results.md

What version of PnP PS are you using? Could you provide the screenshot of the output? Command is found in docs above.

Could you also turn PnP Trace logging on so we can get more details on what is throwing the errors?

**Comment by sharepointsuz** [comment]
Thanks for the prompt reply!

I'm running v2.28.1807.0:
![image](https://user-images.githubusercontent.com/40970718/42430207-d78e694a-8391-11e8-851a-f8f8675acd88.png)

**Comment by eoverfield** [comment]
Ah, I bet that is it. You have many PnP PS versions installed, I bet one of the v2.25. versions is being used. My suggestion is you remove all of the old versions and try deployment again. You can get removal instructions from:
https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/common-provision-results.md#recommended-solution

Please let us know if that helps.

**Comment by sharepointsuz** [comment]
That was it! I just left the 2 most recent and it ran. 
Thankyou!
