### ISSUE TITLE
Ability to add other app's (such as a document library) and assoicate with hub site

### ISSUE THREAD

**Issue by nicholas-morris** [SharePoint/sp-starter-kit#87]
Is it possible somehow to add other app's such as a document library to the hierarchy.json file and associate them with the hub site  or is this only currently possible with team sites?

**Comment by eoverfield** [comment]
hiearchy.json is used only to describe what sites to auto provision when running the starter kit deploy.ps1 PS script.

If you want to add other apps, recommended approaches including updating one of the included PnP Provisioning templates, creating a new provisioning template and applying that to your specific sites, or you could create an additional site script / site design and using SPO management shell and PS, apply the site design over the site(s) you create.

There are additional options including creating a site design and site script first, then allowing the site creation process to run, and I am sure others can come up with yet more approaches. Any of these techniques would require that you customize the starter kit to meet your needs.

**Comment by nicholas-morris** [comment]
Has anyone out there got any sample PS Script of how to provision a site page, name it, add an app such as a document library and associate it with the hub site that I can use as a reference? Hopefully that I can simply insert into this solution :)

**Comment by eoverfield** [comment]
@nicholas-morris this starter kit has the scaffolding you need. The provisioning template to do much of what you need may be found here:
https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/hubsite.xml

Review line's 39 onward to add a page, add content, add components, libraries, etc. To provision this template to a site, you will want to review the general process here:
https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/deploy.ps1
