### ISSUE TITLE
Footers

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-starter-kit#90]
Hello,

Which file do i need to modify to change the footer on the main communications portal site ?

Thanks!

**Comment by eoverfield** [comment]
@gristy58 check out the following closed issue:
https://github.com/SharePoint/sp-starter-kit/issues/84

./provisioning/hubsite.xml in particular. You can also modify the collabFooter SPFx extension found in solution/src/extensions/collabFooter if you want to.

**Comment by ruben1980** [comment]
Hi, is there a way to remove the portalfooter completely?

**Comment by eoverfield** [comment]
@ruben1980 absolutely. Easiest way is to not activate it via a custom action in the provisioning template. Open https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/hubsite.xml in a text editor, look at line 500 (Currently) and remove the line:
<pnp:CustomAction Name="PortalFooter"... />

That will not deactivate the footer on an existing site though, for that you will need to use PowerShell.

**Comment by bcameron1231** [comment]
As @eoverfield just mentioned, you'll need to modify the hubsite.xml file or use powershell to do it. I have written about it, and code is available on this post https://beaucameron.net/2018/07/19/customizing-the-pnp-starter-kit-for-office-365-part-1-portal-footer/

**Comment by ruben1980** [comment]
Thank you verry much for your support!

**Comment by elpinto007** [comment]
Has anyone successfully managed to get the portalfooter into its own package to deploy? I am currently trying to do this but I am running into an error when I try to do a gulp bundle --ship.

Its complaining about :
`Error - [webpack] 'dist':
./lib/common/myLinks/MyLinksDialog.js
Module not found: Error: Can't resolve 'MyLinksStrings' in 'C:/dev/SharePoint Dev/git/sp-starter-portal-footer/lib/common/myLinks'`

I am not sure why its looking for that as a module.

**Comment by bcameron1231** [comment]
Yes I have successfully moved it out into it's own package. MyLinks is what is used in both the portal footer and the collab footer. You can find it in the common folder https://github.com/SharePoint/sp-starter-kit/tree/master/solution/src/common/myLinks

This is what is used when managing the personal links in both of the footer extensions. You'll need to pull this into your solution, and update your references accordingly.

It's currently imported in the PortalFooterApplicationCustomizer.ts on lines 21 & 22.

**Comment by elpinto007** [comment]
Yup, I brought across the common folder contents (mylinks). Refactored MyLinksDialog.tsx using the new CommandBar (icons in items are now iconProps). I got the references for mylinks in PortalFooterApplicationCustomizer.ts as well. 
I will push the change to my repository if you would like to look at the code.
One difference I noticed in the Lib folder is in MyLinksDialog.js, my file doesnt have "use strict"; at the top. 
Following this, I saw in my file:
`import styles from './MyLinks.module.scss';`
`import * as strings from 'MyLinksStrings';`
Whereas for the sp-starter-kit, the same lib file has:
`Object.defineProperty(exports, "__esModule", { value: true });`
`...`
`var MyLinks_module_scss_1 = require("./MyLinks.module.scss");`
`var strings = require("MyLinksStrings");`

I am not sure why thats happening to be honest

**Comment by elpinto007** [comment]
I think I might have found a clue. At the top of the MyLinksDialog.tsx file is this line:

`import * as strings from 'MyLinksStrings';`

I think this might be the culprit because when Gulp generates the JS files, something in the new libraries is not reading this reference correctly. 

I found this from this error message generated:
`Field 'browser' doesn't contain a valid alias configuration`

Digging further

**Comment by bcameron1231** [comment]
@elpinto007 I have made a comment on your new post #122 , please check it out :)

**Comment by bcameron1231** [comment]
Closed as this was answered.
