### ISSUE TITLE
Discuss Now Meeting Contents Error

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-starter-kit#91]
#### Category
- [ ] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

URL In Meeting Request

#### Observed Behavior

Meeting request is saved:

Let's discuss about this document: ${this.filePath}

#### Steps to Reproduce

Upload document to team sheet
Click Discuss now and Schedule meeting

**Comment by bcameron1231** [comment]
Hi, we are working through some of the older items in the issues list. It appears this issue is almost 2 years old. I am going to close this ticket, if this issue is still affecting you and your environment, please create a new issue in the issues list.
