### ISSUE TITLE
About deploying localized version of the sp-starter-kit

### ISSUE THREAD

**Issue by helpdsp** [SharePoint/sp-starter-kit#92]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Observed Behavior
While deploying the localized version of the SPFx web parts I notice that If App Catalog site collection is NOT created in English language the provision script will error out when uploading the solution file to the app catalog. I tested on Spanish based tenant and found out that App Catalog site collection must be created always in English language to ensure sp-starter-kit successful deployment and also to see the localized SPFx web parts working properly. I suggest we should point out in the documentation that  App Catalog should be in English language.

**Comment by absieee** [comment]
The pre-requirements section already lists that automatic end-to-end provisioning only works with English tenants:
![sp-kit](https://user-images.githubusercontent.com/22594092/42814774-356f0d68-89bd-11e8-84f4-cba308065615.PNG)

**Comment by helpdsp** [comment]
Yes, but recently resources files have been implemented and there are several languages supported now, in fact I did test deploying in different language than English. I am talking only about the app catalog site collection, that it;s required to be created in English language in order for the provision script to run properlly

**Comment by eoverfield** [comment]
@helpdsp there is no current plan I am aware of to move away from the 1033 requirement of the app catalog. There is of course localization allowed at the content site level. I am going to close this issue for now, if you have additional feedback or comments, please either re-open the issue or create a new one.
